Dallinger/Dallinger

.travis.yml
README.md
dev-requirements.txt
wallace/heroku/requirements.txt

I’ve been less than impressed with Coverall’s interface lately — time
to try something new.

Use Codecov, not Coveralls

---

docs/source/index.rst

Remove statement on “Alfred Russel Dallinger”. Oops.

Fix a branding bug

---

.travis.yml

This has been causing issues because some sites (postgresapp.com) show up as broken links even though they are fine.

Don't check for broken links when building docs

---

.travis.yml

This improves the speed of CI runs on Travis by caching dependencies.

Speed up Travis CI runs

---

.github_changelog_generator
.gitignore
.travis.yml
CHANGELOG.md
Dangerfile
scripts/github_releases.sh

This sets up Danger to check that PRs with the label "release" have updated change logs. It also add Chandler, a program that automatically syncs GitHub release notes with the change log, though in a dry run mode until it is tested further.

Set up a release process

---

dallinger/command_line.py
dallinger/heroku/requirements.txt

This install Dallinger via PyPi on Heroku, rather than installing it from GitHub. This fixes a bug where the demo-specific requirements were being overwritten by the generic Heroku requirements.

Install Dallinger via PyPi on Heroku

---

scripts/github_releases.sh

This fixes the permissions of the generated Chandler configuration file
so that Travis CI can automatically update GitHub releases.

Fix Chandler config. permissions

---

dallinger/frontend/static/scripts/dallinger.js

Some experiments depended on the underscored version of the names.

Fix backwards incompatibility

---

dallinger/__init__.py
requirements.txt

This commit adds a new submodule to Dallinger, dallinger.config, which
contains the contents of the experiment-specific configuration file,
automatically parsed as much as possible. This makes it possible, for
example, to access the “us_only” parameter of the “HIT Configuration”
section through:
```
dallinger.hit_configuration.us_only
```

Use localconfig for dallinger.config

---

dallinger/custom.py

Dallinger v2.3.0 unintentionally shipped with a breaking change.
Because routes no longer automatically rendered with the four
parameters in the query string that were hardcoded in psiTurk (hid_id,
assignment_id, worker_id, and mode), the consent forms all became
broken. This fixes the problem so that now the old demos still work.

Add a consent route

---

dallinger/command_line.py
dallinger/custom.py
dallinger/db.py
dallinger/experiments.py
dallinger/heroku/clock.py
dallinger/heroku/worker.py
dallinger/models.py
dallinger/networks.py
dallinger/nodes.py
dallinger/processes.py
dallinger/recruiters.py

According to PEP8:
```
Imports should be grouped in the following order:
standard library imports
related third party imports
local application/library specific imports
You should put a blank line between each group of imports.
```

Sort import statements

---

dallinger/models.py

Converts property1 from String to Text
Allows storage or strings of arbitrary length, which is useful if we want to store complex json objects
I have saved long strings

convert property1 from String to Text

---

dallinger/command_line.py

This allows requirements to be specified by URL, e.g.,
```
-e git://github.com/Dallinger/Dallinger.git#egg=dallinger
```

Allow requirements specified by URL

---

dallinger/frontend/static/scripts/dallinger.js

Previously, submitting the responses on a page also submitted the
assignment, which causes a problem if you don’t want the two to be
linked in that way (e.g., you have a questionnaire before and after the
experiment). This dissociates the two.
Fixes #284.

Refactor response submission

---

dallinger/command_line.py
dallinger/heroku/worker.py

We've been having trouble with the worker and clock processes on Heroku and think it may be due to Redis taking a long time to come online. This is a work-in-progress fix.

Fix clock and worker processes

---

dallinger/command_line.py

The —no-owner flag to fixes an issue where if the user is not set as a “superuser” in Postgres, the data export command fails because it tries to perform an action that only these superusers can do.

Add -no-owner flag to dallinger/command_line.py

---

docs/source/build_demo_docs.py
docs/source/conf.py
docs/source/index.rst

This puts the static files for demos into their own directories so that name conflicts do not occur. Note that Sphinx will still copy the files into its own `_images` folder, but it will properly handle name conflicts (I checked this) so that if two images have the same name, they will get properly renamed by Sphinx itself.
Fixes #216

Properly link in static files for documentation of demos

---

dallinger/command_line.py

To check if the Redis queue is available, we try to write to it.
However, sometimes the URL for the Redis queue is not immediately
available. The existing implementation retrieves this URL once and then
pings it over and over. The new implementation retrieves the URL once
per ping. Thus it is updated as soon as the URL becomes available,
preventing an infinite hang.

Fix bug in waiting for Redis

---

dallinger/command_line.py

Heroku has a Teams feature where groups of people can use shared billing and fine-grained permissions. This PR automatically transfers apps to a team if one is specified in `.dallingerconfig`, e.g.:
```
[Heroku Access]
team = dallinger 
```

Transfer application to Heroku team if specified

---

.coveragerc
.gitignore
.travis.yml
dev-requirements.txt
docs/source/developing_dallinger_setup_guide.rst
docs/source/index.rst
docs/source/running_the_tests.rst
docs/source/spelling_wordlist.txt
tox.ini

- Run coverage as a wrapper of nosetests rather than using nosetest's coverage plugin.
This fixes a problem where completely uncovered files were not reported.
- Also report on branch coverage.
- Make the build fail if coverage is under a threshold (currently 30%; we can increase it over time).
- Set up tox and make travis run tox.
This makes it easier to run the same tests locally that are run by Travis.
- Use Travis' matrix feature to run tests in parallel with building docs.
- Don't require Travis' sudo support. We don't need it and tests start faster without it.
- Add documentation about running tests
- Add missing documentation about installing the pandoc dependency
- Add a few missing words to the spelling list
- Add command to run flake8 (but don't run it automatically yet; I'll …

Misc improvements to testing infrastructure

---

.travis.yml
dallinger/command_line.py
dallinger/db.py
dallinger/experiments.py
dallinger/heroku/clock.py
dallinger/models.py
dallinger/networks.py
demos/rogers/experiment.py
demos/rogers/tests/tests.py
dev-requirements.txt
docs/source/conf.py
docs/source/running_the_tests.rst
setup.cfg
tests/_test_bartlett.py
tests/test_models.py
tests/test_networks.py
tests/test_processes.py
tox.ini

This fixes Python code formatting that doesn't conform to PEP8, and adds a job to tox and travis to fail if new formatting errors are committed.
I think the only noteworthy change here is comparing to `sqlalchemy.sql.expression.false` in query expressions instead of using `== False` which is disallowed by PEP8. It's a workaround that I found at http://stackoverflow.com/a/18998106
Enforcing PEP8 helps with readability of the codebase, which is important for a project involving multiple developers, and it's generally seen as a best practice for Python projects.
Tested by running flake8

Enable flake8 checks and fix errors

---

dallinger/command_line.py

This fixes two bugs in data exporting:
1. When the data directory already exists, we no longer fail because of the `makedirs` call.
2. There are a couple of subprocess calls that return error codes but which are harmless. We no longer fail to export the data in those instances.
Tested locally and by downloading data from Heroku with and without each change.

Bugfixes for data exporting

---

.hound.yml

Hound CI should respect the configuration of Flake8 as specified in `setup.cfg`.

Tell Hound CI to respect the configuration

---

dallinger/models.py

Fixes a problem where some workers seem to have longer ids. Closes #348.

Increase size of worker_id column

---

dallinger/command_line.py

This uses the --org flag to create applications directly under a team
if one is specified in the config.

Create team apps directly

---

dallinger/command_line.py

This fixes a data export issue that I believe has been encountered by @thomasmorgan, @mongates, and @Gecia. The issue arose because of an update to the Heroku CLI. The command to back up a Postgres database used to be:
```
heroku pg:backups capture
```
but is now:
```
heroku pg:backups:capture
```
To test the change, I confirmed that data can be exported using the latest version of the Heroku CLI. I haven't tested the backwards compatibility because I don't know how to downgrade to an earlier version of the Heroku CLI.

Update data export for new Heroku CLI

---

tox.ini

Some tox runs were failing because of outdated .pyc files. This deletes the files before running the tests.

Delete .pyc files before test

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
tests/experiment/dallinger_experiment.py
tests/test_experiment_server.py

Implements new experiment server route to check experiment status.
The route returns a `state` JSON object with `completed`, `unfilled_networks`, `nodes_remaining`, and `working_participants` attributes.
This route is automatically polled when an experiment is run via a python call to `experiment.sandbox()` or `experiment.deploy()`.
This implements Story 156.
There is an automated test that the route returns the expected values with the test experiment (which starts out in completed state). I also tested the route manually via debug mode, and confirmed that the route was polled when deployed in a heroku sandbox.

Implement experiment status route and completion check (156)

---

.travis.yml

Instead, use the Travis defaults: send the committer and the commit
author when a build becomes or continues to be broken, or when a
previously broken build becomes fixed.
I get so many Travis emails.
I want fewer.
It has not been tested.

Stop sending Jordan so many emails

---

.coveragerc
.gitignore
dallinger/command_line.py
dallinger/compat.py
dallinger/config.py
dallinger/default_configs/local_config_defaults.txt
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/gunicorn.py
dallinger/recruiters.py
dallinger/utils.py
docs/source/demoing_dallinger.rst
docs/source/spelling_wordlist.txt
tests/test_command_line.py
tests/test_config.py

This switches to a better (and working) approach for switching to the HotAirRecruiter when running in debug mode. It also adjusts the HotAirRecruiter to log the URL for a new participant when one is recruited, and monitors the output from debug mode to open the browser when that URL is printed.
With the removal of the psiTurk shell, it's no longer possible to request a participant URL using the `debug` command. This is an alternative approach.
(Note, this is currently targeted at the remove-psiturk-server branch, but it should be updated to target the development branch once PR 356 is merged.)
Tested by manually running `dallinger debug`

Open experiment for new participants in debug mode

---

.travis.yml
dev-requirements.txt
docs/source/running_the_tests.rst
pytest.ini
tests/_test_bartlett.py
tests/conftest.py
tests/test_agents.py
tests/test_clock.py
tests/test_config.py
tests/test_models.py
tests/test_networks.py
tox.ini

The pytest runner is more expressive and better fits the style of assertions being used in Dallinger. This change uses it in documentation and in tox, as well as removes the dependency on nosetests.
The nosetest runner presents poor assertion errors, pytest allows for providing significantly more debug feedback, as well as good support for fixtures that make tests faster and more reliable.
Running the tests, and observing better output than nose.

Switch to using pytest as the test runner.

---

dallinger/command_line.py
dallinger/config.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/heroku/tools.py
demos/chatroom/experiment.py
tests/test_command_line.py

Updates for remove-psiturk-server (based on stories/136-debug-recruiter to support configuration writing) to use new configuration object universally to get and set config.

Update command line, demos, etc. to use new configurator

---

.coveragerc
dallinger/experiment_server/experiment_server.py
dev-requirements.txt
tests/conftest.py
tests/test_command_line.py
tests/test_config.py
tox.ini

This fixes #396 by configuring coverage.py to initialize for subprocesses started during test runs, and then combining all the coverage data before reporting.
This helps us get coverage for modules like `command_line.py` and `experiment_server.py` that are only run in a separate process.

Collect coverage for code run in subprocesses

---

dallinger/config.py
tox.ini

Previously, when a local config.txt cannot be found in the current
working directory, a value error was raised. This PR allows the
configuration to load even when there is no such config.txt. This
makes it possible to use the configuration even outside the context of
an experiment directory (e.g., to get AWS keys in a function that loads data from S3, for use in analysis scripts).

Load configuration even without local config.txt

---

dallinger/config.py
demos/2048/config.txt
demos/bartlett1932/config.txt
demos/chatroom/config.txt
demos/concentration/config.txt
demos/function-learning/config.txt
demos/iterated-drawing/config.txt
demos/mcmcp/config.txt
demos/rogers/config.txt
demos/sheep-market/config.txt
demos/snake/config.txt
demos/vox-populi/config.txt

There's a parameter `anonymize_data` that's unused. This PR removes it. The behavior will soon be to do this anonymization by default (see `data-tools-2` branch), with a `--no-scrub` option to keep PII in the exported data.

Remove unused parameter "anonymize_data"

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/models.py
dallinger/mturk.py
tests/test_experiment_server.py
tests/test_mturk.py

This prevents a request to AWS to extend the hit from causing a fatal error/death spiral
I have made the following changes:
1. the psiturk recruiter commits on init, this means whenever we are about to get in touch with AWS through psiturk we commit the current transaction first.
2. When recruiting participants Dallinger tries to extend the duration of the hit before opening more slots for participants
3. contact with AWS is put in try/except brackets with informative error messages as well as tracebacks
This fixes an issue that arose when a request to AWS to add more time failed (even though a request to add more participants succeeded) causing the db to roll back to a state that could not accent the new participants that had been recruited.
I ran a small experiment and it worked fine. …

Defend experiment server against AWS

---

dallinger/__init__.py
dallinger/command_line.py
dallinger/registration.py
docs/source/aws_etc_keys.rst
docs/source/index.rst
docs/source/registration_on_OSF.rst
tests/test_registration.py

Dallinger now integrates with the [Open Science Framework](https://osf.io/) (OSF), creating a new OSF project and uploading experiment code to the project on launch. To enable, specify a personal access token ``osf_access_token`` in your ``.dallingerconfig`` file. You can generate a new OSF personal access token on the [OSF settings page](https://osf.io/settings/tokens/).
Next steps include uploading data to the OSF project on export.

OSF integration

---

.travis.yml
setup.py
tox.ini

Fixes an issue on PyPI where the README was not being rendered correctly:
vs.

Fix issue with README formatting on PyPI

---

dallinger/config.py
tests/test_config.py

Make it possible to set config variables via `set`:
```
config.set("mode", u"live")
```

Enable setting config variables through config.set

---

dallinger/command_line.py
setup.py

Fixes a bug where experiments cannot be launched on Heroku because `setup.py` tries to install something that depends on `pandoc`, which isn't available. This PR prevents that installation from happening on Heroku. I tested it by launching an experiment in sandbox mode.

Don't install setuptools-markdown on Heroku

---

dallinger/command_line.py
setup.py

Environment variables set by user are not available when setup.py
is run, so default to one that is alway present when on Heroku.

Use DYNO environment variable

---

dallinger/command_line.py
dallinger/config/.dallingerconfig
dallinger/default_configs/local_config_defaults.txt
dallinger/experiment_server/gunicorn.py
docs/source/aws_etc_keys.rst

This fixes an issue where `debug` mode does not open browser windows for recruitment if the log level is too high. This sets it to zero when in debug mode. Along the way, it cleans up some other log-level-related code.

Log level in debug mode

---

docs/source/conf.py

MathJax, which is currently unused, causes a loading message to flash
at the bottom left corner of every documentation page. This removes
MathJax, thereby removing the flashing message.

Remove MathJax

---

dallinger/command_line.py
tests/test_command_line.py

Closes #200.
Prints the version number in the header.
This is useful because when people share log output errors, we can verify that they're using the stated version of Dallinger.
Test added to suite.
```
❯ dallinger debug --verbose
____        ____
/ __ \____ _/ / (_)___  ____ ____  _____
/ / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
/ /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
/____/
v2.7.0
Laboratory automation for
the behavioral and social sciences.
```

Add version number to header

---

dallinger/command_line.py
dallinger/config.py
dallinger/data.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/heroku/clock.py
dallinger/heroku/tools.py
dallinger/recruiters.py
demos/chatroom/experiment.py
tests/conftest.py
tests/test_command_line.py
tests/test_config.py
tests/test_heroku.py
tests/test_recruiters.py

Simplifies the configuration API naming.
Before:
`config.load_config()`
`config.write_config()`
`config.load_from_config_file()`
After:
`config.load()`
`config.write()`
`config.load_from_file()`
Removes redundancy.
All hit by the test suite.

Simplify configuration API naming

---

dallinger/data.py
tests/test_data.py

This changes the boto API used to connect to S3 to one that is more explicit about which AWS region to use.
This fixes a `IllegalLocationConstraintException` error I was getting in tests.
I checked that I can successfully connect to S3 using this function with a couple different AWS accounts, and I ran tox.

Be sure to specify the region when connecting to boto

---

dallinger/command_line.py
dallinger/data.py
dallinger/default_configs/local_config_defaults.txt
dallinger/heroku/tools.py
demos/rogers/tests/tests.py
tests/test_command_line.py

Removes all instances of `shell=True`. Closes #353.

Don't execute subprocess commands in shell

---

.travis.yml
dallinger/command_line.py
dallinger/experiment_server/gunicorn.py
docs/source/demoing_dallinger.rst
docs/source/installing_dallinger_for_users.rst
setup.cfg
tests/test_command_line.py

This change sets the debug command line tool to use heroku's local plugin rather than directly invoking scripts.
The `dallinger debug` command now calls `heroku local` in the context of the created experiment, delegating responsibility for invoking processes to heroku itself. This adds a heroku dependency for users not planning on launching real experiments, who otherwise wouldn't need it. It also makes the debugging more representative of real experiments.
In addition, this tidies some of the output of the debug command to make it more user friendly, and updates documentation.
This makes the debug command much more representative of how real applications are deployed. Specifically, it is now possible to rely on workers and clocks being available in debug mode.
Manual testing only. 
N/A

Use heroku local for local debugging

---

dallinger/config.py
dallinger/recruiters.py
demos/2048/config.txt
demos/bartlett1932/config.txt
demos/chatroom/config.txt
demos/concentration/config.txt
demos/function-learning/config.txt
demos/iterated-drawing/config.txt
demos/mcmcp/config.txt
demos/rogers/config.txt
demos/sheep-market/config.txt
demos/snake/config.txt
demos/vox-populi/config.txt
docs/source/configuration.rst
docs/source/extra_configuration.rst
docs/source/index.rst
docs/source/spelling_wordlist.txt
tests/experiment/config.txt
tests/test_recruiters.py

This PR makes a few tweaks to the configuration:
+ Removes `num_participants` from the default config. (It's experiment-specific.)
+ Renames `amt_keywords` to `keywords`
+ Add documentation for the configuration object

Various tweaks to configuration

---

dallinger/command_line.py

(I missed two instances of the nixed Heroku email/password config
variable in PR #503.)

Remove two invalid config variables

---

Vagrantfile
docs/source/developing_dallinger_setup_guide.rst
docs/source/spelling_wordlist.txt
docs/source/vagrant_setup.rst
setup.cfg
tox.ini

This adds a simple Vagrant file using Ubuntu Xenial that installs according to the developer installation instructions.
The aim of this change is to make bootstrapping for new developers simpler, and to provide easy isolation of Dallinger components for developers who need that. It also makes installation on Windows easier.
This has been my primary development environment for about 100 hours of work on the Dallinger project, both on Mac and Ubuntu hosts.

Add Vagrant setup

---

dallinger/command_line.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/templates/waiting.html
demos/chatroom/experiment.py
demos/chatroom/static/scripts/experiment.js
demos/rogers/experiment.py
docs/source/learning_to_use_dallinger.rst
docs/source/required_experimental_files.rst
docs/source/spelling_wordlist.txt
docs/source/the_experiment_class.rst
docs/source/waiting_rooms.rst
docs/source/web_api.rst
tests/experiment/dallinger_experiment.py
tests/test_experiment_server.py

This moves the chatroom implementation of the waiting room to core and begins documentation.
The chatroom implementation of the waiting room has been moved into core Dallinger, using the same functionality. The reliance on global variables and polling has not been removed.
This is an intermediate step towards high quality waiting rooms, by making the existing chatroom implementation the standard.
Additional unit tests for formalised interfaces, manual testing of chatroom and of instructions to apply waiting room to other experiments (using the snake demo).
N/A

Move chatroom waiting room implementation to core

---

dallinger/command_line.py
dallinger/db.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/gunicorn.py
dallinger/experiment_server/sockets.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/templates/waiting.html
demos/chatroom/static/scripts/experiment.js
demos/chatroom/static/scripts/reconnecting-websocket.js
requirements.txt
tests/conftest.py
tests/test_command_line.py
tests/test_db.py
tests/test_experiment_server.py
tests/test_sockets.py

This includes two improvements to the waiting room:
- Make the node creation / network filling endpoint run using the SERIALIZABLE postgresql isolation level, and retry any transactions that fail due to coincident writes by another client.
- Communicate notifications about how full the waiting room is using websockets (set up using flask-sockets -- important note: this involves switching gunicorn to run using a gevent-based worker).
The isolation level change fixes an issue where network nodes might not be linked correctly once the quorum is reached and all workers move to the experiment.
The websockets change allows for less latency in updating clients as the number of participants changes. It also lays the groundwork for the use of websocket communication in actual experiments.
More …

Waiting room improvements

---

dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/sockets.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/templates/waiting.html
demos/chatroom/config.txt
tests/experiment/dallinger_experiment.py
tests/test_sockets.py

A couple fixes for the websocket-based waiting room:
1. Send a ping message every 30s so that Heroku doesn't close the websocket connection after 55s.
2. Wait to send the create participant request until the websocket connection has been opened, so that the user receives the quorum update for their own participant.
Without these fixes, the waiting room doesn't work reliably on Heroku.
I ran `dallinger sandbox` using this branch (which requires updating demos/chatroom/requirements.txt to use dallinger from git) and confirmed that Jesse and I could enter the chatroom.

Fix issues with websockets on Heroku

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/sockets.py
dallinger/nodes.py
tests/test_sockets.py

Allow experiments to define background tasks and channels to be set up by the framework on experiment launch
* Experiments can define a list property `background_tasks` which will be run as `gevent` `greenlet`s on experiment launch
* Experiments can define a `channel` property which will be added to the set of active pubsub channels, and the experiment object itself will be subscribed to the channel on launch
* Adds support for subscribing to a specific channel when registering a websocket via the `/receive_chat` route
* Adds a new `/send_chat` route, allowing websocket clients to send messages to a pubsub channel
The Griduniverse demo requires a flexible bidirectional communication channel between clients and the Experiment process
* Changes to the ChatBackend class have automated tests …

Support experiment-defined background tasks and pubsub channels

---

dallinger/bots.py
dallinger/config.py
tests/conftest.py
tests/test_bots.py

This change allows users to specify the webdriver_url configuration parameter, which points at a Selenium Server, such as http://192.168.1.2:4444/wd/hub. If this is specified the webdriver.Remote backend is used.
In addition, webdriver_type determines the browser being used. If a URL is specified these are passed as desired_capabilities to the hub server, otherwise it is used to pick a local webdriver. Currently supported values are 'phantomjs' and 'firefox'.
This allows users to see the bots running in a real browser, to aid debugging, or to take advantage of browser specific features.
This is being used to develop the griduniverse bot

Support Selenium drivers other than local PhantomJS

---

.travis.yml
dallinger/db.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/templates/waiting.html
demos/chatroom/config.txt
demos/chatroom/experiment.py
demos/chatroom/static/scripts/experiment.js
tests/experiment/dallinger_experiment.py
tests/test_db.py

This is for Scrumdo story 176 (iteration 8). It makes it possible to use the waiting room to fill multiple equal-sized networks in sequence as participants arrive.
The chatroom demo is adjusted to support this. To fill multiple networks, set the `repeats` config setting to a value > 1. The recruiter will initially recruit `repeats * n` participants, where `n` is the number of participants per network.
Related changes:
- Delegate choosing the network for a new participant to a `choose_network` method on the experiment. This is so the chatroom experiment can fill networks sequentially rather than randomly.
- Adjust the `success_response` function in `experiment_server.py` to handle returning a response with an arbitrary number of key-value pairs.
- Make sure the websocket message with the …

Make waiting room handle filling multiple networks

---

Dangerfile

@DallingerBot complains when the `feature` label is used on a PR because it doesn't recognize that. This fixes it.

Put a sock in @DallingerBot

---

docs/source/command_line_utility.rst

Remove duplicate 'summary' field in the docs.
Fixing typo.

Typo, duplicate summary text

---

Vagrantfile
dallinger/recruiters.py
dallinger/utils.py

Automatically load balances between all ports exposed by local web processes. This improves bot performance, in conjunction with changes already on development.
Previously, all users would connect to web.1, which would cause significant delays when spawning large numbers of bots, as well as increased load for web sockets.
Tested while on `bot_queue` branch manually with Griduniverse

Balance web locally

---

dallinger/bots.py
docs/source/command_line_utility.rst
docs/source/index.rst
docs/source/running_bots.rst
docs/source/spelling_wordlist.txt
docs/source/the_experiment_class.rst

Provides initial documentation on how to implement and run bots in Dallinger, including scaling concerns.
The Griduniverse experiment is rather processor and RAM intensive on the client side. Some changes were made to increase performance, however other changes regarding how to run the Selenium server cannot be included in the code. This PR formalises the discussions we've been having in development about how to run bots, and includes specific advice for choice of browser and performance.
There are no code changes, only documentation. They need a test reader for style and substance.

Add documentation on bots

---

dallinger/command_line.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
demos/bartlett1932/config.txt
tests/conftest.py
tests/test_command_line.py
tests/test_experiment_server.py

This branch implements explicit error handling and logging in the experiment server's `/launch` route. In addition, it adds some additional error handling and logging to the command line's `deploy_sandbox_shared_setup` call to the experiment `/launch`
These changes are intended to address the problem described in issue #480.
Automated tests have been added for the experiment server `/launch` route in success and failure conditions. The automated test suite runs successfully with these changes.

Better error handling in command line calls to /launch

---

demos/mcmcp/static/scripts/experiment.js

When running a long chain, @jcpeterson noticed that every so often the
mapping between the "left" and "right" buttons flipped. The error was
non-deterministic and hard to predict. After a long debugging session,
we realized that the order of infos returned by the
`node/<node_id>/infos` route is non-deterministic (or at least not
always sequential in node id). This is a fix that behaves properly no
matter what order the returned infos are sorted in.
Closes #570.

Fix sort order issue in MCMCP demo

---

dallinger/command_line.py
tests/test_command_line.py

PR #566 adds a verification check for app ids. I changed this to use Click's [callback feature](http://click.pocoo.org/5/advanced/#parameter-modifications), which broke a bunch of stuff by making the `--app` flag mandatory for deployment and sandboxing. This fixes those problems.

Verification fixes

---

dallinger/command_line.py
dallinger/config.py
tests/test_command_line.py
tests/test_config.py

Add payment check method, change ValueErrors to be TypeErrors
#337 asked for better error checking on MTurk payment. While this was partially fixed in commit 3027f0f369df42686bf6974a9b17fdf3826a6697, there are still issues when submitting a config where `base_payment` is a negative number or a large float.
`dallinger verify` using an different `base_payment` values in `config.txt`

Add payment check method

---

dallinger/default_configs/local_config_defaults.txt

This changes the default gunicorn port to 5000 (for consistency with some developers who already have it configured that way; we want a consistent port for browser-sync to proxy in Dallinger/Griduniverse#63

Default port 5000

---

dallinger/frontend/static/scripts/dallinger.js
demos/bartlett1932/static/scripts/experiment.js

Allow experiments to prevent exit or reload from experiment pages by setting prevent_exit to true after dallinger.js is loaded.
Story 188 calls for the removal of the prevent exit functionality, but was amended to make it configurable.
Tested with the Bartlett1932 demo. Experiments need to do nothing to get the default allow exit behavior.

allow reload or exit by default, but add a simple way to prevent exit

---

demos/mcmcp/experiment.py

In some cases, if request from the client-side are not received, both of the two infos on each mcmcp trial will remain marked as chosen=False. Creating a new node for that participant or a new participant is then impossible, and there is no mechanism to halt the assignment afterwards. 
A very simple data check using the standard function is added that checks that at least one info is marked as chosen=True. If not, the participant is failed in the usual manner.
This happened to me twice in real experiments and it took a while to figure it out. It can randomly appear any time and make long MCMCP chains impossible, which are essential for using it in practice.
I've run about 1000 trials in a real experiment, and this does the trick. The rate of error before was about 2%, and no new cases …

Add checks to catch failures to mark an info true

---

dallinger/command_line.py
dallinger/heroku/__init__.py
dallinger/heroku/tools.py

`dallinger monitor` opens the Heroku dashboard to the launched app,
opens the MTurk console, opens the Papertrail logs, connects to the
database using Postico, and then runs a loop that prints the summary
every 10 seconds.

Add CLI command for monitoring

---

dallinger/frontend/static/scripts/dallinger.js

This creates `Dallinger`, a new JS module provided by `dallinger.js`. Eventually, this should hold all the experiment-agnostic code. For now it contains only one function, `Dallinger.submitQuestionnaire`, which serializes the entire form on `questionnaire.html` and submits the responses as a single entry in the Question table. None of the in-Dallinger demos have been modified to use this. I figured we'd wait until a 4.0 release that puts everything inside a `Dallinger` module that has more than just one function. This was created for the purposes of https://github.com/Dallinger/Griduniverse/pull/69, which has a 20-item survey that is not well-served using the existing form submission tools.

Create JS module namespace with a questionnaire submitter

---

dallinger/command_line.py
dallinger/experiment.py
dallinger/experiments/__init__.py
tests/test_experiment_server.py

Experiments wrapped in python packages may not contain a requirements.txt file or a README in the same directory as the experiment.py. The command line tool (which is used to run the experiments in the python API) does not need to check for those files. Additionally, this branch removes a spurious import time config side-effect and ensures that custom config variables are registered in a timely manner.
This is required for story DA-106, supporting Griduniverse as a PyPI package.
Automated tests ran successfully. I also manually ran the Griduniverse `packaged` branch through a debug session via the API.

Support for Packaged Experiments

---

dallinger/command_line.py

When there is both a local and a Dallinger version of a template, defer
to the local version. Note that this conflicts with the verification
policy that prevents local copies of Dallinger templates. I think this
policy is more sensible.

Defer to local files

---

dallinger/experiment_server/sockets.py
dallinger/frontend/static/scripts/dallinger.js
tests/test_sockets.py

This fixes a problem where only the web worker which handled the `/launch` request would start a greenlet to receive messages from redis. That had the side effect of causing some clients to not receive messages meant for them (see https://github.com/Dallinger/Griduniverse/issues/71 for one example).
There are a couple of minor semi-related changes:
- Log the process id and greenlet id for each log entry from sockets.py to help with debugging what's going on.
- No longer subscribe to the `quorum` channel by default.
Tested with the automated tests and by running locally and confirming that I don't see the problem I did before.

Make sure each web worker listens for redis channel messages

---

dallinger/recruiters.py
tests/test_environments.py
tests/test_recruiters.py

These changes support the ability to run experiments which calculate bonus payments for participants with Recruiters other than the MTurkRecruiter.
Upon experiment completion and submission, if an experiment returns a non-zero value from its `bonus()` method, the active recruiter's `reward_bonus()` method will be called. `reward_bonus()` is really part of the `Recruiter` interface and should be supported by all recruiter implementations.
The Griduniverse demo will support participant payment, and it's helpful to test this using the `HotAirRecruiter`.
This has been testing with a combination of automated and manual tests.

Story 205: pay participant bonus

---

tests/conftest.py
tests/test_agents.py
tests/test_environments.py
tests/test_examples.py
tests/test_heroku.py
tests/test_information.py
tests/test_models.py
tests/test_networks.py
tests/test_processes.py
tests/test_recruiters.py
tests/test_sources.py
tests/test_transformations.py

Make use of the `db_session` fixture for tests which interact with the database session.
Refactor tests to use the existing test fixture.
* Removes duplication
* Makes it easy to opt in or out of database setup/teardown on a test-by-test basis, rather than a class-by-class basis, allowing tests which don't need it to run faster.
No changes to production code. Test refactoring only.

Tests cleanup and speedup

---

dallinger/data.py
tests/test_data.py

Replace the shutil.make_archive() function with a ZipFile function that does the same compression of the archive, except it allows you to pass the arguments `Zip64=True` for large files.
Issue #588 discovers a bug where shutil does not zip data that is too large (>800mb).
Tested with 2.5 gigs of data inserted in the local database table, then exported with `dallinger export`

Fixing file compression error when data is too large

---

dallinger/data.py
tests/test_data.py

Do not backup when local==True. Allows us to test `dallinger.data.export`

Do not backup to S3 when running with local=True

---

dallinger/data.py
tests/test_data.py

Currently you can not load a file created with `export()` with the `Data` class, because the zipped folder structures differ.
Structure expected by `Data`:
```
12eee6c6-f37f-4963-b684-da585acd77f1-data
├── 12eee6c6-f37f-4963-b684-da585acd77f1-code.zip
├── data
│   ├── info.csv
│   ├── network.csv
│   ├── node.csv
│   ├── notification.csv
│   ├── participant.csv
│   ├── question.csv
│   ├── questiontransformation.csv
│   ├── transformation.csv
│   ├── transmission.csv
│   └── vector.csv
├── experiment_id.md
└── server_logs.md
1 directory, 13 files
```
Structure created by `export`:
```
data
└── test_export
├── data
│   ├── info.csv
│   ├── network.csv
│   ├── node.csv
│   ├── notification.csv
│   ├── participant.csv
│   ├── question.csv
│   ├── transformation.csv
│   ├── transmission.csv
│ …
```

WIP: Compatibility between export .zip format and format expected by Data class

---

dallinger/command_line.py
dallinger/experiment.py
tests/test_api.py
tests/test_command_line.py

Provide an API method (`Experiment.make_uuid`) and commandline (`dallinger uuid`) to generate a new uuid for an experiment.
This change is motivated by [ScrumDo Story 214](https://app.scrumdo.com/projects/story_permalink/1192298) which is in turn motivated by [ScrumDo Story 213](https://app.scrumdo.com/projects/story_permalink/1192296)
This has been tested by running the new `dallinger` command and the python API call. Additionally, new unit tests are included in this branch.

Implement story 214, uuid generation method/commandline.

---

dallinger/__init__.py
dallinger/config.py
dallinger/data.py
dallinger/experiment.py
tests/test_api.py
tests/test_data.py

Implements an `Experiment.retrieve()` method, which requires an experiment id, and accepts the configuration paramters that `run()` accepts. It will check to see if there is already data for the provided id, otherwise it will test if an experiment with that UUID has already completed and registered results, in which case it will fail with a `RuntimeError`, otherwise if the UUID is unknown it will run the experiment with the provided parameters and the specified id. This implementation includes a registry for experiment ids in a new `dallinger-registrations` bucket, all experiments runs that export data will also register their UUID in this bucket so it can be checked by the `retrieve()` method.
This is the implementation of story 213, whose goal is to allow full repeatability of …

Implement story 213, API method to retrieve data or run experiment.

---

tests/test_mturk.py

Remove test is now completely redundant. It's worth removing, because it's not adding anything and it's very slow.

Remove redundant test

---

dallinger/data.py

```
/Users/monica/.virtualenvs/dallinger/lib/python2.7/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
@convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
```

Suppress pd future warning from odo

---

dallinger/experiment.py
tests/test_experiment_server.py

It was not possible to run the `test_experiment_server` tests either as a module, or by selecting individual tests from the module, due to cross-test side effects and poor cleanup.
Tests!

Clean up test module so it can run by itself

---

Vagrantfile
dallinger/config.py
dallinger/default_configs/local_config_defaults.txt
dallinger/experiment_server/gunicorn.py
dallinger/heroku/tools.py
dallinger/recruiters.py
dallinger/utils.py
tests/test_heroku.py

Addresses issue #626 
When `heroku local` (I _think_ it's `heroku local`), starts, it sets an environment variable 'PORT' to whatever port the process's web worker is running on. This value is read by `load_from_environment()` when the process's `Configuration` object is initialized, and, prior to this fix, from that point on this value was treated as the base port by subsequent calls to `dallinger.utils.get_base_url()`, resulting in a miscalculation when defining a list of available ports. In order to preserve the original port number as the basis for calculating the port range, this PR introduces a new config variable `base_port`, which will not be overridden by heroku's writing to `os.environ`.
For now I left the old 'port/PORT' config value in place, and …

Avoid key collision on os.environ['PORT']

---

dallinger/experiment_server/sockets.py

The ChatBackend.send method is given a UTF-8 encoded string, not a unicode string. Decode to utf-8 so the socket implementation can correctly encode this for transmission to the user.
This allows non-latin content to be sent as part of chat messages, which otherwise would trigger a server error and a dropped transmission.
Manually, using the GridUniverse experiment and samples of non-latin and latin text.

Fix encoding bug in ChatBackend

---

dallinger/command_line.py
tests/test_command_line.py

More flexible version of `dallinger qualify` CLI command
Based on the work I did with @mongates on #662, this PR enhances the `dallinger qualify` command in several ways:
1. Supports the option to notify workers via a `--notify` option, whereas previously workers were always notified
2. Supports qualifying more than one worker at a time
3. Supports specifying a qualification name rather than an ID with the `--by_name` option
Now that we support blacklisting MTurk workers based on qualifications, a more flexible tool will be useful.

Features/662 better 'dallinger qualify'

---

dallinger/config.py
dallinger/experiment.py
tests/test_config.py

Provide a softer reset of config between experiment runs.
Fixes issue where the config reset between experiment runs using the API caused errors when reloading the config.
Includes an automated test to replicate the duplicate run issue.

Fix error when running experiment multiple time from API

---

.gitignore
dallinger/command_line.py
dallinger/config.py
dallinger/experiment_server/experiment_server.py
tox.ini

This adds Sentry as a Heroku add on and makes the resultant DSN, stored in an environment variable, available to templates via injection in the template context.
This should be evaluated in combination with `sentry` branch of Griduniverse.

Add Sentry integration via Heroku addons

---

dallinger/experiment_server/sockets.py
tests/test_sockets.py

Some contexts don't work well with any delay in message delivery (Griduniverse player movement, for example).
See https://github.com/Dallinger/Griduniverse/pull/107
I'm hesitant to remove the `gevent.sleep()` call altogether, since the concept will then be lost and I don't fully understand the implications. The original idea came from the example code in this tutorial: https://devcenter.heroku.com/articles/python-websockets
Automated tests, and manual testing with Griduniverse game

Allow clients to configure lag in redis message delivery

---

docs/source/developing_dallinger_setup_guide.rst
docs/source/running_the_tests.rst

Add installation of the demos sub-package to development setup documentation.
Addresses #699

Document installing the `dlgr.demos` subpackage

---

dallinger/command_line.py

Before this change, experiment launching breaks if the `sentry` config variable isn't provided.

Fix behavior when Sentry config missing

---

.travis.yml
dallinger/db.py
docs/source/developing_dallinger_setup_guide.rst

Use a database user with a password as default to have same settings in Linux and OsX.
Issue 492.

use postgres defaults that work both on Linux and OsX

---

dallinger/models.py
tests/test_models.py

I was not able to reproduce the problem described in the issue, but presumably, when the receive method is called in models.py, the transmissions query returned them in a different order than their creation time implied, so sorting by creation time should prevent this issue in the future.
Try to fix issue 274.

make sure transmissions are always returned sorted by creation time

---

dallinger/data.py

After re-creating my dallinger database following the instructions in the Developer Setup Guide, I ran into test failures in `test_data.py` due to the user specified for the DB connection. An example:
```
local_db = 'dallinger', path = '/var/folders/pv/yvkdh0vx195bcssnd2pc3cn40000gp/T/tmphMwr24', scrub_pii = True
def copy_local_to_csv(local_db, path, scrub_pii=False):
"""Copy a local database to a set of CSV files."""
if "postgresql://" in local_db:
conn = psycopg2.connect(dsn=local_db)
else:
conn = psycopg2.connect(database=local_db, user="postgres")
cur = conn.cursor()
for table in table_names:
csv_path = os.path.join(path, "{}.csv".format(table))
with open(csv_path, "w") as f:
sql = "COPY {} TO STDOUT WITH CSV HEADER".format(table)
>               cur.copy_expert(sql, f)
E …
```

Fix database user to match documented setup instructions

---

tests/conftest.py
tests/test_command_line.py
tox.ini

Speeds up tests which run `heroku local` by about 25 seconds each, by avoiding a full heroku CLI download and installation on each run.
I checked the "CI" environment variable on a few different CI servers (including AppVeyor) and it seems to be generally supported.
I have yet to figure out how to share a heroku cli installation across tests on Travis.

Don't use a fake HOME dir unless we're on Travis

---

Dangerfile
dallinger/mturk.py
dallinger/recruiters.py
docs/source/running_the_tests.rst
tests/conftest.py
tests/test_mturk.py
tests/test_recruiters.py

We currently have a large suite of tests which run against the live MTurk service. These tests provide a lot of confidence, but they are not only slow, but also non-deterministic, since occasionally the service is unavailable. The more calls we make, the more likely to hit non-responsive moment and see a spurious test failure. 
There is also a large degree of redundancy between tests, because so many of the same preconditions exist across different tests. This can cause a single regression to trigger failures in a large number of tests, making debugging difficult.
This PR:
- completes, as much as possible, isolation tests for the MTurkService class
- adds one new full-system test which hits 75% of the MTurkService class code
- configures the comprehensive integration tests so they are …

More sustainable MTurk testing

---

dallinger/command_line.py
tests/test_command_line.py

When debugging an experiment which uses the webpack BrowserSyncPlugin, it's really nice to avoid manually updating the port on multiple browser windows.

Provide option for opening browser windows with alternate port

---

dallinger/experiment.py
dallinger/networks.py
dallinger/recruiters.py
demos/dlgr/demos/bartlett1932/config.txt
demos/dlgr/demos/bartlett1932/experiment.py
demos/dlgr/demos/iterated_drawing/templates/questionnaire.html
demos/dlgr/demos/mcmcp/experiment.py
demos/dlgr/demos/mcmcp/templates/consent.html
demos/dlgr/demos/mcmcp/templates/exp.html
demos/dlgr/demos/mcmcp/templates/instructions/instruct-ready.html
tests/test_networks.py
tests/test_recruiters.py

This creates a recruiter that can get more than 10 participants on mechanical turk, and a chain implementation that handles the initial glut of participants. It also adds a bot for MCMCP to assist with testing this.
Mechanical turk's pricing increases if you need more than 10 assignments, so if your initial recruitment size is less than 10 it will fail on extending past that limit. This pre-allocates 10 participants and introduces a chain and a recruiter type to make it compatible with experiments without them needing to specifically code for the mturk limitations.
Unit tests only, at this stage.

Allow more than 10 assignments on Mechanical Turk

---

requirements.txt

The tablib library shouldn't be installed by default because it's an optional dependency. This is a fix for #728.

Remove optional dependency

---

dallinger/experiment.py
tests/test_api.py

The default behavior of `uuid.uuid4()` uses random bits generated by the OS and is thus unresponsive to seeding the random number generator. Here, we generate the UUID using 128 pseudorandom bits. This helps with computational reproducibility — it'll use the OS source of randomness, unless the PRNG is seeded.

Use random bits to form UUID

---

.gitignore

.gitignore pattern for ignoring snapshots no longer working since the layout move to use the /dlgr/ directory. This pattern matches more aggressively, and covers the tests/experiment snapshot directory also.

Ignore snapshots everywhere

---

dallinger/__init__.py
dallinger/command_line.py
dallinger/heroku/tools.py
dallinger/patches.py
dallinger/utils.py
tests/test_command_line.py
tests/test_heroku.py
tests/test_utils.py

This adds a patch for ipython's IO streams and wraps subprocess calls to make them more tolerant of the fact that jupyter does not allocate file descriptors for its streams. This allows experiments to be run through jupyter, albeit with the caveat that output is significantly laggier than using a console script.
This allows the full range of functionality to be used in a Jupyter notebook, lowering the bar to entry.
Manual tests of bartlett1932/demo.ipynb only.

Better jupyter support

---

setup.py

`master` and related branches are broken since new release of `networkx` package on 9/20/2017.
https://pypi.python.org/pypi/networkx/
```
dallinger/data.py:418: in df
return odo.odo(self.odo_resource, pd.DataFrame)
.tox/py27/lib/python2.7/site-packages/odo/odo.py:91: in odo
return into(target, source, **kwargs)
.tox/py27/lib/python2.7/site-packages/multipledispatch/dispatcher.py:164: in __call__
return func(*args, **kwargs)
.tox/py27/lib/python2.7/site-packages/odo/into.py:43: in wrapped
return f(*args, **kwargs)
.tox/py27/lib/python2.7/site-packages/odo/into.py:53: in into_type
return convert(a, b, dshape=dshape, **kwargs)
.tox/py27/lib/python2.7/site-packages/odo/core.py:44: in __call__
return _transform(self.graph, *args, **kwargs)
.tox/py27/lib/python2.7/site-packages/odo/core.py:57: …
```

Pin networkx version, since odo doesn't

---

dallinger/heroku/tools.py
tests/test_heroku.py

Fix for #750 
Currently, running `sandbox` or `deploy` in verbose mode echos sensitive keys to the terminal. This PR suppresses this output.
Bug report #750 
Automated tests and test with the Bartlett1932 experiment
Before (problem):
```
Setting whimsical and restarting ⬢ dlgr-2428dd53... done, v5
whimsical: True
Setting aws_region and restarting ⬢ dlgr-2428dd53... done, v6
aws_region: us-east-1
Setting auto_recruit and restarting ⬢ dlgr-2428dd53... done, v8
auto_recruit: True
Setting aws_secret_access_key and restarting ⬢ dlgr-2428dd53... done, v9
aws_secret_access_key: [redacted]
Setting dallinger_email_key and restarting ⬢ dlgr-2428dd53... done, v10
dallinger_email_key: '???'
Setting aws_access_key_id and restarting ⬢ dlgr-2428dd53... done, v11
aws_access_key_id: [redacted]
```
After …

Send subprocess output do dev/null when setting sensitive keys

---

dallinger/experiment.py

Fixes call signature for `debug` call within `experiment.run()`. This resolves an issue with GU test failures.

Fix debug API call signature.

---

tox.ini

`flake8` version needs to be explicitly pinned in tox.ini, otherwise the newest available version is used.

Pin flake8 version in for tox

---

dallinger/mturk.py
tests/test_mturk.py

MTurk now has a short delay between the time a HIT is created and when it can be extended. This PR updates the tests to account for this. Once on master this should be cherry-picked or rebased into development.

Fix test failure caused by MTurk service behavior change

---

dallinger/experiment_server/experiment_server.py
dallinger/recruiters.py
tests/test_recruiters.py

Move forward a bit more on recruiter separation of concerns:
* experiment_server delegates to recruiter to know what kind of worker submission event to process
* running the MTurkRecruiter in debug mode isn't actually possible, so fail early if that's somehow attempted, and clean up code which later checked for that condition

Missed a spot when working on recruiter design earlier

---

dallinger/bots.py

Griduniverse bot test fails due to new updates to the questionnaire requiring all questions to be filled out before submission. Changing the base bot class in order for this to work.
Tested with `python demo.py`

Change questionnaire bot

---

dallinger/experiment_server/experiment_server.py
tests/conftest.py
tests/test_experiment_server.py

Loading the config on import was problematic for testing, so this was changed to happen at runtime. However, there were cases where the config was not loaded before use when running on heroku. This PR adds a decorator for functions which act as entry/start-up points to the application, to ensure that the configuration is already reliably loaded for internal code.
Provide an obvious, concise way to load configuration at runtime, and in the appropriate layer.
1. Automated test
2. `dallinger sandbox` using Griduniverse
This seems like it might be complimentary to our upcoming effort to standardize database transaction boundaries, which should probably happen at the same points.

Ensure config is loaded on route entry

---

docs/source/configuration.rst

I made a new PR because the tests were failing due to permission errors on @pkrafft's forked PR #797

Corrected error in configuration.rst: 'group' variable -> 'group_name' (2)

---

dallinger/command_line.py
tests/test_command_line.py

This adds a test for another use of that function that
although still being ordering dependent will fix the partial coverage
of `dallinger.command_line.notify()` function in all cases.
The `notify()` method of command_line.py is partially covered depending
on dictionary ordering, which causes spurious -0.19% test coverage deltas
in some builds. 
This is primarily to unblock spurious warnings on pyupbot PRs.
codecov on this PR

Improvements for repeatable test coverage

---

dallinger/command_line.py
dallinger/heroku/messages.py
tests/test_command_line.py
tests/test_heroku.py

Email experimenters after app is left running for 6+ hours.
Heroku applications are often left running by experimenters without them knowing. This is costly. Experimenters should be notified if there app is left running for a certain amount of time.
Tested using my email credentials in the config, entering the following keys:
`dallinger_email_address`, `contact_email_on_error`, `dallinger_email_password`

Idle Heroku application email

---

dallinger/utils.py
tests/test_command_line.py

Restore verbose Git output from sandbox and production deployment.
Errors which occur during experiment startup (debug, sandbox, or production deployment) can be very mysterious and hard to debug unless printed error information is specific and related to the actual problem.
A previous change improved error handling of Git commands by capturing the error output and including it in an exception message during deployment. However, a side-effect of this change was to suppress the vast amount of standard output from this command, leading to confusion about whether the command was actually processing, or hung.
This PR attempts to restore the output stream while retaining the improved exception handling.
* ran `dallinger sandbox --verbose` with Griduniverse, and verified the …

Echo git output from Heroku in verbose mode

---

dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/waiting.html
dallinger/mturk.py
dallinger/recruiters.py
tests/test_recruiters.py

Updates `waiting_count` to include participants assigned to nodes to prevent quorum count from resetting. We may eventually need to adjust this to handle multiple waiting rooms for multiple networks. Implements a handler to complete the HIT for users exceeding quorum count.
Fixes the issue described in [story 255](https://app.scrumdo.com/projects/story_permalink/1337425).
Tested manually with GridUniverse [see branch](https://github.com/Dallinger/Griduniverse/tree/stories/259-waiting-room-fix).

Story 259 - Waiting Room Fix

---

dallinger/bots.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/static/scripts/dallinger2.js
dallinger/models.py
tests/test_experiment_server.py
tests/test_models.py

Created a new PR for story 47, because #715 was broken.
Description
Previously, worker_id and unique_id for any participant were visible in the public participant view. This PR removes that information from the view, while making sure other views that used that information continue to work as before.
Motivation and Context
Story 47.

Redo pr 715

---

dallinger/bots.py

Small bug fix in bots.py
Make `participant_id` an attribute. 
`participant_id` isn't being saved to the Bots object, so there's errors on looping bot.
Using interactive evolutionary algo on GU

Fix participant_id bug

---

dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/waiting.html

Fix small waiting room bug. Current behavior leaves over-recruited participants stuck in the waiting room. This fix attempts to make the intended behavior redirect over-recruited participants to the end of the experiment.
Tested with Griduniverse waiting room in debug mode.

Fix waiting room bug

---

dallinger/command_line.py
dallinger/heroku/tools.py
tests/test_command_line.py
tests/test_heroku.py

Bugfix: Allow `dallinger hibernate` to work when app's `clock_on` setting is `false`
`dallinger hibernate` raised an exception when trying to scale down a non-existent `clock` process if this process was not enabled in the experiment config. This PR updates the scaling down of dyno procedure to first check if the clock process is running.
* Ran Bartlett experiment with `clock_on = false`, and successfully hibernated experiment:
```
dallinger hibernate --app fbf4efbd-4f68-0e9a-26f3-31884d40e534
❯❯ The database backup URL is...
❯❯ https://dallinger-f6dff828.s3.amazonaws.com/fbf4efbd-4f68-0e9a-26f3-31884d40e534.dump
❯❯ Scaling down the web servers...
Scaling dynos... done, now running web at 0:Standard-2X
Scaling dynos... done, now running worker at 0:Standard-2X
❯❯ …
```

Bugfix for #840 (hibernate when clock is off)

---

dallinger/recruiters.py
tests/test_recruiters.py

More specific error message when invoking the MTurkRecruiter with an invalid mode setting. See Dallinger/Griduniverse/pull/159.

Improve error message on invalid recruitment mode

---

dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js

See issue #827. Participants in deploy mode with null fingerprints are getting marked as the same fingerprint.

Fix fingerprint in deploy mode

---

dallinger/frontend/static/scripts/dallinger2.js

Bugfix: createParticipant() was not exported and available to client experiment code.
`Uncaught TypeError: dallinger.createParticipant is not a function`
Run experiment previously failing

Include createParticipant in exported dallinger module object

---

dallinger/experiment.py

Small bug in string formatting leaves `experiment_completed()` in an endless loop when running the high level api in debug mode.
See GU PR [#159](https://github.com/Dallinger/Griduniverse/pull/159)

Fix format error in experiment_completed()

---

dallinger/experiment.py

Similar to #863. Fix all bugs that prevent high level api automation of experiments
The high level api is unable to work in sandbox/live mode because the experiment gets destroyed after it is finished. Is there a reason this line is in the code or is it a bug?

Prevent experiment destroy function

---

.travis.yml
dallinger/config.py
dallinger/data.py
dallinger/db.py
dallinger/experiment.py
tests/test_replay_state.py

This is story 294. It is part of the wider group of stories to enable better jupyter interaction with experiment data. This story allows the user to instantiate an experiment and provide it with data from a previous run, scrubbing forwards so the experiment is effectively paused at various points in the previous run.
Until now, it's only been possible to replay an experiment in real-time, interacting with it as the replay runs through the web server, or to load the full set of data wholesale and introspect it manually. This provides a generic framework to get the data an experiment had at a given time and progress through it at your own pace.
Basic unit tests, included in the commit
Manual testing with GridUniverse where the _state event was introspected

Replay server state

---

dallinger/command_line.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/error-complete.html
dallinger/frontend/templates/error.html
dallinger/heroku/messages.py
tests/conftest.py
tests/experiment/templates/error-complete.html
tests/test_command_line.py
tests/test_experiment_server.py
tests/test_heroku.py

This pull request implements [ScrumDo Story 291](https://app.scrumdo.com/projects/story_permalink/1459239).
This PR implements a new error handler for failed AJAX requests. It makes some modifications to the default error page to include a response form, with hidden fields containing all available information about the failed request. It also implements a new route to handle the error form post which attempts to complete the HIT, and adds a `Notification` to the database associated with the `assignment_id` that includes all available information about the error, including the user feedback. Additionally, it sends an email to the experimenter notifying them of the error so that they can verify completion, etc.
See This pull request implements [ScrumDo Story …

Story #291: Better Error Handling

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
dallinger/recruiters.py
tests/test_experiment_server.py
tests/test_recruiters.py

If an experiment is overrecruiting then the experiment qualification
should only be given to users who are actually shown the experiment.
If someone joins then is discarded by the waiting room they should
be unqualified. Assigning then removing the qualification causes
spurious emails to be generated by MTurk, so we change the way
overrecruitment is defined to be a python function rather than
comparing two elements of a JSON value in Javascript.
This lets
us assign the qualification in Python code and makes for a slightly
more standardised override story for experimenters.
Incorrect qualifications were assigned during overrecruitment.

Move experiment qualification to after waiting room

---

.travis.yml

We agreed to remove the test server from continuously uploading versions of Dallinger to Pypi since this is not useful in a majority of cases. Should we need the test server to be uploaded to during testing, we will create a story in the future that may integrate inserting hashes to the version number to prevent duplicates from being uploaded.

Remove test pypi upload

---

dallinger/experiment.py
tests/test_networks.py

Fix `retrieve_data` to be called after the loop ends but before the experiment is destroyed... See: 
https://github.com/Dallinger/Dallinger/pull/866/files
The high level api is unable to work in sandbox/live mode because the experiment gets destroyed after it is finished. Is there a reason this line is in the code or is it a bug?

Refactor and fix retrieve_data bug

---

dallinger/experiment_server/experiment_server.py
tests/test_experiment_server.py

Log unsupported event notifications (HITReviewable, for example), rather than raising exceptions.
Currently unsupported event notifications can result in confusing tracebacks:
```
Mar 08 16:45:04 dlgr-b02f3c0e app/worker.1:  >>>> ----- Received an HITReviewable notification for assignment None, participant None 
Mar 08 16:45:04 dlgr-b02f3c0e app/worker.1:  00:45:04 ValueError: Error: worker_function needs either an assignment_id or a participant_id, they cannot both be None 
Mar 08 16:45:04 dlgr-b02f3c0e app/worker.1:  Traceback (most recent call last): 
Mar 08 16:45:04 dlgr-b02f3c0e app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 789, in perform_job 
Mar 08 16:45:04 dlgr-b02f3c0e app/worker.1:      rv = job.perform() 
Mar 08 16:45:04 …
```

Log and ignore unsupported event types to avoid confusing tracebacks

---

dev-requirements.txt

We use bumpversion to increment version numbers thoughout the codebase when cutting new releases. It should be included in dev-requirements.txt

Include bumpversion in dev dependencies

---

.gitignore

Pycharm stores project settings in an .idea directory. It should not be tracked by version control.

Exclude Pycharm's .idea directory from repo

---

dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/static/scripts/dallinger2.js

This adds code to both dallinger.js and dallinger2.js to show an alert if the other library was also loaded.
dallinger2.js is meant to replace dallinger.js, not be used alongside. This intends to make that clearer to experiment authors.
Has not been tested yet.

Show an alert if dallinger.js and dallinger2.js are loaded together

---

dallinger/frontend/static/scripts/dallinger.js
dallinger/frontend/static/scripts/dallinger2.js
docs/source/developing_dallinger_setup_guide.rst

It turns out that the check I added to make sure that both dallinger.js and dallinger2.js are not loaded does not work but throws a ReferenceError. This fixes it. I'm going to go ahead and merge this since it's blocking other work on Griduniverse.
Tested by running Griduniverse in debug mode.

Fix check for loading both versions of dallinger script

---

dallinger/db.py
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/recruiters.py
tests/experiment/dallinger_experiment.py
tests/test_experiment_server.py

This branch implements Scrumdo stories [315](https://app.scrumdo.com/projects/story_permalink/1535307) and [323](https://app.scrumdo.com/projects/story_permalink/1536451). It creates a new customizable `is_complete` method on the `Experiment` class to provide custom logic for determining when an experiment has finished. It also re-enables recruiter notification methods and fixes error handling issues and provides more comprehensive exception handling.
This PR attempts to resolve the issues described in the ScrumDo stories above related to over-recruitment and email errors.
I tested these changes manually using GridUniverse with new parameters enabled for over-recruiting and a custom `is_complete` method. Scenarios were tested where the over-recruited users started the experiment before …

WIP: Over-recruitment and error email fixes

---

dallinger/experiment.py

This simply calls replay_start and replay_finish methods on the experiment when replaying state. It's needed for story 295 so that Griduniverse has a chance to initialize the Gridworld *after* the configuration has been loaded.
There's a new test that fails without this in the Griduniverse branch with the same name.

Give experiment a chance to initialize/finish around replaying state

---

dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/base/layout.html

Detects if an Ad blocker is enabled. If an ad blocker is detected on the ad page, the button is disabled and an alert is opened indicating that ad blockers must be disabled. If a previously undetected extension has blocked loading of Fingerprint2.js, that condition will be detected before attempting to create a new participant, and an alert shown.
See [ScrumDo Story 322](https://app.scrumdo.com/projects/story_permalink/1536427). When ad blockers were enabled, Fingerprint2.js would not be loaded and `dallinger.createParticipant()` would fail. Now an ad blocker should be detected before the HIT is accepted, and a missing Fingerprint2.js should trigger an alert rather than an error.
This code was tested to ensure it detects `AdBlock` and `uBlock Origin` when enabled and works when those …

Ad blocker detection and detection for missing Fingerprint2.js

---

dallinger/command_line.py
dallinger/mturk.py
dallinger/recruiters.py
tests/test_command_line.py
tests/test_recruiters.py

Implements [ScrumDo Story 321](https://app.scrumdo.com/projects/dallinger/#/iteration/286266/board/story/1536415). Adds two new `dallinger` commands `hits` and `expire` to list HITs associated with an experiment id and expire those HITs respectively. Addtionally, adds an option to the `dallinger destroy` command to expire HITs associated with the experiment id being destroyed. These commands require a `--sandbox` flag to be passed for cases where the experiment was run in the MTurk sandbox.
See story description. Currently a fair amount of work is required to find and expire HITs associated with an experiment, these changes simplify and automate that process. In order to explicitly associate a HIT with an experiment id, the MTurk recruiters add a `RequestAnnotation` to all created HITs …

HIT Manipulation Commands

---

dallinger/command_line.py
dallinger/config.py
docs/source/configuration.rst
tests/conftest.py
tests/test_command_line.py

Adds a `redis_size` configuration parameter that defaults to `premium-0` (the current default). Creating or waking an experiment on Heroku will use the `redis_size` to configure the redis addon.
See [ScrumDo Story 333](https://app.scrumdo.com/projects/story_permalink/1574090)
Updated automated tests for use of new config variable

Story 333 configurable redis sizing

---

.codecov.yml
.coveragerc
dallinger/heroku/rq_gevent_worker.py
dallinger/heroku/worker.py
setup.py

This includes a copy of `rq_gevent_worker` because we need some fixes from https://github.com/reallistic/rq-gevent-worker/ that are not released.
It also switches to always use the gevent-based worker because it seems to be working okay and it seems like an unnecessary choice to give the experimenter.

Use vendored rq_gevent_worker

---

dallinger/command_line.py
requirements.txt

This avoids showing some distracting warnings when running dallinger on the command line.

Fix warnings about psycopg2 and unicode_literals

---

.eslintrc
dallinger/command_line.py
dallinger/config.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/worker_events.py
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/base/ad.html
dallinger/models.py
dallinger/recruiters.py
demos/dlgr/demos/bartlett1932/static/scripts/experiment.js
demos/dlgr/demos/chatroom/static/scripts/experiment.js
demos/dlgr/demos/concentration/static/scripts/experiment.js
demos/dlgr/demos/function_learning/templates/ad.html
demos/dlgr/demos/iterated_drawing/templates/ad.html
demos/dlgr/demos/rogers/tests/tests.py
demos/dlgr/demos/snake/static/scripts/experiment.js
docs/source/index.rst
docs/source/running_bots.rst
docs/source/writing_bots.rst
tests/conftest.py
tests/experiment/templates/ad.html
tests/test_db.py
tests/test_experiment_server.py
tests/test_heroku.py
tests/test_models.py
tests/test_recruiters.py

https://app.scrumdo.com/projects/dallinger/#/iteration/286266/board/story/1559966
This adds a new recruiter, the MultiRecruiter, which can delegate to multiple other recruiters.
The MultiRecruiter is used if `recruiter = multi` is specified in config. It looks for a recruiter spec like this: `recruiters = bots: 4, cli: 1` and will recruit that many times from those recruiters in sequence.
Implementing this required some noteworthy changes:
1. Ad URLs generated from recruiters now include a `recruiter` param and the participant table now has a `recruiter_id` column so we can keep track of which recruiter a participant came from. (Note that if there *isn't* a recruiter in the URL because a particular experiment hasn't been updated to pass it from the ad page onward, we fall back to using …

Story 328: Mixed recruiters

---

.gitignore

- Update `.gitignore` to exclude `.pytest_cache` and `.vscode` directories from source control
- Add two `__init__.py` files required by python2 (but not python3) to source control
Quite noise from `git status`

Git status cleanup

---

dallinger/command_line.py
dallinger/experiment.py
tests/test_experiment.py

Changes `Experiment.make_uuid` to take an optional `app_id` parameter and if that parameter is a valid UUID, then it returns that instead of generating a new one. Existing code using `make_uuid` passes in the `app_id` when available.
See [ScrumDo Story 319](https://app.scrumdo.com/projects/story_permalink/1536379)
Manual testing. Existing tests should cover all code changes.

Story 319: don't generate a new UUID if we were passed in a valid one

---

dallinger/command_line.py
dallinger/config.py
dallinger/default_configs/local_config_defaults.txt
dallinger/recruiters.py
docs/source/command_line_utility.rst
docs/source/configuration.rst
tests/conftest.py
tests/test_command_line.py
tests/test_recruiters.py

This PR adds a new configuration variable, `assign_qualifications`, to control whether recruiters that support participant qualifications assign qualifications for the experiment ID and any configured `group_name` when participants are recruited. 
When testing experiments with participant collaborators, it is undesirable to assign qualifications which make it difficult for the same people to participant in the same experiment several times in a row. A configuration variable makes it easy to toggle qualification assignment on and off.
- automated tests
- `dallinger sandbox` on Bartlett1932 experiment with `assign_qualifications` set to `false`

Story 331: Add configuration for recruitee qualification and add 'dallinger revoke' command

---

dallinger/command_line.py
tests/test_command_line.py
tests/test_mturk.py

Bug fix. Click commands always pass strings, and boto3.mturk code needs ints for qualification scores.
Bug reported by @mongates. Command failing was a valid one:
`dallinger qualify --qualification "squaresexpt" --value 1 --by_name --sandbox [WORKER ID REDACTED]`
- Ran `dallinger qualify` successfully

Fix dallinger qualify to pass integers to mturk.set_qualification_score()

---

.travis.yml
dallinger/config.py
dallinger/experiment.py
dallinger/jupyter.py
tests/test_config.py
tests/test_replay.py

Extend the Jupyter widgets and replay stories to allow experiments to implement a method scrubbing back in time.
This allows experiments to support cleanly exploring data in a replay rather than just replaying forwards.
Minimal manual testing in a Jupyter notebook

Scrub back in replays

---

dallinger/experiment.py

This should be merged into master ASAP, as the prior changes from this branch cause a `ModuleNotFoundError` when running without the `jupyter` extra.

Fix widget related import error

---

dallinger/bots.py

`HighPerformanceBotBase` subclasses should use the waiting room just like browser-based bots and real participants.
Bug fix for #1004 
- Manual testing with RandomBots in debug mode on GridUniverse (see related PR https://github.com/Dallinger/Griduniverse/pull/182)
- Automated tests use AdvantageSeekingBot (also a HighPerformanceBot)

Story 338: High Performance Bots should use waiting room

---

dallinger/experiment.py

This PR implements tweaks to data loading and configuration to help enable multiple jupyter widgets in a single notebook and ensure data is retrieved from the notebook path rather than the original experiment module path.

Jupyter data loding fixes

---

dallinger/frontend/static/scripts/dallinger2.js
demos/dlgr/demos/bartlett1932/static/scripts/experiment.js

Leave it up to clients of methods which delegate to `dallinger.ajax()` to determine whether to show the /error-page on particular errors.
Most (all?) of the demo experiments use a 403 status error response to a `/node/[participant ID]` call (via dallinger2.js's `dallinger.createAgent()`) as cue to send the participant to the questionnaire. 
Our recent attempt to build in automatic error handing and presentation of the /error-page prevented this tactic from working on Chrome (it continued to work in FIrefox for reasons explained in #924).
Fixes #924 
Tested with Bartlett demo experiment.

Issue 924: dallinger.ajax() error handling changes

---

dallinger/data.py
tests/test_data.py

This PR provides a very simple (perhaps too simple?) fix for issues related to creating new local databases from pg:pull downloads. Instead of using Heroku's `pg:pull` to clone the database into a local one running a CSV export on that. It uses the Heroku app's `DATABASE_URL` to run the CSV export directly.
See [ScrumDo Story 344](https://app.scrumdo.com/projects/story_permalink/1596142) which describes issues that some users have related to using a local postgres as intermediate data store for exports.
I manually tested exports from a live Griduniverse sandbox experiment. The changes are fairly trivial and require no new automated tests for coverage, all current tests were passing locally.

Story 344: Fix Data Export Issues

---

dallinger/config.py
dallinger/experiment_server/gunicorn.py
docs/source/configuration.rst
tests/test_experiment_server.py

The PR implements a fix for the issues described in [ScrumDo Story 363](https://app.scrumdo.com/projects/story_permalink/1605684) and issue #1078. It reduces the default multiplier for 2 to 1.5 and makes it configurable via a `worker_multiplier` config parameter. Since more complex experiments may use significantly more RAM per worker than simpler ones, allowing this to be configured is probably the best route. The new default seems to be sensible for avoiding the RAM limits for most experiments without significantly underutilizing dyno resources.
See issue #1078
I manually tested starting sandbox GridUniverse experiments with varying multipliers. Higher multipliers resulted in RAM errors, the new lower default multiplier appears to eliminate RAM errors in my trial runs.

Configurable multiplier of gunicorn workers per CPU

---

dallinger/command_line.py
tests/test_command_line.py

Implements retrying `/launch` route with increasing delays (5, 10, 20, 40 seconds), to prevent experiments with slower launch times from failing catastrophically.
See [ScrumDo Story 362](https://app.scrumdo.com/projects/story_permalink/1605538) and issue #1082.
An existing automated test has been modified to verify that retries occur.

Retry Experiment Launch

---

dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
dev-requirements.txt
docs/source/conf.py
docs/source/contributing_to_dallinger.rst
docs/source/index.rst
docs/source/javascript_api.rst
package.json
tox.ini
yarn.lock

Add documentation for `dallinger` javascript API as defined in `dallinger2.js`
This PR uses JSDoc comment conventions integrated into the Sphinx documentation setup to
include API documentation for Dallinger's JS API.
Implements [ScrumDo Story 360](https://app.scrumdo.com/projects/story_permalink/1600086)
This may still need information about recommended JS build systems and such, if desired. We currently use `webpack` and `yarn` for both Dallinger and Griduniverse. Should we recommend those for custom experiments that wish to make use of external JS dependencies?

Add JS API docs using JSDoc and Sphinx-JS

---

dallinger/experiment.py
docs/source/classes.rst
docs/source/python_module.rst
docs/source/the_experiment_class.rst

Improve documentation for `dallinger` python API for running experiments.
This PR extends the python module documentation to provide information about running
experiments repeatably and registering experiments. It also makes some changes to
existing API documents to facilitate cross-linking API documentation.
Implements [ScrumDo Story 358](https://app.scrumdo.com/projects/story_permalink/1600084)
Ideally, one would test this by pulling down the branch, `cd docs; make html; open build/html/python_module.html` and reviewing the HTML output, along with the source changes.

Add documentation for python Experiment API

---

dallinger/command_line.py
dallinger/deployment.py
dallinger/experiment.py
tests/test_command_line.py
tests/test_deployment.py
tests/test_heroku.py

- Extracts code which performs deployments from `command_line` module to a new `deployments` module
- `dallinger.command_line` is an overly large module with a lot of churn (the most of any module in the codebase), and would benefit from being smaller
- "deployment" is a first-class concept in the dallinger universe, and is really distinct from the `dallinger [x]` CLI, which includes many non-deployment commands
- Bartlett and MemoryExpt2 in debug and sandbox modes
- Bartlett via the python API (`Bartlett1932().run()`)

Extract deployments from command_line

---

.pyup.yml
constraints.txt
requirements.txt

This seems to fix the syntax issue and should exclude `requirements.txt` and `dev-requirements.txt` from pyup updates while including `constraints.txt`.

Final (?) PyUp config updates

---

dallinger/command_line.py
dallinger/deployment.py
dallinger/heroku/tools.py
docs/source/command_line_utility.rst
requirements.txt
tests/conftest.py
tests/test_command_line.py
tests/test_deployment.py
tests/test_heroku.py

Implements a `dallinger apps` command to list all currently running experiment started by the current heroku user. Relies on setting heroku config variables with the current username and full dallinger experiment UID on experiment startup. As a result it will only work for experiments started using this updated code. This PR also includes documentation updates for to include this command as well as other undocumented commands.
This is an implementation of [ScrumDo story 387](https://app.scrumdo.com/projects/story_permalink/1645295). It make it easier for people to find and destroy long running apps.
This PR includes automated tests of all new methods and commands. In addition, I manually tested the command by starting sandbox apps and verifying that they were listed by the command.

App Listing Command

---

docs/source/developing_dallinger_setup_guide.rst

The commands in the Ubuntu section of **Set up a virtual environment** in the **Developing Dallinger Setup Guide** were inconsistent with other parts of the section.
http://docs.dallinger.io/en/latest/developing_dallinger_setup_guide.html
eg:
``` mkvirtualenv Dallinger --python /usr/bin/python3 ```
should be
``` mkvirtualenv dallinger --python /usr/bin/python3 ```
etc.

Fix typos in docs for consistency

---

dallinger/data.py
dallinger/experiment.py

This prevents leaked connetions, which would prevent future
calls that need to lock the whole database, such as dropdb
during Griduniverse's tests.
It is hoped that this will improve test reliability in Griduniverse, as they currently fail most of the time on Travis.
Using tox on Griduniverse with test order randomisation and a fixed seed that reliably triggers the same exception as on travis.

Close connections no longer being used

---

.travis.yml

Update the PyPI upload url and the deploy conditions to ensure pushing a git tag will cause one successful deploy to travis. It's important that tags be pushed as they are created, because a `git push --tags` with more than three tags will not trigger builds (see https://github.com/travis-ci/travis-ci/issues/9690).
See [ScrumDo Story #391](https://app.scrumdo.com/projects/story_permalink/1658253)
This change was cherry-picked into the v4.0.0 tag which was re-pushed to the origin. That successfully triggered a single deploy resulting in a [successful release](https://pypi.org/project/dallinger/4.0.0/).

Fix PyPI deploys from Travis

---

dallinger/deployment.py
dallinger/heroku/__init__.py
dallinger/heroku/tools.py
tests/test_deployment.py
tests/test_heroku.py

Raises a `RuntimeError` early in sandbox or deploy runs when dyno type `free` is combined with a heroku team. The new `heroku_config_sanity_check()` function can be extended to handle other known misconfigurations.
See [ScrumDo Story #393](https://app.scrumdo.com/projects/story_permalink/1658255). Ensures failure due to common misconfiguration happens quickly to avoid user frustration.
Branch includes new automated test.

Fail early on heroku misconfiguration

---

dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/worker_events.py
dallinger/models.py
dallinger/recruiters.py
tests/test_experiment_server.py
tests/test_recruiters.py

Prevent MTurk workers who are over-recruited for an experiment from receiving any configured qualifications. 
Addresses issue #1270 
* automated tests 
* testing in debug mode to verify succession of participant status values and overall flow
* **I could use help with sandbox testing**
(Difference in bold)
1. Participant created with status of `working`
2. proceeds from waiting room to experiment and completes experiment
3. Submits questionnaire, which triggers a call to `/worker_complete` route
4. **Recruiter receives `notify_completed()` message, and based on the Participant status being other than `overrecruited`, requests MTurk qualifications**
5. No `AssignmentSubmitted` event is immediately processed, because the `MTurkRecruiter` returns `None` from `submitted_event()`
6. Worker …

Story 389: Don't grant MTurk Qualifications to over-recruited participants

---

dallinger/command_line.py
docs/source/command_line_utility.rst
tests/test_command_line.py

Changes default for `destroy` command to automatically attempt to expire any HITs for the app.  Updates order of existing operations in `destroy` command to ensure HIT expiry happens before Heroku app destruction. Adds a `--no-expire-hit` flag to disable HIT expiry explicitly.
The implementation is for MTurk recruiters only. It is not aware of other recruiters. It is also not aware of which recruiter was used for the requested app id, it simply assumes MTurk for any request that wants to expire HITs.
Ideally the Recruiter class itself would manage expiring recruitment, but the command line isn't aware of recruiter configuration nor can it interact with a recruiter directly. Ideally, the command line would attempt to securely contact an experiment route that instruct the recruiter to …

Expire hits before destroying application

---

dallinger/heroku/tools.py
tests/test_heroku.py

Resolves https://github.com/Dallinger/Dallinger/issues/1317
The 'heroku_team' key is optional, so the config `sanity_check()` needs to deal with that.
Automated test

Don't raise when optional 'heroku_team' key is absent

---

docs/source/running_bots.rst

Fix typo in documentation. The nickname of the MultiRecruiter is `multi`, not `mixed`.

Fix typo in MultiRecruiter documentation

---

dallinger/recruiters.py

Make all recruiters log their class name on initialization, to make it easier to track which recruiters are in use when reviewing logs. This is particularly helpful when using the MultiRecruiter.
Only the BotRecruiter does this currently.
Confusion over recruiters encountered when helping experiment author. 
Change covered by current tests
```
11:18:44 AM web.2   |  >>>> ----- Launching experiment...
11:18:44 AM web.2   |  2018-08-31 11:18:44,824 Initializing HotAirRecruiter...
11:18:44 AM web.2   |  2018-08-31 11:18:44,824 Opening recruitment.
11:18:44 AM web.2   |  2018-08-31 11:18:44,824 New participant requested: http://0.0.0.0:5001/ad?recruiter=hotair&assignmentId=EEAM5W&hitId=L169T9&workerId=52DK2P&mode=debug
```

Log recruiter class on initialization

---

.readthedocs.yml

Adding this file allows RTD to set up the dependencies for the Javascript docs.
THe RTD build was broken.
Forked the project and generated a build with this file.

Add rtd configuration

---

dallinger/bots.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/templates/base/ad.html
dallinger/heroku/clock.py
dallinger/models.py
tests/test_bots.py
tests/test_experiment_server.py

Fix for issue #1367, which turns out to be specific to the `HighPerformanceBotBase`. Sets a recruiter during participant `sign_up` with the name `bots:BotClassName`.
The prior behavior didn't allow distinguishing `HighPerformanceBotBase` participants from humans when using the `MultiRecruiter`. This change will allow distinguishing bots from humans and bots of varying classes.
Added new automated tests for the `HighPerformanceBotBase` class. Ran `GridUniverse` experiments locally with and without bots.

Make HighPerformanceBots set recruiter explicitly

---

dallinger/db.py
dallinger/deployment.py
tests/test_deployment.py

Don't make assumptions about how postgres is running when testing connection in experiment setup.
When running inside a Docker container, the check of whether postgresql is running fails spuriously due to hard-coding connection parameters which don't work in Docker. This PR inverts the check from trying to raise an expected failure using bad credentials to simply using the configured `db_uri` from `dallinger.db` and attempting to make a successful connection, which is then immediately dropped if it succeeds. 
As an added benefit, the original psycopg2.OperationalError is re-raised to provide more detail than a generic RuntimeError.
* Manual testing with postgresql running and not, both "natively" (outside of Docker) and in a Docker container.

Story 345: Change postgres status check to be more context agnostic

---

dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/utils.py
tests/test_experiment_server.py

Fixes https://github.com/Dallinger/Dallinger/issues/1342
MTurk workers who are overrecruited should be shown the "thanks.html" page when then are returned to the /ad page, rather than the template for opting into an experiment run.
* MTurk sandbox tests

Story 396: overrecruited MTurk workers should be prompted to submit HIT

---

docs/source/dallinger_with_anaconda.rst
docs/source/demo_index.rst
docs/source/demoing_dallinger.rst
docs/source/demos_on_heroku.rst
docs/source/developing_dallinger_setup_guide.rst
docs/source/index.rst
docs/source/installing_dallinger_for_users.rst
docs/source/installing_python.rst
docs/source/troubleshooting.rst

Make a clear distinction between Users, Experimenters and Core Developers,
and modify a few documents to not give core dev instructions to users.
The documentation is unclear, leaving users of Dallinger setting themselves up as core developers, creating problems as they aren't on a stable release.
Built and checked the docs by hand

Better organise documentation for different users

---

dallinger/config.py

This marks the database uri as sensitive.
For some reason that I do not understand or support, the root of an experiment shows a huge amount of config data. This correctly excludes parameters marked as sensitive but there hasn't been an audit of which are actually sensitive.
I'd also recommend removing this feature.

Don't show database passwords to end users

---

.travis.yml

As of around 9/28/18, all Travis builds started failing with the following error:
```
Installing APT Packages
8.33s$ travis_apt_get_update
3.93s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install pandoc enchant heroku-toolbelt redis-server
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
heroku-toolbelt : Depends: heroku (= 3.99.4) but 7.16.0-1 is to be installed
E: Unable …
```

Fix Travis build by installing Heroku via Snap

---

dallinger/heroku/clock.py
tests/test_heroku.py

Encountered while investigating problems with @mongates's memoryexp2. 
The check for participants who have been working on an experiment for too long attempts to expire HITs, but sometimes the HIT has already been removed from MTurk, or never existed in the first place (no MTurkRecruiter is in use).
This timed check function now handles exceptions in the call the MTurkService and logs them, but continues processing so the worker's assignment can be resolved.
```
dlgr-e2a139c1	54.91.70.18	Local7	Info	app/clock.1	During handling of the above exception, another exception occurred: 
982119572721897478	2018-09-27T23:59:35	2018-09-27T23:59:35Z	2356746171	dlgr-e2a139c1	54.91.70.18	Local7	Info	app/clock.1	Traceback (most recent call last): 
982119572721897479	2018-09-27T23:59:35 …
```

Clock check: HIT does not exist

---

dallinger/bots.py
dallinger/db.py
dallinger/experiment_server/experiment_server.py
dallinger/heroku/worker.py

This is intended to replace #1385 as other things have been merged into there now.
This fixes a problem in serialising new participants that could cause high performance bots to get stuck in the waiting room. It also tidies some code around the questionnaire that was nonfunctional.
This is part of a series on making bots work better.
This has been tested locally, @mmosleh is testing to see if it fixes https://github.com/Dallinger/Griduniverse/issues/196

Improve reliability of bots

---

dallinger/deployment.py
dallinger/heroku/Procfile
dallinger/heroku/Procfile_no_clock
dallinger/heroku/launch.py
dallinger/heroku/runtime.txt
dallinger/heroku/worker.py
setup.py
tests/test_deployment.py

This PR implements new setuptools entrypoint scripts for the Heroku processes: `launch.py`, `worker.py`, and `clock.py`. These scripts are now installed along with the `dallinger` script as `dallinger_heroku_web`, `dallinger_heroku_worker`, and `dallinger_heroku_clock`. Instead of copying these scripts from the machine launching the experiment, the heroku dynos will run the scripts installed on the instance when Dallinger was installed. The `Procfile` and `runtime.txt` files are still copied from the machine starting the experiment, which should provide some additional flexibility in deployment while minimizing backwards compatibility issues. Additionally, this PR updates the default python runtime from 3.6.4 to 3.6.6.
This PR relates to [ScrumDo Story …

Provide Dallinger scripts for heroku processes

---

.travis.yml
tests/test_deployment.py

Changes Travis config to use different server `base_port` for the py27 and py36 builds, and fixes tests to not assume a specific base port.
During a couple test runs on my last PR I'd get errors randomly on one of the two builds indicating that port 5000 was already in use. This PR makes the two simultaneous test runs use different ports for the application server, avoiding the conflict.
Running the tests with `base_port` set differently.

Avoid Random Travis Errors By Running on Different Ports

---

docs/source/creating_an_experiment.rst
docs/source/developing_dallinger_setup_guide.rst
docs/source/docker_setup.rst
docs/source/installing_dallinger_for_users.rst

The Docker documentation has been updated to the docker-compose method. The older docker implementation has been removed. Mentions of the vagrant method have been removed from the installation instructions, although the vagrant_setup.rst is still present, just not linked into the main docs. The recommended method to run Dallinger is now either natively or via virtual machine, without specifying any VM specifics. Mentions of Windows have been prepended with ```Microsoft``` for consistency.
I have not been able to compile my docs locally due to a bad connection. I apologize if there are any compilation errors, although I hope there are none.

Update docker documentation for v5.0.0 release

---

docs/source/index.rst

This section has been removed the main index.

Unlink Required Experiment files section for v5 release

---

tests/conftest.py

Fixes tests which run `heroku local` to work with the new way of starting web and worker dynos via entry point commands.

Update process termination in tests to work with entry point commands

---

docs/source/demoing_dallinger.rst
docs/source/developing_dallinger_setup_guide.rst
docs/source/index.rst
docs/source/rewarding_participants.rst
docs/source/running_bots.rst
docs/source/troubleshooting.rst
docs/source/waiting_rooms.rst

The link to demos was removed from the main index. 
Only references to bartlett1932 were kept throughout the docs.
Added a link in the the **demoing Dallinger** section to the **running demos on Heroku** section, so that it exists somewhere for now. (Normally found in the demo index page).
References to chatroom and 2048 demos were removed from various sections. Besides bartlett which pops up frequently in our docs, chatroom was referenced twice and 2048 once.
I made a note: https://github.com/witekdev/dallinger_demos/blob/master/README.md and point to this PR so that we can know where to re-add those references once we make sure chatroom and 2048 are working properly. **Potentially these 2 demos should be prioritized for reinclusion in the docs?**
Additionally made a small fix to name of …

Remove demos from docs for v5 release

---

dallinger/mturk.py
dallinger_scripts/worker.py
tests/test_mturk.py

1. Moves creation of the redis connection for the heroku worker into the new `worker` script, and applies `gevent.monkey.patch_all()` beforehand
2. Improves performance of redis in conjunction with gevent in the context of the heroku worker process
3. Logs details of MTurk assignment when an ApproveAssignment request fails
Consistent timing problems in the worker process following the move of the worker, web, and and clock into entry_point scripts suggested a problem with the order and manner of gevent patching. This work was an somewhat of an experiment, but seems to have been successful.
Large-scale (120 participant) heroku/MTurk deployment run by @a-paxton.
This PR includes all the commits from https://github.com/Dallinger/Dallinger/pull/1491, and so supersedes it if merged first.

Optimize redis connection in worker

---

dallinger/frontend/static/scripts/dallinger2.js

Save identity data taken from the ad URL at experiment start.
Check for the js store, and if available save dlgr.identity data.
Currently, experiments require explicitly setting identity parameters in experiment js. This is usually done after consent. This is prone to errors and requires repeating the same lines of code in every experiment. This PR sets the store data right after taking it from the experiment URL. This allows users to focus on the experiment and not having to deal with required boilerplate that can crash their experiment if missing.
Tested in debug and sandbox modes.

store identity data from start

---

dallinger/mturk.py
tests/test_mturk.py

When `approve_assignment` calls fail on MTurk, query for current assignment state, so it can be included in our own error message.
Since we call MTurk to approve assignments based on messages from MTurk that the assignment has been submitted by the worker, it's a bit of mystery why MTurk then says they're in the wrong state when we attempt to approve them. More information may shed light on the matter.
- Large-scale (120 participant) heroku/MTurk deployment run by @a-paxton.

Log assignment status on failure

---

dallinger/recruiters.py
tests/test_agents.py
tests/test_recruiters.py

I thought I'd found a subtle bug in the MTurkLargeRecruiter, because the logic of the recruit() method was hard to follow. This PR just adds or clarifies some tests, and then refactors that method.
1. Clarity
2. Avoid depending on the real redis connection in these tests. We have other tests for the redis connection.
Full automated test coverage.

Add tests and refactor MTurkLargeRecruiter

---

constraints-deps.txt
constraints.txt

With rq version 0.12.0, this bug was found in Dallinger by @suchow :
```
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1: Traceback (most recent call last): 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 781, in perform_job 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:     self.prepare_job_execution(job) 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 706, in prepare_job_execution 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:     registry.add(job, timeout, pipeline=pipeline) 
Dec 13 07:55:17 dlgr-8372b4ee app/worker.1:   File …
```

Update rq to 0.13.0

---

CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/requirements.txt
demos/dlgr/demos/chatroom/requirements.txt
demos/dlgr/demos/concentration/requirements.txt
demos/dlgr/demos/function_learning/requirements.txt
demos/dlgr/demos/iterated_drawing/requirements.txt
demos/dlgr/demos/mcmcp/requirements.txt
demos/dlgr/demos/rogers/requirements.txt
demos/dlgr/demos/sheep_market/requirements.txt
demos/dlgr/demos/snake/requirements.txt
demos/dlgr/demos/twentyfortyeight/requirements.txt
demos/dlgr/demos/vox_populi/requirements.txt
setup.cfg
setup.py

- Documentation improvements and additions:
+ Update Creating an Experiment documentation to use dallinger.goToPage() standard
+ Reintroduce seven working demos into the documentation
- Legacy `dallinger.js` has been removed
- Fixed: AttributeError: 'int' object has no attribute 'items' (rq has been updated to 0.13.0 to fix this)
- Fixed: dallinger2.js: valid store values are overwritten with 'undefined'

Release version 5.0.2

---

dallinger/command_line.py
demos/dlgr/demos/bartlett1932/experiment.py
tests/test_command_line.py

Fail early with an explicit error message when running a command that requires being in a Dallinger experiment directory if you are not.
Currently if you run `debug`, `sandbox`, or `deploy` outside of an experiment directory, you get a very confusing traceback, and risk unpleasant accidental side-effects. This PR introduces a sanity check for these commands, so the problem is detected early and reported clearly.
```
$ dallinger debug --verbose
✗ config.txt is MISSING
✗ experiment.py is MISSING
Usage: dallinger debug [OPTIONS]
Error: The current directory is not a Dallinger experiment.
```
The changes also include a breaking down of the `verify_package()` function so that it delegates to smaller, single-purpose functions, so that the basic directory check can be run separately. This was …

Check valid experiment dir

---

.travis.yml
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/static/scripts/dallinger2.test.js
package.json

This enables the Jest JS testing framework and integrates it into CI.
I noticed that PR #1556 has no tests but makes lots of changes I don't understand. This made me nervous, but I couldn't fail the PR as there is no testing framework for JavaScript in Dallinger. To that end, I've added a basic one and a first test, in the hope that it will shame us into starting to test the JS library.
I wrote two basic tests and verified that they pass and are run by Travis.

Start monitoring JS code coverage

---

dallinger/deployment.py
tests/test_deployment.py

Change deployment script to add command line option for preventing chrome to ask to be default browser when running in debug mode.
It is annoying to have to click through this popup for every recruitment request in an experiment debug run.

Prevent chrome from showing default browser popup on debug runs

---

.travis.yml

Pin version of chandler gem used by `danger` on Travis CI
Our version of Ruby only supports versions of chandler <= 0.7.0
```
3.08s$ gem install danger
Successfully installed claide-1.0.2
Successfully installed nap-1.1.0
Successfully installed colored2-3.1.2
Successfully installed cork-0.3.0
Successfully installed open4-1.3.4
Successfully installed claide-plugins-0.9.2
Successfully installed git-1.5.0
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.4
Successfully installed faraday-http-cache-1.3.1
Successfully installed public_suffix-3.0.3
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.13.0
Successfully installed kramdown-1.17.0
Successfully installed unicode-display_width-1.4.1
Successfully …
```

Pin chandler ruby gem

---

docs/source/index.rst
docs/source/networks.rst

Network documentation is currently linked in the Creating an Experiment section. 
This PR additionally makes it easily visible and accessible from the main table of contents.
As an additional "win", the main headings of the network documentation show up in the side navigation

Include Networks documentation in the main table of contents

---

dallinger/config.py
dallinger/deployment.py
tests/test_deployment.py

This adds a special case to `new_webbrowser_profile` which attempts to cover the most common codepath on OSX, which was previously unsupported.
This is an attempt to fix the issue in #1361, which is that #816 doesn't work on Apple Macs.
This has not been tested. I don't have an apple device anymore. Could you take a look perhaps, @vlall?

Profiles on osx

---

docs/source/networks.rst

Following up on https://github.com/Dallinger/Dallinger/pull/1627
> I hadn't read through these before, so I did so, and made a couple small edits, unrelated to the question of linking them in the docs (the topic of this PR). One question I had (again, on the docs, not their linking) was whether references to source code values should be styled as literals, using double back-ticks, rather than italics (single back-ticks) as they are now.
@jessesnyder I have changed them to double back-ticks as the visibility is improved IMO. If somebody feels differently, please comment. Thanks!

Tweak styling of network docs

---

CHANGELOG.md

The indentation in the CHANGELOG for release 5.0.4 made it seem like all changes/updates were related to documentation. Fixed.

Fix indentation in CHANGELOG

---

docs/source/_static/custom.css
docs/source/conf.py
docs/source/dallinger_with_anaconda.rst
docs/source/demoing_dallinger.rst
docs/source/developing_dallinger_setup_guide.rst
docs/source/gsoc.rst
docs/source/installing_dallinger_for_users.rst

The user and developer installations have been reordered and the OS sections have been grouped logically together. The side menus now look much cleaner: :muscle: 
**User instructions**
**Developer instructions**
The instructions for using pip3 in certain cases have been made more explicit. Likewise the Demoing Dallinger section has been made more explicit as where to find the demo files.
References to Anaconda have been removed from the user and developer installation and where appropriate those comments have been placed in the Anaconda installation instructions themselves.
**NB**  **If we chose to continue supporting Anaconda, we should think about whether we want to provide an entire installation path (and test it) and link that in appropriately, or drop Anaconda entirely?**
@vlall 's …

Restructure user and developer installations + misc doc fixes

---

dallinger/heroku/tools.py
tests/test_command_line.py
tests/test_heroku.py

Heroku v7.21 stopped supporting the "--orgs" parameter.
as per: https://github.com/Dallinger/Dallinger/issues/1664
The Heroku CLI has renamed the `--org` parameter to `--team`. From 7.21 this breaks calls to Heroku, so users of Dallinger who are on this version of Heroku cannot launch experiments.
https://devcenter.heroku.com/articles/develop-orgs
This PR makes the change for Dallinger to use the supported "--team" parameter.
Tested to be working on Ubuntu 18.04 with ```heroku/7.22.0 linux-x64 node-v11.9.0```
It is unclear when the "--team" parameter was added.
Looks like Heroku Teams have been around for at least 2.5 years based on the date of https://blog.heroku.com/heroku-teams
From documentation on the ```heroku apps``` command, it looks like the "--team" parameter has been present …

Change Heroku apps parameter from --org to --team

---

docs/source/developing_dallinger_setup_guide.rst
docs/source/installing_dallinger_for_users.rst

This PR addresses https://github.com/Dallinger/Dallinger/issues/1636
It was found that these insecure postgres configuration instructions are not necessary to run experiments.
Tested with a fresh Ubuntu 18.04 installation that deliberately omitted these postgres configuration/installation steps, therefore using postgres defaults which are set to:
```
local   all             postgres                                peer
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all …
```

Remove insecure Ubuntu postgres instructions

---

docs/source/demoing_dallinger.rst

Tell the new user about the "--verbose" by example from day one, in the demoing Dallinger section.

Show "--verbose" as a best practice when running Dallinger experiments

---

CHANGELOG.md
dallinger/command_line.py

A couple problems spotted while working on the demos:
1. A core Dallinger JS file is not checked in the existing duplicate file check
2. If an experiment module defines more than one experiment, that should probably be an error(?)

Updates to `verify_package`

---

dallinger/deployment.py

Fix for #1671 
After creating the remote Heroku app, there may be a delay before a valid value is returned for `REDIS_URL`. This change moves the attempt to connect into the existing try/except/loop construct.
`dallinger sandbox` on Bartlett.

Wait for redis URL on heroku before connecting

---

CHANGELOG.md
dallinger/experiment_server/experiment_server.py
dallinger/models.py
docs/source/classes.rst
docs/source/web_api.rst
tests/test_models.py

Adds a `__json__` method to the `SharedMixin` model base class that includes details for any types that don't already provide `__json__`. Adds `details` to existing model `__json__` methods.
This allows JSONB data stored on various models to be made available via the experiment server API. This should resolve #1645.
Automated tests now include tests for presence of details JSON data.

Add `details` column to json serializations of data

---

CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/requirements.txt
demos/dlgr/demos/chatroom/requirements.txt
demos/dlgr/demos/concentration/requirements.txt
demos/dlgr/demos/function_learning/requirements.txt
demos/dlgr/demos/iterated_drawing/requirements.txt
demos/dlgr/demos/mcmcp/requirements.txt
demos/dlgr/demos/rogers/requirements.txt
demos/dlgr/demos/sheep_market/requirements.txt
demos/dlgr/demos/snake/requirements.txt
demos/dlgr/demos/twentyfortyeight/requirements.txt
demos/dlgr/demos/vox_populi/requirements.txt
demos/requirements.txt
demos/setup.py
setup.cfg
setup.py

- Heroku has deprecated the use of the --org parameter which previous versions of Dallinger used. This release fixes Dallinger to use the newer --team parameter instead, which has been available in Heroku for quite some time. The change was introduced in Heroku CLI 7.21. The --team parameter was introduced in Heroku a significant time ago, thus this version of Dallinger will work with many older versions of the Heroku CLI. If using an older version of the Heroku CLI, we recommend updating to the latest version.
- Improve launch retry messaging when running in debug mode
- `dallinger verify` now fails if you have more than one Experiment class
- Fixed: Add `details` JSON data to `__json__` methods for all models.
- Fixed bug related to running Dallinger with Redis 3.1.0 or higher.
- …

Release version 5.0.6

---

docs/source/developing_dallinger_setup_guide.rst
docs/source/installing_dallinger_for_users.rst

If the user uses Ubuntu 16.04 with Python 3, they will need to use a custom python to get python 3.6+. Update virtualenv installation instructions to reflect this explicitly.

Minor documentation fix

---

dallinger/mturk.py

Addresses #1637 
Timing issues in tests can result in trying to clean up an already deleted HIT. We should just ignore these errors.
Hard to reproduce the error context, and not possible to write an automated test. I did run tests with the `--mturkfull` flag to verify HIT deletion still works, but can't be sure the Except block was executed.

If a HIT is already deleted, don't raise from disable_hit()

---

.travis.yml
tests/conftest.py
tests/test_api.py
tests/test_command_line.py
tests/test_config.py
tests/test_data.py
tests/test_demos.py
tests/test_deployment.py
tests/test_experiment_server.py
tests/test_heroku.py
tests/test_models.py
tests/test_mturk.py
tests/test_networks.py
tests/test_processes.py
tests/test_replay.py
tests/test_replay_state.py
tests/test_sockets.py
tox.ini

The fast tox environment runs a subset of the tests under Python 3.6
that exclude the slowest of the current set. This is intended to be
used to make the development process more usable.
Tests are too slow
I've run the tests locally. Testing on travis now.

Add fast tox environment

---

.pre-commit-config.yaml
tox.ini

- Only show error output from black inside the pre-commit output
- Run black on Travis and fail build if it finds formatting problems
- Too much output from _black_ distracts from the important fact that your commit failed
- Failing Travis build if _black_ finds formatting problems will cover the case where someone pushes a commit on which _black_ hasn't already been applied.
Local failure:
```
$ git commit -a -m "Test output"
black....................................................................Failed
hookid: black
Files were modified by this hook.
```
Travis failure:
```
style runtests: commands[1] | black --check dallinger dallinger_scripts demos tests
would reformat /home/travis/build/Dallinger/Dallinger/dallinger/notifications.py
All done! 💥 💔 💥
1 file would be reformatted, 105 …
```

Black refinements

---

.travis.yml

All Travis builds are failing due to a problem with Ruby gem versions. Updating to the latest Ruby (2.6.2) fixes the problem and seems like a better option than pinning back specific gems.

Update Ruby to fix Travis builds

---

docs/source/classes.rst
docs/source/developing_dallinger_setup_guide.rst

Instructions for installing the pre-commit hook should appear in but Mac OS and Ubuntu sections.
Also fixes a small duplication error in classes.rst.

Fix precommit docs and fix duplicate annotation

---

dallinger/bots.py
dallinger/command_line.py
dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/deployment.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/gunicorn.py
dallinger/heroku/tools.py
dallinger/notifications.py
dallinger/recruiters.py
dallinger/utils.py
demos/dlgr/demos/bartlett1932/experiment.py
demos/dlgr/demos/rogers/config.txt
demos/dlgr/demos/rogers/experiment.py
tests/conftest.py
tests/test_command_line.py
tests/test_config.py
tests/test_deployment.py
tests/test_experiment_server.py

This PR implements [ScrumDo Story 494](https://app.scrumdo.com/projects/story_permalink/1829486). It moves default config values from calls like `config.get(key, default)` to the `global_config_defaults.txt`. It also implements automatic whitespace stripping of strings in `config.get` and fixes some issues with how config was being manipulated in tests. Custom configuration in demo experiments has also been adapted to set default values in `config.txt` instead of in the experiment code.
See [ScrumDo Story 494](https://app.scrumdo.com/projects/story_permalink/1829486). The primary motivation is to centralize the location of all configuration default values and avoid repeating them or accidentally setting defaults to different values in different parts of the codebase.
I added an automated …

Move Config Defaults Out of Python

---

docs/source/index.rst

This is an optional enchancement. TBD if it is desirable or not. See screenshot:
**Before:**
**After**

Have beginner docs show up in lefthand menu of documentation

---

dallinger/command_line.py
dallinger/config.py
dallinger/deployment.py
dallinger/utils.py
tests/test_command_line.py
tests/test_config.py
tests/test_deployment.py

Cleans up experiment temp directory creation code, and checks the size of the proposed file set before copying them from the local experiment directory.
Code to remove temp directories on experiment completion will be implemented separately.
Addresses #1710 
To avoid inadvertently copying large files or directories when running an experiment, check the total size of all the files that _would be copied_ before proceeding.
* `dallinger debug`
Dallinger verify:
```
$ dallinger verify
❯❯ Verifying current directory as a Dallinger experiment...
✓ config.txt is PRESENT
✓ experiment.py is PRESENT
✗ 2309MB is TOO BIG (greater than 50MB)
✓ experiment.py defines 1 experiment
✓ no file conflicts
❯❯ ☹ Some problems were found.
```
Dallinger debug/sandbox/deploy:
```
$ dallinger …
```

Check experiment size before copying

---

CHANGELOG.md
dallinger/command_line.py
docs/source/command_line_utility.rst
tests/test_command_line.py

Expand the command line documentation section & fix some small errors.
Call the ``--app`` flag a parameter and any other parameter that requires some value following a flag a ```parameter```, everything else remains a ```flag``` if it has no parameter following it.
Add a few undocumented commands.
This addresses https://github.com/Dallinger/Dallinger/issues/1672

Expand command line documentation

---

docs/source/installing_dallinger_for_users.rst

Fix an issue detected by Robin Watson on Ubuntu 18.04.2 with Python 3.6.7
When installing Dallinger the line ``` pip install dallinger[data] ``` fails with:
```
That error message you got says: `    Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/psycopg2.egg-info
writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
writing pip-egg-info/psycopg2.egg-info/PKG-INFO
writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'
```
Installing the ```libpq-dev``` package fixes the issue.

Include libpq-dev in installation instructions

---

demos/dlgr/demos/iterated_drawing/models.py

The iterated drawing demo loads an image from the filesystem and creates a base64 encoded data url of it. This changes the loading mechanism to work on Python 3.
Iterated Drawing was not functional on any supported version of Python without this, amazingly.
Manual testing.

Fix encoding of source image to work on Python3

---

dallinger/frontend/static/scripts/dallinger2.js

An extraneous error about module being undefined is present when using dallinger2.js in the browser. This change guards the setting of module.exports.dallinger (which is required for node-based unittesting) to suppress that error.
It annoys users.
Through the web testing and running of jest tests.

Suppress module is undefined error in dallinger2.js in the browser

---

dallinger/config.py
dallinger/experiment_server/experiment_server.py
dallinger/models.py
tests/test_experiment_server.py

This makes the question/response length configurable.
Some experimenters want to have users write longer question responses.
Automated tests only

Add config variable for text length for questions

---

CHANGELOG.md
dallinger/experiment_server/experiment_server.py
dallinger/models.py
demos/dlgr/demos/mcmcp/models.py
docs/source/web_api.rst
tests/test_agents.py
tests/test_experiment_server.py

Currently, it is not possible to add an Info to a Node that is failed. This change alters the check to make it so it's not possible to add an Info to a node that's failed unless the Info is also failed. This keeps the guarantee that Infos on a failed node are all failed and allows developers to explicitly add info to failed nodes.
The `/info/nodeid` route has been changed so it allows a failed parameter to mark JS-originated infos as failed. The `Info` base class's `__init __` also has a failed kwarg for these purposes.
This should be a major version change, as it changes the Info `__init__` signature, albeit in a way that would be backwards compatible for careful users.
See issue #2037 
Extensive unit testing, manual testing of existing (non-failed) case.

Allow failed infos to be created on failed nodes

---

dallinger/config.py
dallinger/utils.py
tests/test_config.py
tests/test_utils.py

This fixes the tests for a base url function, which were poor and in the incorrect place. It also fixes a bug where a HOST environment variable could not be overriden in tests.

Fix base url function

---

dallinger/mturk.py
tests/test_mturk.py

Bugfix: sometimes HITs have no keywords
HITs created through the MTurk web UI may have no keywords. This can cause problems for the Dallinger MTurk API, which assumes they're always present.  This PR checks to see if there are keywords defined before trying to parse them into the internal Dallinger HIT format.

Handle case where HIT has no keywords

---

CHANGELOG.md
dallinger/deployment.py
tests/test_deployment.py

Alters `DebugDeployment` to only make a single attempt to call the `/launch` route. Adds some additional logging on failures.
See #1885
Automated tests have been updated to test that a single attempt is made in debug mode, and that additional logging calls are made. I also manually ran a demo in debug mode.

Issue #1885 don't retry launch route in debug mode

---

CHANGELOG.md
dallinger/config.py
dallinger/deployment.py
docs/source/configuration.rst
tests/test_deployment.py

Adds `dyno_type_web` and `dyno_type_worker` configuration options which override the default `dyno_type`.
See issue #2088
New automated test for heroku dyno scaling.

Issue #2088 configure web and worker dynos separately

---

docs/source/index.rst
docs/source/private_repo.rst

This proposed change documents how to add dependencies on private repositories to Dallinger experiments (fixes #2036).
Such documentation was previously missing.
Documentation successfully rebuilt locally.

Documenting private repositories

---

dallinger/heroku/tools.py
tests/test_heroku.py

Add `dyno_type_web` and `dyno_type_worker` to sanity check method
This will avoid delayed errors on startup when using a free dyno type with a team configuration. See issues #2088 and #1239
An automated test has been added.

Add new dyno_type configs to sanity check

---

dallinger/deployment.py
dallinger/utils.py
tests/test_deployment.py
tests/test_utils.py

Bug fix for #2092 
```
>>> os.listdir('.')
['.DS_Store', 'foo\nbar', 'ånøthér file.txt', '.git', 'fîlé.txt']
>>> from dallinger.deployment import ExperimentFileSource
>>> src = ExperimentFileSource()
>>> src.files
{'./fîlé.txt', './foo\nbar', './ånøthér file.txt'}
```

Non-asciii filename support

---

CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/requirements.txt
demos/dlgr/demos/chatroom/requirements.txt
demos/dlgr/demos/concentration/requirements.txt
demos/dlgr/demos/function_learning/requirements.txt
demos/dlgr/demos/iterated_drawing/requirements.txt
demos/dlgr/demos/mcmcp/requirements.txt
demos/dlgr/demos/rogers/requirements.txt
demos/dlgr/demos/sheep_market/requirements.txt
demos/dlgr/demos/snake/requirements.txt
demos/dlgr/demos/twentyfortyeight/requirements.txt
demos/dlgr/demos/vox_populi/requirements.txt
demos/requirements.txt
demos/setup.py
setup.cfg
setup.py
tests/test_deployment.py

- No longer retry `/launch` route in debug mode. Additional logging for launch retries.
- Allow setting of separate optional `dyno_type_web` and `dyno_type_worker` parameters.
- Regression fix: experiment files with non-ascii characters in file names are again supported
- Documentation for including dependencies on private repositories

Release6.1.0

---

CHANGELOG.md
dallinger/command_line.py
dallinger/default_configs/global_config_defaults.txt
dallinger/experiment_server/experiment_server.py
dallinger/mturk.py
dallinger/notifications.py
dallinger/recruiters.py
docs/source/command_line_utility.rst
tests/test_command_line.py
tests/test_experiment_server.py
tests/test_mturk.py
tests/test_notifications.py
tests/test_recruiters.py

New `dallinger compensate` command to compensate a worker a specific dollar amount.
New `dallinger email_test` command to validate and test email configuration.
The `MTurkService` class, which was initially a hasty port from the psiturk project, was overly rigid about the kinds of HITs you could create; it assumed a HIT would only ever be used to run an experiment. For compensating workers, we use MTurk HITs with nothing to do but click a submit button as a means of paying them when something has gone wrong for them which trying to complete an experiment. A fair bit of this PR involved adding more flexibility to HIT creation via the `MTurkService`, and that's reflected in the large diff.
Previous to this work, the only case where Dallinger sent email messages was to notify experiment …

"compensate" Command

---

dallinger/deployment.py
dallinger/experiment.py
dallinger/experiment_server/dashboard.py
dallinger/frontend/static/css/dashboard.css
dallinger/frontend/static/scripts/network-monitor.js
dallinger/frontend/templates/base/dashboard.html
dallinger/frontend/templates/dashboard_home.html
dallinger/frontend/templates/dashboard_monitor.html
dallinger/models.py
dallinger/pytest_dallinger.py
dallinger/utils.py
docs/source/classes.rst
docs/source/monitoring_a_live_experiment.rst
tests/experiment/templates/dashboard_home.html
tests/test_dashboard.py
tests/test_models.py

This PR integrates the psynet network monitor into the dashboard. It essentially reuses the code as-is, with some code cleanup. The node details have been moved into the Details pane, and transformations are only shown if requested. When a node is clicked, and AJAX request is made to retrieve a custom HTML visualization for the node. By default this is looked up using a `visualization_html` property on the Model class, but the mechanism can be customized further using the `Experiment.node_visualization_html` method which looks up that property by default.
Filters are in place to limit the view to networks and sources only, specific networks only, specific network roles only, and to show/hide all transformations.
Documentation has been updated to reflect the customization mechanisms.
See …

Implement graphical network monitoring dashboard

---

demos/dlgr/demos/bartlett1932/requirements.txt

Fixes #2250
It would be nice to be able to override the required version of dallinger without changing demo requirements.txt files, since this is an easy accidental commit to make. Or maybe a commit hook could catch these....

Revert accidental dependency on dallinger git commit

---

dallinger/deployment.py
dallinger/experiment_server/experiment_server.py
dallinger/pytest_dallinger.py
tests/test_deployment.py
tests/test_experiment_server.py

Switch to determining the Flask secret at launch time and setting it via the environment. This seems to fix the sandbox login issues reported in #2251
The flask `SECRET_KEY` is now determined based on environment variables set during launch (like the password), and read before serving requests, rather than being generated experiment server import time. That should allow the CSRF validation to operate reliably.
Fix for #2251
Tested via sandbox deploy

Fix sandbox password issue

---

.travis.yml

Travis builds are breaking because the default node version is now incompatible. This ensures a compatible node version.

Fix broken Travis builds resulting from node version change

---

dallinger/frontend/static/scripts/network-monitor.js

Addresses node monitor styling issues described in #2273. Non-failed node and info colors should be based on participants. Infos who's nodes don't have a `participant_id` are checked for `participant_id` now even though it is not a canonical property of the `Info` class. The rules in #2220 should now be in effect, once the infos are given a `participant_id` in the data by customizing the Experiment class `json_data` method.
See issue #2273
I tested these changes manually using the non_adaptive demo in debug mode.

Fixes for node monitor styling

---

CHANGELOG.md
dallinger/utils.py
tests/test_deployment.py
tests/test_recruiters.py
tests/test_utils.py

Changes displayed hostname to `localhost` when the `host` config is set to the debug default of `0.0.0.0`. The application should still listen on all interfaces, but the displayed and auto-opened urls will use `localhost` to help ensure they don't trigger browser security issues.
See #2272
New test for the host change. Updated tests that depended on old debug default value.

Change dallinger debug from 0.0.0.0 to localhost

---

CHANGELOG.md
dallinger/config.py
dallinger/default_configs/local_config_defaults.txt
dallinger/deployment.py
dallinger/experiment_server/dashboard.py
dallinger/experiment_server/experiment_server.py
dallinger/pytest_dallinger.py
docs/source/configuration.rst
docs/source/monitoring_a_live_experiment.rst
tests/test_dashboard.py
tests/test_deployment.py
tests/test_experiment_server.py

The dashboard credentials are now retrieved from configuration variables (`dashboard_user`, and `dashboard_password`) rather than environment variables. This allows customizing passwords via e.g.
`~/.dallingerconfig`. The defaults are still the same when the configuration variables are unset.
See issue #2276. Users would like to be able to use consistent dashboard passwords across experiment runs.
I tested the new configuration variables manually in debug and sandbox mode. Additionally, I added an automated test that the variables are being set in the config as expected when unset, and updated existing tests to read the variables from the configuration.

Allow Dashboard Password to be Set Using Config

---

constraints-deps.txt
dallinger/experiment_server/gunicorn.py
tests/test_experiment_server.py

Enables `ProxyFix` middleware when not in production mode to ensure Flask generates https links when serving proxied over https from Heroku. Additionally, sets flask `SECRET_KEY` during gunicorn load to help avoid initial 500 errors when first page load tries to generate CSRF tokens.
See #2289. The `SECRET_KEY` is now set in two places, but I think this is fine because the value is consistent. There may be some need to run the Flask application without the gunicorn wrapper, in which case setting it in the `before_first_request` would still be necessary, but setting it earlier when running in a load-balanced fashion is probably best.
Tested on sandbox (wrapped) and in debug mode (not wrapped). Added automated tests for ProxyFix calls and `SECRET_KEY` setting.

Fix for HTTPS inconsistency #2289

---

CHANGELOG.md
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
docs/source/javascript_api.rst
docs/source/the_experiment_class.rst
docs/source/web_api.rst
tests/test_experiment.py
tests/test_experiment_server.py

Provides an implementation of #2242. Provides a new mechanism for retrieving and setting data about a participant based on an `assignmentId`. There are three components:
A `load_participant` method on the `Experiment` class that takes an `assignment_id` and returns the matching `Participant`. This can be overridden by subclasses to perform other actions required to restore a user session.
A new `/participant` route that takes a `POST` request with an `assignment_id` argument, and calls the above method to retrieve the corresponding participant from the experiment.
A new `dallinger.loadParticipant` function which takes an `assignmentId` which asynchronously retrieves the participant data using the methods above and sets the resulting information in the `dallinger.identity` object. It …

Add JS function to allow resuming Participant session

---

CHANGELOG.md
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
docs/source/the_experiment_class.rst
docs/source/web_api.rst
tests/test_experiment.py
tests/test_experiment_server.py

Implements #2258 allowing experiment developers to customize the class/process for adding partcipants to the experiment. This PR includes three changes (and documentation/test updates):
1) Adds a `create_participant` method to the `dallinger.experiment.Experiment` class.
2) Updates the `/participant/` creation route to delegate to `dallinger.experiment.Experiment.create_participant`.
3) Adds a `participant_constructor` attribute to `dallinger.experiment.Experiment` which defaults to `dallinger.models.Participant` and is used by `create_participant`. Experimenters who simply want to replace `Participant` with a subclass can override this attribute to use their custom class. It is only necessary to override `create_participant` to provide more complex behavior.
See issue #2258
Automated …

Allow Custom Participant Class

---

CHANGELOG.md
dallinger/experiment.py
dallinger/experiment_server/dashboard.py
dallinger/frontend/templates/dashboard_database.html
docs/source/monitoring_a_live_experiment.rst
docs/source/the_experiment_class.rst
tests/test_dashboard.py
tests/test_experiment.py

This PR implements DataTables button actions for the Dallinger Database Dashboard.
It adds two button groups to the form. The first is called `export`, which includes an option for a JSON export of selected (or all) rows as well as the built-in DataTables CSV and Print options. The second is called `actions` and it contains and action to fail selected nodes, and, when running on MTurk, an action to provide a command to compensate selected participants.
Additionally, the `actions` group can be customized by customizing the Experment `dashboard_database_actions` method to provide additional actions, each with a `name` and a `title`. The action `name` should correspond to a method on the class that accepts a data array and returns a message.
See issue #2257. This work provides an …

Dashboard Database Actions

---

dallinger/experiment.py
tests/test_dashboard.py

Removes active participants computation from dashboard network monitor statistics. The method did not return useful information and likely caused performance issues (see #2311 and #2312).
See #2312 (also performance issues described in #2311)
Manual testing, automated test update.

Remove active participants from network monitor dashboard

---

CHANGELOG.md
dallinger/config.py
dallinger/data.py
dallinger/default_configs/global_config_defaults.txt
dallinger/mturk.py
dallinger/pytest_dallinger.py
docs/source/configuration.rst
tests/test_api.py
tests/test_data.py
tox.ini

Add a configuration flag (off by default) to enable the global S3 experiment id registry.
This disables a feature that is largely unused and relies on a specially configured S3 bucket that is currently unavailable. Disabling this feature will allow tests to pass so that we can make a working release.
Updated/new automated tests.

Disable global S3 experiment id registration

---

.travis.yml
CHANGELOG.md
dallinger/command_line.py
dallinger/data.py
dallinger/db.py
dallinger/deployment.py
dallinger/recruiters.py
dev-constraints.txt
docs/source/command_line_utility.rst
tests/test_command_line.py
tests/test_deployment.py
tests/test_recruiters.py

Provide a new `--archive` option to `dallinger deploy` and `dallinger sandbox` which makes it possible to start an experiment run with the database populated from an experiment archive created with `dallinger export`.
Divided into three sections, for clarity (hopefully).
- When an exported experiment archive is provided, overwrite the remote database during deployment, before the `/launch` route is called, so that the new experiment picks up where the archived experiment left off
The most complicated aspect of this feature turned out to be the need to support multiple HITs related to a single experiment. Previously, we could assume that there was only one HIT, and its ID could be found by querying the Heroku postgres database for any Participant created via MTurk, and using the record's …

Support bootstrapping a deployment from an experiment archive

---

dallinger/db.py
dallinger/deployment.py
dallinger_scripts/worker.py

SSL certificate requirements for Redis set to "none" wherever necessary in the code base. 
Heroku recently changed their default Redis version to 6.0 (it was formerly 5.0). This breaks Dallinger when attempting to use non-free Redis add-ons, since Heroku's configuration requires SSL for non-hobby add-ons (Dallinger will still therefore launch the various demos, since those are set to use hobby-grade add-ons). I have attempted several different ways of "fixing" my own SSL certificates, but to no avail. I eventually decided to remove the requirement for SSL entirely from my Redis connections, and a Heroku representative later independently suggested this solution. I did not realize that this problem was due to the upgrade to Redis 6 at the time that I made this change. An alternative …

Fix issue deploying to Dallinger with Redis 6

---

dallinger/experiment_server/dashboard.py

Adds the Question type to the list of models included in the DB dashboard by default.
See #2414
Through the web testing in debug mode only. The change is trivial.

Add Questions (trivial) to DB dashboard

---

dallinger/experiment_server/dashboard.py
tests/test_dashboard.py

The DB dashboard contained some special handling for Array objects which attempted to allow individual Array items to be filtered. That logic caused issues with rendering Arrays and needed to be removed. The array handling is now identical to the Object/dict handling.
See issue #2313
Manual testing with Array data in `details` column. Updates to automated tests.

Remove broken DB Dashboard SearchPanes logic for array data

---

dallinger/recruiters.py
tests/test_recruiters.py

Fix for issue #2373 
Since MTurk requester accounts with large numbers of HITs make querying MTurk for the current HIT ID impractical, this PR switches to storing the current HIT ID in redis.
* Allows MTurk dashboard load quickly, while still supporting the `--archive` option to `dallinger deploy` and `dallinger sandbox`
* Makes previous, complicated system of querying MTurk for the current HIT Id unnecessary
* Reduces weird patching in recruiter tests
* Bartlett1932 sandbox deployment

Use redis to store the current HIT Id for the MTurkRecruiter family

---

CHANGELOG.md

Recent release notes where missing the "v" in the "vX.X.X" portion of the tag URL, so the generated links don't work.

Fix tag URLs in CHANGELOG

---

dallinger/config.py
dallinger/experiment.py
demos/dlgr/demos/bartlett1932/experiment.py
demos/tests/test_bartlett.py
docs/source/extra_configuration.rst
docs/source/the_experiment_class.rst
tests/experiment/dallinger_experiment.py
tests/test_config.py

This PR implements an optional `extra_parameters` method at the Experiment class level. The method is called automatically during experiment initialization. The method should only be called once for a given `Configuration` instance. Includes documentation and test updates.
See issue #2432
Automated tests have been updated to include class based parameter registration. The Bartlett1932 demo has been updated to use a class method for parameter registration.

Implement `extra_parameters` configuration as a class method

---

tests/conftest.py
tests/test_data.py

This PR segregates these tests into a class which gets skipped unless a `--s3buckets` flag is included when running tests.
Tests that create S3 buckets have historically failed randomly on Travis, and are now failing regularly due to bucket creation limits. We are paying for far more than we're getting out of these tests, which largely verify AWS S3 behavior, and exercise code that is extremely stable in Dallinger.
It's all about Travis CI.

Split out tests that create S3 buckets

---

dallinger/config.py
dallinger/experiment.py
demos/dlgr/demos/bartlett1932/experiment.py
demos/tests/test_bartlett.py
docs/source/extra_configuration.rst
docs/source/the_experiment_class.rst
tests/conftest.py
tests/experiment/dallinger_experiment.py
tests/test_config.py
tests/test_data.py

Undoes merged PRs that caused issues. Avoided using revert to simplify history and rebases.
People need to be able to use master with experiments that currently fail due to these half-finished changes.

Undo changes on master related to fail_reason and experiment_params

---

tests/conftest.py
tests/test_data.py

This PR segregates these tests into a class which gets skipped unless a `--s3buckets` flag is included when running tests. 
Tests that create S3 buckets have historically failed randomly on Travis, and are now failing regularly due to bucket creation limits. We are paying for far more than we're getting out of these tests, which largely verify AWS S3 behavior, and exercise code that is extremely stable in Dallinger.
It's all about Travis CI.

Split out tests that create S3 buckets (PR to master)

---

dallinger/models.py
dallinger/pytest_dallinger.py
docs/source/classes.rst
tests/test_models.py
tests/test_networks.py

Adds a `failed_reason` SQLAlchemy attribute to all classes inheriting from `dallinger.models.SharedMixin`. See #2254 
It is useful to be able to track the reason an object was `fail()`ed.
I'm hazy on whether adding a DB column and accessing it represents a breaking change requiring a major release.
* superficial debug tests using Bartlett1932
Assume a Network with some related Nodes and Vectors received a `fail()` message.
When an explicit reason was passed to `fail()`, which was propagated from Network downwards:
```python
>>> explicit = 'Boom!->Network1->Node1->Vector1'
>>> original_reason, *chain = explicit.split('->')
>>> original_reason
'Boom!'
>>> chain
['Network1', 'Node1', 'Vector1']
```
When no explicit reason was passed:
```python
>>> implicit = …
```

Add failed_reason attr/column, and use it to capture cascading failures

---

.github/workflows/ci.yml
CHANGELOG.md

Add PYPI deployment steps to finish porting of Travis workflow to Github actions.

add deploy steps

---

.github/workflows/ci.yml

This PR adds a github workflow to check `pre-commit` constraints using the `pre-commit` github action.
It also changes the way `node` is installed, removing the installation of Node Version Manager, to only rely on the `node` that is set up by Github actions.

Improve github actions

---

.github/workflows/ci.yml
.pre-commit-config.yaml

The current pre-commit configuration mentions pep8, but for me the hook was not running.
Also, the black version used by the pre-commit hook is the one that happens to be already installed on the user machine, not a specific one.
I needed to wait full test runs to find out I had a problem detected by flake8. 
I believe the proposed pre-commit hook configuration will improve developer productivity by catching problems early.

Pre commit fixes

---

dallinger/experiment_server/dashboard.py
tests/test_dashboard.py

Adds basic HTML escaping to datatables code for Database Dashboard
See latest comments on #2414
New unit tests for escaping feature. Manual testing in debug mode.

Add html escaping to Database Dashboard display output

---

dallinger/config.py
dallinger/experiment.py
demos/dlgr/demos/bartlett1932/experiment.py
demos/tests/test_bartlett.py
docs/source/extra_configuration.rst
docs/source/the_experiment_class.rst
tests/experiment/dallinger_experiment.py
tests/test_config.py

This PR implements an optional `extra_parameters` `classmethod` on the Experiment class. The method is called automatically during experiment initialization. The method should only be called once for a given `Configuration` instance. Includes documentation and test updates.
See issue #2432
Automated tests have been updated to include class based parameter registration. The Bartlett1932 demo has been updated to use a class method for parameter registration.

Allow `extra_parameters` configuration from classmethod

---

.github/workflows/ci.yml
dallinger/bots.py
dallinger/default_configs/global_config_defaults.txt
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/base/ad.html
dallinger/frontend/templates/base/consent.html
dallinger/models.py
dallinger/pytest_dallinger.py
dallinger/recruiters.py
demos/dlgr/demos/bartlett1932/config.txt
demos/tests/conftest.py
dev-constraints.txt
docs/source/the_experiment_class.rst
docs/source/web_api.rst
tests/conftest.py
tests/test_bots.py
tests/test_experiment.py
tests/test_experiment_server.py
tests/test_recruiters.py
tox.ini

Implements a general mechanism for validating Ad url parameters and turning them into parameters required to create a participant. Provides a new method `normalize_entry_information` on the `Experiment` class and the base `Recruiter` class. The default `Experiment` method delegates to the recruiter to perform the check. The check method takes an` entry_information` dict and returns a dictionary with parameters needed to create a participant. The default implementation just looks for `hit_id` or `hitId`, `assignment_id` or `assignmentId`, and `worker_id` or `workerId` and uses those directly. Additional parameters are included in the `entry_information` key.
The participant class now has a JSONB column to store the `entry_information` directly.
The experiment server route `POST …

Generic Recruiter Support

---

.dockerignore
.github/workflows/ci.yml
dallinger/command_line/docker.py
dallinger/deployment.py
dallinger/docker/deployment.py
requirements.txt
setup.py

Do not install `docker` and `docker-compose` dependencies unless the `[docker]` extra is specified with
```
pip install dallinger[docker]
```
#2568 introduced `docker` and `docker-compose` as unconditional dependencies.
This caused #2581 and is not necessary in most cases, in particular when using a  Heroku sandbox.
This PR fixes #2579 
CI
In addition there is a .dockerignore file that I worked on in the context of the previous PR but forgot to commit.

Install docker only as an optional dependency

---

dallinger/experiment_server/experiment_server.py
tests/test_experiment_server.py

Fix for #2582
When previewing a HIT on MTurk, a worker ID is not yet passed as a parameter to the /ad route
* Bartlett in MTurk sandbox

Worker ID needs to be optional, to support HIT preview on MTurk

---

.github/workflows/ci.yml
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/static/scripts/dallinger2.test.js
docs/source/running_the_tests.rst

URL parameters passed to the /ad route by both MTurk and Dallinger's own recruiters use camelCase for `workerId`, `hitId`, and `assignmentId`, but we were not parsing the URL with this convention in mind. We were instead assuming snake case (`worker_id`, etc.). The caused delays (at least) in getting these values set correctly in the `dallinger.identity` JS object.
This PR also reinstates running of JS tests as part of the CI build, documents how to run them locally.
Fix for #2604 
* Bartlett1932, in debug
* Updated jest test

Ad route URL parameters are actually camel-case

---

.github/workflows/ci.yml
dallinger/command_line/docker.py
dallinger/docker/docker-compose.yml.j2
dallinger/docker/tools.py
requirements.txt
setup.py
tests/test_deployment.py
tox.ini

This PR aims at fixing the docker tests.
Some improvements to the docker support are included:
* health checks for postgres and redis, to make sure they're ready when other services are started
* new commands to start postgres and redis services using docker (only needed when using heroku deployments - docker deployments take care of those services alongside the experiment services)
* docker related tests are run with tox
Invoking `dallinger debug --verbose --bot --no-browsers` in the `bartlett1932` directory worked for me locally but I could not get it to run in CI, neither through tox/pytest nor by direct invocation.
On CI the experiments hangs until a timeout. These are the last lines of logs:
```
>>>> ----- Launching experiment...
2021-03-11 17:31:45,119 Initializing BotRecruiter... …
```

Fix docker tests

---

dallinger/db.py
dallinger/deployment.py
dallinger/pytest_dallinger.py

Possibly because we recently bumped up our versions, this problem started to appear:
```2021-03-16T22:51:00.067813+00:00 app[worker.2]: File "/app/.heroku/src/dallinger/dallinger/db.py", line 27, in <module>
2021-03-16T22:51:00.068028+00:00 app[worker.2]: engine = create_engine(db_url, pool_size=1000)
2021-03-16T22:51:00.068065+00:00 app[worker.2]: File "<string>", line 2, in create_engine
2021-03-16T22:51:00.068324+00:00 app[worker.2]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
2021-03-16T22:51:00.068693+00:00 app[worker.2]: return fn(*args, **kwargs)
2021-03-16T22:51:00.068739+00:00 app[worker.2]: File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 520, in create_engine …
```

Fix sqlalchemy dialect name

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

This PR changes the way the release to pypi and to github releases is managed wrt its integration with github actions
Currently the secrets are stored in the `CI` environment. Environments are meant to host secrets that, when used, have an effect on the outside world.
For Dallinger the following secrets are in this category (and should live in [the environment named `pypi`](https://github.com/Dallinger/Dallinger/settings/environments/201786602/edit)):
* PYPI_API_TOKEN
* CHANDLER_GITHUB_API_TOKEN
while these ones are used to run tests (and should live in [the repository secrets](https://github.com/Dallinger/Dallinger/settings/secrets/actions)):
* MTURK_WORKER_ID
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
For this PR to work the secrets above need to be set up.
I used my credentials on …

Fix deployment environments

---

.gitignore
dallinger/command_line/__init__.py

Suppress warnings from SQLAlchemy about duplicate names on polymorphic_identity.
All Dallinger experiment sqlalchemy models trigger warnings because of the way Dallinger imports the experiment module. This is basically distracting noise in the context of developing or deploying and experiment, and we'd probably be better off without seeing these warnings.
See https://github.com/Dallinger/Dallinger/issues/269
Without suppression:
```
$ dallinger verify
❯❯ Verifying current directory as a Dallinger experiment...
✓ config.txt is PRESENT
✓ experiment.py is PRESENT
/Users/jesses/projects/py_dev/dlgr_demos/vaelgates_dallinger_demos/.venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py:1108: SAWarning: Reassigning polymorphic association for identity 'empty' from <Mapper at 0x108ff1850; …
```

Ignore sqlalchemy warnings

---

dallinger/deployment.py
tests/test_deployment.py

This change makes Dallinger build and bundle its wheel only when deploying remotely.
The locally installed egg is already used anyway, so in the local debug case building the wheel is not needed.

Improve `dallinger debug` startup time

---

dallinger/db.py
dallinger/deployment.py

Provides more information when connecting locally to Postgres fails.
@omonida had a not-so-fun experience where redis was running on the port usually used by Postrges (5432), and when `dallinger debug` started up, it just hung with no info and was very hard to quit:
```
dallinger debug --verbose
✓ config.txt is PRESENT
✓ experiment.py is PRESENT
✓ experiment.py defines 1 experiment
✗ static/scripts/store+json2.min.js OVERWRITES shared frontend files inserted at run-time
____        ____
/ __ \____ _/ / (_)___  ____ ____  _____
/ / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
/ /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
/____/
v7.1.0
Laboratory automation for
the behavioral and social sciences.
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Creset
^C^C^[^[^[^Cquit
^C^C^C^C
```
This …

Add timeout and better error info to local Postgres connection check

---

dallinger/default_configs/global_config_defaults.txt
dallinger/pytest_dallinger.py

3.9.1, our current default version, has been deprecated on Heroku due to a security problem, so this updates the default to 3.9.2 for Heroku deployment.

Update default python version for Heroku

---

dallinger/frontend/templates/dashboard_home.html

The dashboard link to Dallinger documentation on configuration was broken. This PR updates the link.
Broken:

Fix URL to documentation about configuration

---

dallinger/deployment.py
tests/conftest.py
tests/test_deployment.py

The `local_checks=False` flag was missing on the call to `deploy_sandbox_shared_setup()`, so we were treating a heroku deployment as if it were running locally.
memoryexp3 with Heroku deployment

Bugfix: heroku deployments are by definition "remote"

---

dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/pytest_dallinger.py
dallinger/recruiters.py
docs/source/configuration.rst
tests/test_recruiters.py

Adds a new config parameter `disable_when_duration_exceeded` which is enabled by default. The default experiment behavior is unchanged. When this parameter is set to `False` the duration exceeded event triggered by the clock server will not disable the MTurk auto-recruit or expire the hit.
See #2617
I added new automated tests for this feature, and existing tests for the original behavior all still pass.

Allow configuration of duration exceeded behavior for MTurk Recruiter

---

dallinger/command_line/__init__.py
docs/source/command_line_utility.rst
tests/conftest.py
tests/test_command_line.py
tests/test_mturk.py
tests/test_recruiters.py

To provide more insight into your MTurk HIT inventory (similar to feature of https://manage-hits-individually.s3.amazonaws.com), allow one to view all their HITs with `dallinger hits` instead of forcing you to specify a Dallinger app ID.
The `--app` parameter is still supported, but is now optional.
This command now accepts either an experiment/app ID, or a HIT ID, so you can just expire a HIT directly.
In trying to get to the bottom of #2144 I found having no way to view my full HIT list with details such as `annotation` and `status` a major hindrance.
Locally, against an MTurk account provided by @jacobyn 
```
dallinger hits --sandbox
2021-04-06 11:29:07,842 - /Users/jesses/projects/py_dev/Dallinger3/dallinger/experiment.py - ERROR - Could not import experiment.
❯❯ Found 612 hit[s]:
Hit …
```

`dallinger hits` will show all your HITs by default

---

dallinger/config.py
dallinger/recruiters.py

Allow for the declaration of a specific `Recruiter` class in config.txt.
This pull request accomplishes two things:
1. Allow for a custom `Recruiter` class in debug mode other than `HotRecruiter` by introducing a new config variable `debug_recruiter`.
2. Return at runtime the correct custom `Recruiter` class from the `by_name` function in recruiter.py
Specific `Recruiter` classes are otherwise not set correctly, incl. in debug mode..
Tested by running experiments in debug/sandbox mode in combination with custom `Recruiter` classes.

Facilitate support for custom recruiters

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/worker_events.py
dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/templates/error-complete.html
dallinger/frontend/templates/error.html
dallinger/mturk.py
dallinger/recruiters.py
docs/source/recruitment.rst
docs/source/the_experiment_class.rst
tests/test_experiment.py
tests/test_experiment_server.py
tests/test_mturk.py
tests/test_recruiters.py

Addresses issue #2261 
Allow the Experiment to control qualification assignment to workers.
Instead of the Dallinger infrastructure calling the recruiter directly for qualification assignment, this work will now manged by the Experiment in cooperation with the recruiter for a Participant.
The underlying objective is to add flexibility to when MTurk Qualifications are assigned to workers. Currently this is always done after the post-experiment questionnaire is submitted to the `/worker_completed` route. 
The PR proposes moving in the direction of notifying the Experiment class when various experiment lifecycle events happen, and letting the Experiment then request qualification assignment from participant's recruiter reference (to support the MultiRecruiter).
The status quo is preserved …

Move control of qualification assignment to Experiment class

---

dallinger/frontend/static/scripts/dallinger2.js

Sometimes participants close the parent window, so we can't load the /recruiter-exit route there. This PR checks for the presence of the parent window, and opens /recruiter-exit in the current window if the parent is no longer there.
Bug reported by @pmcharrison and @fmhoeger 
Completely untested. :-)

Bugfix: open /recruiter-exit it experiment window if parent unavailable

---

dallinger/frontend/templates/dashboard_mturk.html

Fixed typo in dashboard for extending a hit. 
Issue: #2775
I ran the `bartlett1932` demo in debug to check that dashboard command matched that of `dallinger -h`. 
Note that the two commands now agree.

Fixed #2775. Typo in dashboard.

---

dallinger/experiment.py
dallinger/heroku/clock.py
dallinger/pytest_dallinger.py
docs/source/configuration.rst
docs/source/index.rst
docs/source/scheduled_tasks.rst
tests/experiment/dallinger_experiment.py
tests/test_experiment.py
tests/test_heroku.py

This PR implements a new decorator `@dallinger.experiment.scheduled_task` which allows functions or classmethods on the experiment class to be used as background tasks to be run by the clock server. The task intervals are controlled using the trigger type and arguments from the [`appscheduler`](https://apscheduler.readthedocs.io/en/stable/) used by the clock scheduler.
For example to run a background task every 10 minutes, you could add the following to your experiment class:
```
@scheduled_task("interval", minutes=10)
@classmethod
def my_scheduled_task(cls):
... do stuff ...
return
```
A task can also be run at clock server start using the following:
```
@scheduled_task("date")
@classmethod
def my_one_off_task(cls):
... do stuff ...
return
```
There are three types of triggers available …

Add support for custom task registration from experiment class

---

dallinger/command_line/__init__.py
dallinger/heroku/tools.py
dallinger/registration.py
tests/test_heroku.py
tests/test_recruiters.py

Changes the generated heroku app name to use 18 characters of the Dallinger app id instead of 8.
See #2840 for details.
Automated tests have been updated to reflect the app id length change.

Increase character limit on app names

---

.github/workflows/ci.yml
dallinger/deployment.py
dallinger/experiment.py
dallinger/experiment_server/dashboard.py
dallinger/experiment_server/experiment_server.py
dallinger/heroku/clock.py
dallinger/pytest_dallinger.py
dallinger/recruiters.py
dallinger/utils.py
demos/dlgr/demos/mcmcp/experiment.py
demos/dlgr/demos/sheep_market/experiment.py
docs/source/monitoring_a_live_experiment.rst
docs/source/the_experiment_class.rst
tests/experiment/dallinger_experiment.py
tests/test_dashboard.py
tests/test_deployment.py
tests/test_experiment.py
tests/test_experiment_server.py
tests/test_heroku.py

This PR implements an `experiment_routes` Flask Blueprint on the `Experiment` class, similar to the optional `extra_routes` Flask Blueprint defined at the module level. It also updates the MCMCP and Sheep Market demos to use the new route registration mechanism and updates the docs to include the Blueprint as part of the `Experiment` class API. There is also a custom route registration decorator which makes it possible to define the route functions at the class level (though they must be either `classmethod` or plain functions and cannot access the experiment instance directly).
Additionally, to simplify Dashboard route registration this PR now includes a parallel `dashboard_tab` decorator which registers an Experiment class `classmethod` or function as a dashboard tab. This simplifies …

Add experiment_routes Blueprint on experiment class

---

dallinger/heroku/tools.py

This PR gets `dallinger debug` to launch the clock process as well as the web and worker processes (see #2869).
The debug process should resemble the deployment process as closely as possible.
By running `dallinger debug` and inspecting the Heroku logs.

Run clock process in debug mode

---

docs/source/conf.py

`Sphinx.add_stylesheet` was removed and replaced with `Sphinx.add_css_file` in Sphinx >= 4.
This change will allow updating of Sphinx to a version >= 4.
```
...
...
Making 'mcmcp' demo...
Making 'vox_populi' demo...
Initializing Spelling Checker 7.2.1
making output directory... done
Exception occurred:
File "/home/runner/work/Dallinger/Dallinger/docs/source/conf.py", line 432, in setup
app.add_stylesheet('custom.css') # html_static_path is automatically prepended
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-oo4uamew.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker …
```

Rename Sphinx.add_stylesheet to Sphinx.add_css_file

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
Dockerfile
dallinger/docker/Dockerfile.web
dallinger/docker/Dockerfile.worker
dallinger/docker/tools.py
docs/source/docker_setup.rst

This PR adds a github action that is run on pushes to version tags. It builds two docker images (`dallinger` and `dallinger-bot`) and pushes them to the GitHub container registry.
To support the work on docker we need a canonical place to store dallinger images. 
GitHub is launching a container registry service (currently in beta) at ghcr.io.
This PR builds and pushes docker images there:
* https://github.com/orgs/dallinger/packages/container/package/dallinger
* https://github.com/orgs/dallinger/packages/container/package/dallinger-bot
I tested the new action from my fork of this repository. The docker images [were built and pushed successfully](https://github.com/silviot/Dallinger/runs/2279961092?check_suite_focus=true).

Push docker images on release

---

.github/workflows/deploy.yml

There should be enough checks in place already to make sure this does not happen.
The task that does the waiting is erroring out for no apparent reason.

Do not wait for tests to complete before releasing in CI

---

dallinger/experiment_server/experiment_server.py
docs/source/demoing_dallinger.rst
tests/test_experiment_server.py

This PR adds a new optional url parameter to the `/ad` route which allows for automatic generation of the recruiter entry information parameters (`hitId`, `assignmentId`, `workerId`). When an ad url is sent with `?generate_tokens=1` the ad route will redirect to the ad route with all request arguments (except `generate_tokens`) preserved, and random values for any of the standard entry information parameters that weren't provided.
I added some documentation of this feature in `demoing_dallinger.rst`, but I'm not quite sure if that's the right place for it.
See #2974. This should allow passing a single link to recruit users for an experiment using the HotAir recruiter or any recruiter that will accept randomized entry info values.
There are two new automated tests for the redirector, and I …

Add argument to /ad url that allows for auto-generation of entry info

---

dallinger/command_line/utils.py
dallinger/utils.py
tests/test_deployment.py

This PR changes no outward functionality, but lays the groundwork for being able to symlink various files into a directory rather than copy them.
As a first step, this work separates _defining_ what files need to by copied into the generated temp  directory from actually doing the copying. This will facilitate swapping out the copy operation for symlink creation instead.
A secondary perk of this work is that it does away with most of the fussiness of adding new files to Dallinger's `frontend` to be deployed when running experiments. I left all the individual file checks in tests (and in fact added even more) because I wanted to feel very confident in the change for now.
* Bartlett demo
* @silviot has begun using the python 3.5+ `Path` class in some other work. A lot of …

Issues/2114 dallinger develop: underpinnings

---

dallinger/experiment.py

This PR implements better exception logging/handling in `dallinger.experiment.load()` when no class is found in the imported experiment, it will log the first ImportError exception that was triggered in addition to a message about the class not being available.
See #2935
Tested manually.

Add better error logging in `experiment.load()`

---

dallinger/heroku/tools.py
tests/test_heroku.py

Sometimes an error occurs and `dallinger debug` immediately shuts down the process before logging the traceback has been output. This PR introduces an extra step after detecting an error. It will now read out the process output until it hits a new error, the process has exited, or one second has elapsed (it's a very short time because this is generally just a buffering issue, and the output should be available immediately).
See #2532 
Manual testing with an intentionally broken demo, and a known issue in an older revision of a psynet demo. Automated tests to ensure the new method is called on errors, and executes as expected.

More complete debug output on errors

---

.coveragerc
dallinger/command_line/docker_ssh.py

Provide a new `dallinger docker-ssh stats` command to show per container CPU and memory usage info as displayed by `docker stats` on the remote host:
```
CONTAINER ID   NAME                                  CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
edfd18585a96   dlgr-ae9fe938_worker_1                0.00%     77.25MiB / 1.44GiB   5.24%     16.5kB / 18.9kB   43.8MB / 8.19kB   2
1523ee13556e   dlgr-ae9fe938_web_1                   0.13%     154MiB / 1.44GiB     10.44%    46.3kB / 405kB    37.7MB / 16.4kB   9
007e3e921d9c   dlgr-ae9fe938_redis_dlgr-ae9fe938_1   4.18%     5.68MiB / 1.44GiB    0.39%     20.6kB / 14.8kB   17.3MB / 254kB    6
71792c6e8ea7   dallinger_httpserver_1                0.00%     26.62MiB / 1.44GiB   1.81%     3.02MB / 2.57MB …
```

New docker-ssh stats command

---

dallinger/utils.py
tests/test_command_line.py

I think this fixes the space issue when looking up a path in the egg-link file. I wasn't able to reproduce the issue, but I think the cause of the problem is quite clear. Instead of reading the whole egg-link file and splitting on whitespace, it should now read in just the first line and strip leading/trailing spaces (e.g. trailing newline).
See #2861
I was not able to test this (except via a python prompt to verify the issue with the original code), but I'm fairly certain it should resolve the problem with determining the directory from the `.egg-link` file.

Fix egg-link path lookup

---

demos/dlgr/demos/bartlett1932/experiment.py
demos/dlgr/demos/function_learning/experiment.py
demos/dlgr/demos/iterated_drawing/experiment.py
demos/dlgr/demos/mcmcp/experiment.py
demos/dlgr/demos/rogers/experiment.py

Demos that add nodes to network on initialization need to explicitly commit a transaction to ensure these nodes get written to the database.
Currently we rely on a combination of luck and the fact that the /launch route makes a commit after opening recruitment. In other contexts, the state of the database after experiment initialization will likely differ from expectations, since the network will be written to the DB, but additional nodes (Source nodes, for example) will only be transient.
Bartlett demo, in the context of working on `dallinger develop`

Demos that add nodes to network on initialization need to explicitly commit

---

.readthedocs.yml

Update RtD config to install Dallinger using pip and use the new syntax for installing the requirements. See [most recent build failure](https://readthedocs.org/projects/dallinger/builds/14252821/).
See #2957
Can only be tested by merging to master AFAIK. 🤞 Should be very low risk, since RtD is already broken.

Another RtD fix attempt

---

dallinger/experiment_server/experiment_server.py
tests/test_experiment_server.py

This PR adds error handling and logging to the `create_participant()` function (and Flask route) to provide more information when participant creation fails.
See #3153 
* Bartlett1932 demo, by manipulating `dallinger.identity` values with the browser dev tools
* Automated test

Log submitted participant values and full exception on failure

---

dallinger/db.py
tests/test_db.py

The PR ensures that db url values using the unsupported `postgres` scheme will have the scheme corrected to `postgresql` when the engine is created via `dallinger.db.create_db_engine()`
Fix for #2856 

The postgres:// to postgresql:// uri fix should be applied more universally

---

dallinger/frontend/static/scripts/dallinger2.js

`dlgr.loadParticipant` originally referred to a global `assignment_id`, but I think this was a mistake, and it meant to refer to `resp.participant.assignment_id`.
The function didn't work for me without this change.
I made the fix, and now the `loadParticipant` functionality works well for me.

Bugfix in dlgr.loadParticipant

---

demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
scripts/update_experiments_constraints.sh

On linux the command  `md5sum` is provided by `coreutils` and always present. On BSD systems (like Mac OS) the command `md5` is present.
Instead of using one or the other, this PR makes use of python 3, that should be available in all contexts where Dallinger is used.

Cross platform version of md5

---

docs/source/conf.py
docs/source/developing_dallinger_setup_guide.rst
docs/source/installing_dallinger_for_users.rst

See #3104
Starting redis and postgres using docker is much easier, and dallinger ships with a command to use them.

Document `dallinger docker start-services`

---

dallinger/deployment.py
dallinger/recruiters.py

Extremely trivial change to add a message in the debug command output with the link to the recruiter ad url using the `generate_tokens` parameter enabled.
See #3305
Ran demo with `--no-browsers` and tested the link was present and worked as expected.

Add single recruiter link (#3305)

---

dallinger/command_line/docker_ssh.py
dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2

See #3140 
The directory inside the container (the one that the experiment code needs to write to) is always `/var/lib/dallinger`, regardless of experiment id.
Files written to such directory in the container will end up in `/var/lib/dallinger/{{ experiment_id }}` on the host.
The owner of the files will be root, since the dallinger containers currently run the web server and the worker using the `root` user inside the container.
Experiments might need access to a persistent filesystem.
I checked that the container has the expected asset by entering it with `docker exec` and writing a file to `/var/lib/dallinger`.
I didn't yet test the case when the experiment is exported and reimported.

Expose directory from the host when deploying with docker

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
docs/source/conf.py
docs/source/the_experiment_class.rst

This PR provides a very simple implementation of #3739 by adding a `hidden_dashboards` attribute to the `Experiment` class. This attribute contains a list of route/function names to be excluded from rendering as dashboard tabs. It also fixes a bug in the documentation configuration that was preventing API documentation from being rendered properly.
See the issue #3739 for motivation
I tested this manually by setting a value for the `hidden_dashboards` attribute on a demo experiment and verifying that the expected tabs were hidden. I did not attempt to write an automated test for this change because it is very small, and executes at import time (which can cause issues for test repeatability). I'd appreciate any ideas for how to reasonably provide automated tests for this change which …

Allow dashboard tabs to be hidden

---

dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js
tests/test_experiment_server.py

Update dallinger2.js `createParticipant` method to use the version of the call that stores `entry_information` by default, falling back to the old mechanism if no `entry_information` can be extracted from the URL/Request (I don't think this should ever occur, but it seems like the safest fallback). The change is pretty trivial.
See #2652
I tested this in debug mode with a couple of demos. Ideally it should probably also be tested in an MTurk sandbox.

Use entry information routing by default

---

dallinger/utils.py

See #3184
If the `requirements-dev.txt` file for the current Dallinger version can't be found on github the local one is looked up (and can be found if dallinger was installed in editable mode) and used.
Currently `dallinger generate-constraints` tries hard to make sure experiments have versions of their dependecy pinned to the same versions as the ones included in the docker base image for the Dallinger version they depend on. This is to prevent, for instance, the case when they specify a different psycopg version that will need to be compiled to create a docker image for the experiment, and the compilation will fail because of the lack of a compiler in the image.
I successfully ran `dallinger generate-constraints` on the `iterated_drawing` demo experiment with a local master version …

Use local dev-requirements.txt if there's no such file on github for dallinger version currently in use

---

.github/workflows/ci.yml
dallinger/default_configs/global_config_defaults.txt
setup.py

Move to python 3.10 as "primarily supported" version (meaning, we do the most aggressive testing in CI, and we deploy using this version on Heroku by default).
- Take advantage of improved error messages in 3.10
- Stay on the front edge of python version support
TODO:

Bump to python 3.10 by default for full CI runs and Heroku deployment

---

dallinger/experiment_server/dashboard.py
tests/conftest.py
tests/test_mturk.py

Related to https://github.com/Dallinger/Dallinger/issues/3793
Get rid of following `PytzUsageWarning` warnings in the log output:
`PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

Fix PytzUsageWarning: Migrate to new way datetimes are localized

---

tests/test_mturk.py

Increase determinacy of MTurk integration tests:
1. Re-run the "smoke test" up to 3 times on CI
2. Consolidate some HIT creation tests so we have fewer tests overall
3. Re-introduce a system for creating a single HIT description for all tests in a single session to be used in test cleanup to prevent interactions between different runs (multiple CI runs happening simultaneously, or a developer test run happening at the same time as a CI run, for example.)
4. Mark xfail a test for `check_credentials()` with empty strings for key and secret, which has started failing on CI (and CI only) every time for some reason. I have some regrets about not getting to the bottom of this, but the value of the test is not currently worth the pain it's causing.
5. Use an URL under https://www.example.com for …

Reduce flakyness of MTurk tests

---

dallinger/deployment.py

Modified `dallinger debug` to open the dashboard asynchronously.
Previously `dallinger debug` opened the dashboard synchronously, and due to a limitation of the underlying web driver this delayed the opening of the experiment window by five seconds. This can be avoided by opening the dashboard asynchronously. This closes #3897.
By manually running `dallinger debug`.

Open dashboard window asynchronously

---

docs/source/index.rst

Added a couple of mentions of Prolific to the documentation home page, for parity with Mechanical Turk.
Prolific is keen that we make it clear that people can use Prolific with Dallinger.

Mention Prolific on documentation home page

---

dallinger/config.py

Fixes #3337.
It turned out that we just needed a little change to `initialize_experiment_package` to make sure that the imported experiment package looks the same to Dallinger/SQLAlchemy irrespective of how the function is called. 
I can confirm that with this fix `dallinger develop` now works with our PsyNet experiments. Excited to finally take advantage of it, @jessesnyder!

Fix initialize_experiment_package for dallinger develop

---

dallinger/frontend/static/scripts/network-monitor.js

I have fixed a couple of small formatting issues with the dashboard network visualisation. 
First, I have updated the text by Infos so that it says the class name rather than just 'info'. This is particularly useful for PsyNet, where the term 'Info' is not so informative.
Second, I have fixed an issue for the display of networks that have no nodes; previously the visualization would draw a line between these networks and an unrelated node from a different network. Now the network is just left without any connections.

Minor update to network visualistion

---

dallinger/pytest_dallinger.py

This concerns `debug_experiment`, a fixture for running regression tests using `dallinger debug`.
We have had problems where not all errors in debug experiments were logged in pytest. It turned out that this was due to a couple of reasons:
1. The fixture did not use verbose mode for `dallinger debug`, meaning that important information was missed;
2. The fixture did not propagate all the logs to pytest.
This PR fixes these issues. I can confirm that I am now seeing the missing errors in pytest.

Better logging in test debugging experiments

---

dallinger/command_line/develop.py
dallinger/config.py
dallinger/dev_server/app.py
dallinger/dev_server/run.sh
dallinger/experiment_server/dashboard.py
dallinger/frontend/templates/dashboard_develop.html
setup.py

@jessesnyder did most of the work on a hot-refreshing version of `dallinger debug`. However as it currently stood one had to run a series of commands in different directories to get it working. This pull request streamlines the process to match the simplicity of `dallinger debug`. One simply runs `dallinger developer debug` from the experiment directory, waits a few moments, then the dashboard appears, presenting a button which the user can press to open a new participant window.
Note: I have also extended the hot-refresh functionality to include clock and worker processes.
Note: this PR also includes a commit cherry-picked from #3929, concerning `initialize_experiment_package`.

Finishing the hot-refresh implementation

---

dallinger/command_line/docker_ssh.py

When deploying via docker important information is written to the console (STDOUT) at the end of the deployment process. This includes the URL of the deployed experiment, the credentials to log into the dashboard as well as info for how to access the logs.
Unfortunately, all this data is lost when closing the terminal window, e.g. unintentionally, unless it has been manually copied into a file before.
We want the deployment information as described above to be automatically written to a file in the current directory.
See #4096

Persist docker deployment infos to a file in the current directory

---

dallinger/dev_server/run.sh

Addresses #4290.
- Removes the not-supported `eager-loading` option from the `flask run` command.
- Replaces the deprecated `FLASK_ENV` command with `FLASK_DEBUG`.

Update for latest Flask version

---

dallinger/models.py

- Enables experimenters to subclass Vector objects in the same way that one might subclass Node objects, by adding a polymorphic identity on the `type` column.
- Have set the default value of the corresponding SQL column to `vector` so that we can maintain back-compatibility with data exports from before the addition of this column.
I have tested manually that this works.

Allow subclassing vectors

---

dallinger/pytest_dallinger.py

When running on CI, the `env` test fixture previously created a sandbox home directory, but did not copy over the `.dallingerconfig` from the original directory. This is problematic as otherwise this config file would be a useful way to specify global configurations for automated tests that spawn debug experiments. Dallinger hasn't encountered this problem before because its CI tests don't spawn debug experiments, but we've run into this problem now with PsyNet, which does. This PR fixes the issue. I have tested it through our PsyNet CI tests, which rely on this functionality.

Preserve .dallingerconfig when using env fixture

---

Dockerfile

Depend on official python docker images and use version 3.10 
Currently the docker build uses `ubuntu:20.04` as base image, and the python version shipped by default with that image.
This makes changing the python version cumbersome.
By using the python image as base, there's a well defined point where we can change the pyhton version used to build docker images.
Automated tests are passing.

Use python 3.10 base image for docker

---

dallinger/models.py

The previous version of `models.py` left the `foreign_keys` unspecified in several relationship definitions. This works when SQLAlchemy can infer the foreign keys by itself. However, this functionality can break when adding additional foreign keys in subclasses. This PR adds explicit `foreign_keys` arguments to these relationship definitions so that the problem no longer occurs.

Add foreign keys to relationships

---

dallinger/command_line/docker_ssh.py

When deploying using `dallinger docker-ssh deploy`, copy the local docker configuration file `~/.docker/config.json` to the remote server, to allow pulling images from private docker image repositories.
See #4263
Manual testing

Copy docker config to support private image repositories

---

dallinger/command_line/docker_ssh.py

See #4265 
Users should be able to specify a custom app name when deploying
Manual testing

Let users specify a custom app name

---

dallinger/config.py
dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2
docs/source/configuration.rst

See #4266
When deploying using `dallinger docker-ssh deploy` it's useful to be able to specify additional volumes to mount.
This PR adds the `docker_ssh_volumes` config variable to let users specify a list of volumes to mount
Manual testing.

Add docker_ssh_volumes config option to specify additional volumes

---

.github/workflows/deploy.yml
Dockerfile
dallinger/command_line/__init__.py
dallinger/command_line/docker.py
dallinger/command_line/docker_ssh.py
dallinger/dev_server/run.sh
dallinger/docker/tools.py
dallinger/utils.py
docs/source/docker_only.rst

Allow users to run dallinger commands from the published dallinger docker image (at ghcr.io/dallinger/dallinger).
Tested with local development and `dallinger docker-ssh deploy`.
See #2584

Instructions to develop an experiment with only docker as a dependency

---

dallinger/command_line/__init__.py
dallinger/command_line/docker.py
dallinger/command_line/docker_ssh.py
dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/deployment.py
dallinger/docker/docker-compose.yml.j2
dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2
dallinger/experiment.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/templates/base/layout.html
dallinger/utils.py
docs/source/configuration.rst
docs/source/docker_support.rst
tests/experiment/experiment.py
tests/test_config.py
tests/test_deployment.py
tests/test_docker.py
tox.ini

I have put a load of inline comments to help explain the various changes. Here is a summary of what has been done:
- Disabled the behavior where the built image name is written to config.txt. This behavior was inconsistent with the other Dallinger deployment patterns, because it meant that if you deployed once, changed code in experiment.py, then redeployed, then the experiment would launch in the former version unless you remembered to delete the image name from config.txt.
- Heroku deployments were failing because the default `heroku_python_version` had been discontinued by Heroku. We have experienced similar problems in the past and have always had to update Dallinger. Now we have changed the behaviour such that, if `heroku_python_version` is not specified in the experiment config, …

Misc Docker quality of life improvements

---

dallinger/command_line/docker.py
demos/dlgr/demos/bartlett1932/config.txt
demos/dlgr/demos/chatroom/config.txt
demos/dlgr/demos/concentration/config.txt
demos/dlgr/demos/function_learning/config.txt
demos/dlgr/demos/iterated_drawing/config.txt
demos/dlgr/demos/mcmcp/config.txt
demos/dlgr/demos/rogers/config.txt
demos/dlgr/demos/sheep_market/config.txt
demos/dlgr/demos/snake/config.txt
demos/dlgr/demos/twentyfortyeight/config.txt
demos/dlgr/demos/vox_populi/config.txt
docs/source/demos_on_heroku.rst
tox.ini

Replace all occurrences of `hobby-dev` with `standard-0` for Postgres and with `premium-0` for Redis.
For reference see
https://devcenter.heroku.com/articles/heroku-postgres-plans
https://elements.heroku.com/addons/heroku-redis
See also issue #4632

Migrate to new Heroku Postgres/Redis plans

---

docs/source/docker_only.rst
docs/source/index.rst

There were several documentation pages that weren't being indexed by Sphinx and hence weren't being published to the documentation website, including the new Docker documentation. I have addressed this now.

Fix unpublished doc pages

---

dallinger/config.py

Originally when calling `Config.load_from_environment` an error message would be logged for each environment variable that does not correspond to a Dallinger configuration key:
```
raise KeyError("{} is not a valid configuration key".format(key))
```
This is clearly undesirable behavior because environmental variables will often include keys that don't correspond to Dallinger configuration keys. I have fixed this behavior by modifying the code such that `Config.extend` only throws this error if `strict=True`.

Eliminate unnecessary 'is not a valid configuration key' errors

---

dallinger/experiment_server/experiment_server.py
dallinger/experiment_server/utils.py

Refactoring of `advertisement()` to prepare the advertisement in a separate function. This allows wrappers around dallinger, e.g. PsyNet, to use other rendering functions than the one used in Flask. This is for example important, if you want to add custom Jinja filters or add translations.

Refactoring of `advertisement()`

---

CHANGELOG.md
dallinger/frontend/templates/dashboard_develop.html

Added `source=dashboard` to the entry information stored for participant sessions created via the dashboard. This helps to distinguish debugging participants from 'real' participants.
Tested manually (it's a very simple change) and have updated the CHANGELOG.

Add source=dashboard to participant sessions started from the dashboard

---

.pre-commit-config.yaml
CHANGELOG.md
constraints.txt
dallinger/command_line/docker_ssh.py
dallinger/docker/tools.py
dev-requirements.txt
requirements.txt

After discussing with Silvio, have agreed the following fixes for docker-ssh deployment.

Misc Docker deployment fixes

---

dallinger/command_line/docker_ssh.py

- Fixed import of `u` function for paramiko version >= 3

Fix paramiko import

---

dallinger/command_line/utils.py

The concept of base pay is mturk specific. It is not required in Prolific, so you should be able to set it to 0.

Also allow base pay to be 0 in the case of Prolific.

---

dallinger/db.py

The error catching logic in init_db was failing with current versions of SQLAlchemy and has now been fixed.

Better error catching in init_db

---

dallinger/utils.py

The `collate_experiment_files` function is responsible for constructing the experiment directory that is eventually deployed. Due to an oversight, the original version was written in a way such that it was impossible to override built-in Dallinger resources using the `extra_files` hook; such cases were instead silently ignored. This has now been rectified.

Update to collate_experiment_files

---

dallinger/heroku/clock.py

The following scheduled task was defined in clock.py:
```py
@scheduler.scheduled_job("interval", minutes=0.5)
def check_db_for_missing_notifications():
"""Check the database for missing notifications."""
config = dallinger.config.get_config()
participants = Participant.query.filter_by(status="working").all()
reference_time = datetime.now()
run_check(participants, config, reference_time)
```
The `Participant.query` command would start a Postgres transaction, but this transaction would never be terminated. This would cause errors if the server process had to be restarted, because there would never be a moment at which the connection could be gracefully terminated. I have now added a `db.session.commit()` at the end of this function to avoid this problem.

Fix missing commit in clock.py

---

dallinger/recruiters.py

Currently, Prolific keeps on recruiting new participants, even when `auto_recruit` is set to false in Heroku.
Here I provide a small fix.

Check if auto_recruit is True in order to autorecruit a new participant in Prolific

---

dallinger/prolific.py

If the Prolific API returned a JSON response that could not be decoded as valid JSON, Dallinger would throw an error but would not say what the invalid JSON string was. Now this JSON string is printed as part of the error messsage.

Add better logging for Prolific JSONDecodeError

---

dallinger/heroku/rq_gevent_worker.py

The recent Dallinger update that fixed compatibility with  rq >= 1.13.0 then broke back-compatibility with  rq < 1.13.0. The present PR addresses this issue.

Fix back-compatibility with rq < 1.13.0

---

dallinger/utils.py

When running `dallinger generate-constraints`, run `pip-compile`  in verbose mode, so that you can debug slow running resolutions.

Run pip-compile in verbose mode

---

dallinger/experiment.py
dallinger/frontend/static/css/dashboard.css
dallinger/frontend/static/scripts/network-monitor.js
dallinger/frontend/templates/dashboard_monitor.html
dallinger/models.py
tests/test_dashboard.py

Improvements to the Dallinger network monitor:
- selecting a single network only redraws the graph on the front end and does not require reloading all data from the DB again
- networks can be sorted by network ID, number of failed, completed, and pending Infos, as well as the number of failed and completed nodes
- Sorting can be done in ascending and descending order
- Users can show the top X networks if there are too many networks in an experiment
- Users can use free-text search to look for attributes in networks
- Cleaned up the panels in the monitor giving more space to the monitor itself
Steps for testing:
- I made sure the existing network tests don't fail
- I ran the `bartlett1932` demo to validate the monitor works well in Dallinger

Improved network monitor

---

dallinger/config.py
dallinger/experiment.py
dallinger/registration.py
tests/test_bots.py
tests/test_experiment_server.py

- Added `Experiment.config_class`, a hook for customizing the Configuration class.
Have tested manually by defining a custom config class in experiment.py and using it to customise config variable treatment.

Allow customization of Configuration class

---

dallinger/db.py
dallinger/experiment.py
dallinger/experiment_server/dashboard.py
dallinger/frontend/templates/dashboard_monitor.html
dallinger/models.py
tests/test_dashboard.py
tests/test_models.py

Enhanced efficiency in dashboard monitor data loading.
Previously the dashboard could take a very long time to load when the database contained many custom object classes. In such cases we are now running about 1000 times faster.
I have added a few unit tests for new functions included in this merge request. The monitor already had good coverage with unit tests, and these are now passing, showing that existing functionality has been preserved. I have manually tested performance of the dashboard with a large experiment (2000 networks, PsyNet static_big demo, faster-exports branch), and have verified that performance is now much improved.

Faster monitor

---

dallinger/command_line/docker_ssh.py

- Fixed `remote_postgres` for compatibility with docker compose v2. This was necessary because docker compose v2 uses slightly different container names by default, using hyphens as separators rather than underscores.
Tested locally by running an experiment export.

Fix remote_postgres for docker compose v2

---

dallinger/command_line/docker_ssh.py

- Fixed failure in `docker-ssh deploy` that occurred when the app exists already. 
Previously we had a command called `remove_redis_volumes` which dealt with pre-existing volumes from a previous deployment. However this command would fail sometimes if the Docker app was still running. I've now supplemented this command with a `docker compose down` invocation that will first take the app down if it exists.
Tested manually by deploying experiments.

Fix docker-ssh failure when app exists already

---

dallinger/command_line/docker.py
dallinger/command_line/docker_ssh.py

Fixed a bug where config dashboard credentials weren't being propagated to Docker deployments.
Tested by manual deployment

Propagate config dashboard credentials to Docker

---

dallinger/command_line/docker.py
dallinger/command_line/docker_ssh.py

Fixed a bug where app name / ID was not set appropriately in config during Docker deployment. Now when you docker-ssh deploy with a specified `--app` argument this is saved as expected in `config.heroku_app_id`.
(As an aside, the name heroku_app_id is not ideal and we should consider updating it one day)
Tested by manually deploying experiments.

Fix app-id not set in Docker deployment

---

dallinger/frontend/static/scripts/dallinger2.js

* Prevent closing the dashboard tab on `submitAssignment()`

Prevent closing the dashboard tab on submitAssignment

---

.github/workflows/ci.yml
Dockerfile
demos/dlgr/demos/bartlett1932/constraints.txt
setup.py
tests/test_deployment.py

- Infrastructure:
- Added Python 3.11 to list of supported programming languages and to CI workflow
- Updated `Dockerfile` to use Python 3.11

Add support for Python 3.11

---

dallinger/command_line/docker_ssh.py

When Docker-SSH deploys and an app currently exists with that name, there is currently code for stopping any pre-existing app. This code uses `docker compose down`, but this command throws an error like this:
```
Error response from daemon: error while removing network: network dallinger id 4fd314c36d2e3baf56d450156c189ea078522bed75a7824ba8108a403e47971c has active endpoints
```
Following the implementation in `dallinger docker-ssh destroy`, we can safely ignore this error because we don't want/need to remove this network. So, we just pass `_raise=False` to stop these errors from breaking the command.

Fix bug in Docker SSH 'removing any pre-existing app with the same name'

---

dallinger/frontend/static/scripts/dallinger2.js
dallinger/frontend/static/scripts/dallinger2.test.js
dallinger/models.py

* Save `uniqueId` in `dlgr.identity` JavaScript object
* Increase `unique_id` database column string size to 150

Improvements to 'unique ID' storage

---

dallinger/command_line/docker_ssh.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/static/scripts/dallinger2.js

Fixed several bugs that were manifesting on SSH deployments, some of which were specific to Prolific.
- Fixed wrong signature for `executor.run()` call in `docker_ssh.py`.
- Ensured that `config` is loaded before every Flask request; previously config was not loading in advance of the serving of static files and this was causing server errors.
- Fixed a bug in parent window closing which was preventing Prolific experiments from completing.
- Ensured that all fields in `dallinger.identity` are set properly when calling `dallinger.createParticipant`.
I have tested this by debugging an experiment locally and by sandboxing with Docker SSH to Prolific. Note that PsyNet experiments need the hotfix https://gitlab.com/PsyNetDev/PsyNet/-/merge_requests/509 before they can deploy properly.
This fix …

Hotfix ssh deploy

---

dallinger/docker/docker-compose.yml.j2

Fix indentation bug writing Docker volumes in `docker-compose.yml.j2` introduced in commit https://github.com/Dallinger/Dallinger/commit/d316719ac3c91a0e46a9e4a5b23a850c72b9aafe

Fix indentation for Docker volumes in docker-compose.yml.j2

---

dallinger/recruiters.py
demos/dlgr/demos/rogers/models.py

This fix addresses a couple of small typos in docstrings.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!

Fix small spelling errors in documentation

---

dallinger/frontend/static/scripts/dallinger2.js

Fixed a bug in `dlgr.submitAssignment` that was causing MTurk HIT submission to fail. This bug was introduced in v.9.7.0 when fixing another bug (where the dashboard tab was closed on `dlgr.submitAssignment`). The bug meant that `externalSubmit` was being called in the popup window, not the MTurk iframe, causing submission to fail.
I tested this by completing a HIT on MTurk Sandbox, but it would be good if @fmhoeger verifies that this fixes the problem.

Fix bug in dlgr.submitAssignment

---

dallinger/command_line/docker_ssh.py

By not choking on a missing caddy config file
See #5192

Make it possible to destroy a partially deployed app

---

dallinger/utils.py

When checking for installed experiment dependencies Dallinger uses `importlib.util.find_spec`, but packages whose install name differs from their import name (e.g. `PyYAML` which is imported as `yaml`) aren't found by that check. This change falls back on `pkg_resources.get_distribution` to check the package name when the `find_spec` check fails.
We want GridUniverse to use some YAML configuration and depending on PyYAML caused an issue in `dallinger.uitls.check_experiment_dependencies`. This fixes that import and is likely needed for other libraries as well. The two checks are a bit redundant, and the new check would probably suffice on its own, but there doesn't seem to be any harm in checking both.

Add check for dependencies using `pkg_resources`

---

dallinger/utils.py
scripts/update_dependencies.sh
scripts/update_experiments_constraints.sh

With pip-tools version 7.0.0 `--resolver=backtracking` became the default setting, so it can be removed from `pip-compile` commands.
CHANGELOG for pip-tools 7.0.0: https://github.com/jazzband/pip-tools/releases/tag/7.0.0
See issue https://github.com/Dallinger/Dallinger/issues/4919 for reference.

Remove --resolver=backtracking for pip-tools>=7.0.0

---

Dockerfile

* The download URL for Chromedriver changed as of version 115. This PR fixes the recent issue where the CI docker job fails due to a wrong chromedriver download URL.

5418 chromedriver fails to download in ci docker job

---

dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/experiment_server/experiment_server.py
dallinger/pytest_dallinger.py

The `create_participant` route ordinarily begins by locking the Participant table (see `experiment_server.py`):
```py
try:
session.connection().execute(
"LOCK TABLE participant IN EXCLUSIVE MODE NOWAIT"
)
except exc.OperationalError as e:
e.orig = TransactionRollbackError()
raise e
```
If this command happens to run at the same time as another server process that interacts with the participant table, it is possible for a deadlock to occur. In such cases the entire server process freezes. This could lead to timeouts in participant requests.
Another approach would be to rewrite experiment code to avoid such deadlocks. In theory one should be able to introduce other locks on the experiment side to avoid such deadlocks occurring. However it is hard to get this right in SQLAlchemy and we have …

Introduce config variable 'lock_table_when_creating_participant'

---

dallinger/command_line/docker_ssh.py

See #5092
Custom domain names to deploy experiments are already supported in dallinger, but there's no documentation except for the output of `dallinger docker-ssh deploy --help`.
This PR adds sanity checks (to fail early in case the option `--dns-host` doesn't refer to a properly configured name) and a warning that some browsers might deem the domain insecure.

Check validity of dns host and nudge users into registering one and using it

---

.github/workflows/ci.yml

CHANGELOG
* Fixed: Fixed problem with failing CI tests by updating setup-chromedriver to v2.1.2.
See https://github.com/Dallinger/Dallinger/issues/5472

Update setup-chromedriver to v2.1.2

---

dallinger/frontend/static/scripts/network-monitor.js

Fixed a bug where participant IDs weren't always displaying properly in the dashboard network visualization. 
In particular, this edit concerns the labelling of edges between nodes and infos:
I have updated the code that works out what participant ID to display. Originally it would look first at `node.participant_id`, then `info.participant_id`. I have now reversed the priority so that the more specific `info.participant_id` is prioritised if available.

Fix the display of participant IDs in the dashboard monitor

---

dallinger/command_line/develop.py

Fixed bug where dashboard URL was no longer printing in the `dallinger develop` command.

Fix dashboard URL not printing in dallinger develop

---

setup.py

Make sure `pip install Dallinger` or `pip install -e .` from a checkout don't break by downloading a Werkzeug that's too new.

Add hard version constraint for Werkzeug

---

dallinger/db.py

Fixed bug in `get_polymorphic_mapping` which was causing the experiment dashboard to fail when two classes of the same name were registered both in the local experiment and in another package.

Bugfix in get_polymorphic_mapping

---

dallinger/recruiters.py

* Set `completion_code` to `None` when `id` config attribute is not available.

Allow recruiters to be instantiated outside active experiments

---

dallinger/models.py

Removed the character limit for the 'type' attribute on SQLAlchemy classes. This should have no performance impact (https://stackoverflow.com/a/4849030/8454486).

Remove character limit for types

---

dallinger/recruiters.py
tests/test_recruiters.py

I revised the logging text
> Study now published on Prolific
to the more accurate
> Study created on Prolific
The former was a bit misleading for cases where there is no initial recruitment of participants

Revise 'Study now published on Prolific' -> 'Study created on Prolific'

---

dallinger/command_line/develop.py
dallinger/command_line/docker.py
dallinger/command_line/docker_ssh.py
dallinger/deployment.py
docs/source/troubleshooting.rst
tests/test_deployment.py

The `dallinger docker-ssh deploy` is very scarce in details when the http request to `/launch` the experiment fails. The heroku deployment gives more details.
This PR makes `dallinger docker-ssh deploy` use the same code to do the request, improving the error handling. It also adds a test for failures (to make sure helpful messages are emitted) and changes the logic of the `handle_launch_data` function to be more explicit (for instance when a request returns a non-json body.
See #5124 
A unit test has been added.

Improve handle_launch_data error reporting and use it also for docker-ssh deployments

---

dallinger/command_line/docker_ssh.py

There was a missing `f` in an f-string that was causing deployments to fail.

Bugfix in handle_launch_data

---

pyproject.toml

Currently numpy and pandas are listed in pyproject.toml despite not being used by Dallinger. This makes the Docker image unnecessarily heavy. This PR removes them.

Remove numpy and pandas dependencies as they are not used by Dallinger

---

dallinger/command_line/utils.py
tests/test_command_line.py

Underscores are not allowed in domain names for SSL certificates.
See https://www.ssl.com/faqs/underscores-not-allowed-in-domain-names/
We should therefore check if underscores are not in the app name.
The proposal is to only allow: `a-z ` , `0-9` , and `-`.

Make sure app name only contains valid characters

---

dallinger/experiment_server/dashboard.py
dallinger/frontend/templates/dashboard_develop.html

Show database reset button in dashboard only in debug mode as it is too dangerous when deployed !

Show database reset button in dashboard only in debug mode

---

dallinger/default_configs/local_config_defaults.txt

Add `dashboard_password` to local_config_defaults.txt to allow doing `config.dashboard_password` from within tests.

Add dashboard_password to local_config_defaults.txt

---

dallinger/experiment.py

With Python 3.12 we get these lines in the console:
`SyntaxWarning: invalid escape sequence '\*'`

Fix SyntaxWarning: invalid escape sequence '\*'

---

dallinger/experiment_server/dashboard.py
dallinger/experiment_server/experiment_server.py
dallinger/frontend/templates/dashboard_develop.html
dallinger/recruiters.py

The value for `recruiter` in the 'New participant' link in the dashboard's "Development" tab is hardcoded as "hotair". Instead, the value should be set dynamically, e.g. when deploying with Prolific as recruitment method `recruiter` should be set to "prolific". However, when debugging the same experiment locally `recruiter` should use "hotair" as the value assigned.

Use dynamic recruiter value when clicking 'New participant' link in the dashboard

---

.bumpversion.cfg
CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/chatroom_ws/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
demos/requirements.txt
demos/setup.py
pyproject.toml

- Removed `check-latest: true` from `setup-python` action in ci.yml.
- Renamed `prolific.co` to `prolific.com` for API calls to `api.prolific.com` and for various other subdomains.
- Fixed value for `recruiter` in the 'New participant' link in the dashboard's "Development" tab. It is now set dynamically, e.g. when deploying with Prolific as recruitment method `recruiter` is set to "prolific", whereas when debugging the same experiment locally, `recruiter` is assigned "hotair" as value.
- Infrastructure: Updated dependencies.

Release v10.1.2

---

constraints.in
constraints.txt
dallinger/command_line/__init__.py
dallinger/command_line/ec2.py
dallinger/command_line/lib/ec2.py
dallinger/command_line/utils.py
dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dev-requirements.in
dev-requirements.txt
docs/source/ec2_deployment.rst
docs/source/index.rst
pyproject.toml
requirements.txt
scripts/update_dependencies.sh

This code is derived from @polvanrijn's work on the CAP package. Refs #6588
Implements and documents various command line extensions related to EC2 instance provisioning. A couple of notes for those already using these commands via the `cap` package:
* I've changed the default security group name from `cap` to `dallinger`, but you can override that in your dallinger config using the `ec2_default_security_group` variable.
* I've changed the default SSH key pair id (PEM file) from `cap` to `dallinger`, but you can override that in your dallinger config using the `ec2_default_pem` variable.
* I've updated the commands to not require a `--region` specification, the `aws_region` config will be used by default if a `--region` is not specified. The exception is the `ec2 list instances` command …

Add EC2 provisioning support to Dallinger commandline

---

dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/docker/docker-compose.yml.j2
dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2
docs/source/configuration.rst

This PR address issue #6336 .
This PR adds a new `worker_cpu_shares` configuration variable which limits the worker CPU usage when resources are constrained.
This make use of the docker `--cpu-shares` option:
`Set this flag to a value greater or less than the default of 1024 to increase or reduce the container's weight, and give it access to a greater or lesser proportion of the host machine's CPU cycles. This is only enforced when CPU cycles are constrained. When plenty of CPU cycles are available, all containers use as much CPU as they need. In that way, this is a soft limit. --cpu-shares doesn't prevent containers from being scheduled in Swarm mode. It prioritizes container CPU resources for the available CPU cycles. It doesn't guarantee or reserve any specific CPU access.`
In Docker …

Limit worker CPU usage

---

dallinger/experiment_server/experiment_server.py
dallinger/prolific.py
dallinger/recruiters.py
tests/test_recruiters.py

@pmcharrison writes:
> We wish to add a subclass of `ProlificRecruiter` called `DevProlificRecruiter` which can be used to debug and test Prolific  experiments locally (currently when you run in debug mode the experiment defaults to `HotAirRecruiter`, so recruiter-specific code doesn't get run). Every time a communication with the API would happen, we should print to the logs the content of the call, but not actually try to make the call.
>
> @fmhoeger has already made some progress on this but has had health issues recently and has not been able to finish it. We were wondering whether someone would be able to continue and finish it.
- Added `DevProlificRecruiter` and `DevProlificService` for Prolific development
Depends on https://github.com/Dallinger/Dallinger/pull/6408

Prolific development recruiter: 5pts

---

dallinger/command_line/ec2.py
dallinger/command_line/lib/ec2.py

Implements https://github.com/Dallinger/Dallinger/issues/7099
- I stopped an existing server using `--dns-host` which removed the DNS entry
- I started the server again using `--dns-host` which added the DNS entry for the newly given public dns
- All docker containers with `restart: always` started as expected and the app was available under the requested dns

Change DNS entry on restart

---

dallinger/command_line/ec2.py
dallinger/command_line/lib/ec2.py
dallinger/command_line/utils.py

Includes following fixes:
- Check the instance name complies with same naming conventions as for the app name (underscores lead to errors)
- Allow to override `pem` and `security_group_name` (previously the passed parameters are always overridden by the .dallingerconfig)
- ~~Provide the instance name for adding (during provisioning) and removing (during teardown) the server name. E.g. if you do run this `dallinger ec2 provision --name abc --region eu-west-3 --dns-host xyz.my-experiments.com` you want to add the server `abc.xyz.my-experiments.com` and not just `xyz.my-experiments.com`, since your apps will be deployed to: `my_app.abc.xyz.my-experiments.com`~~ This was actually a mistake in my head, so nvm
- Fix a bug in fetching instance name if it's missing
- Bug fix for pem file stored …

Ec2 bugfixes

---

constraints.txt
dallinger/command_line/__init__.py
dallinger_scripts/worker.py
dev-requirements.txt
pyproject.toml
requirements.txt

Refactor to make Dallinger compatible with `rq >= 2` . We thereby get rid of the many deprecation warnings like
```
/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/rq/utils.py:227: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
return calendar.timegm(datetime.datetime.utcnow().utctimetuple())
```

Update to rq v2

---

.bumpversion.cfg
CHANGELOG.md
constraints.txt
dallinger/version.py
demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/chatroom_ws/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
demos/requirements.txt
demos/setup.py
dev-requirements.txt
pyproject.toml
requirements.txt
scripts/update_experiments_constraints.sh

- Renamed config variable `activate_recruiter_on_start` to `open_recruitment` and allow it to be set to `True` also by using a `--open-recruitment` flag
- Added new config variables `prolific_workspace` and `prolific_project` to support declaration of Prolific workspaces and project names (the workspace must already exist and a new project in that workspace will be created if it doesn't exist already)
- Added the `dallinger docker-ssh sandbox` command
- Added `validate_config` methods to recruiters
- Added `local_only` to `exclusion_policy` used when assembling the deployment directory. Users can then use this directory called `local_only` to store misc files that they don't want deployed to the web server.
- Keep Dallinger database in sync with Prolific via combination of regular polling …

Release 11.0.0

---

dallinger/config.py
dallinger/default_configs/global_config_defaults.txt
dallinger/experiment_server/experiment_server.py
dallinger/frontend/templates/base/layout.html
dallinger/pytest_dallinger.py
dallinger/utils.py

Automatic translation using Google translator built in to Chrome can lead to unexpected errors.
- Run a Korean local psynet experiment on `master` and auto translate translates the whole page to English
- Run a Korean local psynet experiment on `disable-browser-autotranslate` and auto translate DOES NOT translate to English

Disable automatic translation in the browser

---

.bumpversion.cfg
CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/chatroom_ws/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
demos/requirements.txt
demos/setup.py
pyproject.toml

- Fixed a bug in `DevProlificService` when debugging locally with `recruiter = prolific`. Previously, an exception was raised erroneously saying that no corresponding Prolific workspace was found
- Added `disable_browser_autotranslate` config variable to prevent automatic translation when using the Google translator built into Chrome. `Default is False`
- Added `publish_experiment` config variable to indicate if the experiment should be published when deploying. Currently only used in Prolific recruitment; if `False` a draft study will be created which later can be published via the Prolific web UI. Default is `True`
- Added `Recruiter.supports_delayed_publishing` attribute
- Removed `--open-recruitment` config variable; removed `--open-recruitment` flag from `deploy` and `sandbox` …

Release 11.1.0

---

dallinger/command_line/ec2.py
dallinger/command_line/lib/ec2.py
dallinger/config.py

Option to disable strict config variable loading.
Useful for EC2 deployment in psynet, as psynet has custom config variables.
In the past they had to all be commented out.
Default parameter `strict=True` (how it was before), but can be overridden when needed.
- Running EC2 command line tools with `dallinger ec2 …` with custom config variables in `.dallingerconfig`

Option to disable strict config variable loading

---

dallinger/experiment_server/dashboard.py
dallinger/experiment_server/experiment_server.py
dallinger/utils.py
tests/test_dashboard.py
tests/test_experiment.py

There's an inconsistency in how dashboard tabs are converted to endpoints. Endpoints are created via `/dashboard/<func_name>`. The issue is that in some cases the `<func_name>` is already used in another way, so `dashboard_<func_name>` is used. However, this leads to ugly URLs and it's cumbersome when some dashboard functions follow the convention and others don't.
To improve this, I provide a prefix (`dashboard_`) for all dashboard tab functions, e.g. `dashboard_develop()` instead of `develop()`, but remove this prefix in the URL if it exists.
- Locally and CI

Prefix all dashboard panels with `dashboard_` but remove this prefix in the endpoint

---

dallinger/experiment_server/dashboard.py

#7500 introduced a regression in `insert_tab_after_route`, such that `@dashboard_tab(after_route=...)` started failing. This PR fixes that.

Fix regression in insert_tab_after_route (see #7500)

---

dallinger/command_line/__init__.py
dallinger/command_line/docker.py
dallinger/config.py
dallinger/deployment.py
dallinger/heroku/tools.py

Implement support for setting the heroku region in the config
To implement support for setting heroku_region, I added to the existing heroku_teams settings. This appeared to work in testing for bartlett1932:
However, right before the experiment finishes deploying, there is an error in papertrail. It sounds unrelated, but I'm not sure:

Heroku_region support

---

.bumpversion.cfg
CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/chatroom_ws/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
demos/requirements.txt
demos/setup.py
pyproject.toml

- Ported `classproperty` decorator from PsyNet to Dallinger
- Added a hook for overriding hidden dashboard tabs and a hook for sorting the dashboard tabs
- Added option to disable strict config variable loading, which is useful for cross-compatibility with PsyNet
- Added new dashboard tab 'Logger' by dumping logs in `jsonl` format and streaming them to the frontend, incl. search functionality and added new dependencies ansi2html, beautifulsoup4, pygtail, and python-json-logger
- Added standardized status reporting across recruiters:
- Introduced new class `RecruitmentStatus` which reports standardized status across recruiters. The class contains the following entries:
- `participant_status`: this is a histogram in dictionary format where the keys are the statuses of submissions (e.g. …

Release 11.2.0

---

dallinger/experiment.py
dallinger/experiment_server/gunicorn.py
dallinger/recruiters.py

- Experiment hooks for server setup and termination, as well as worker termination and startup
- Experiment hook for recruiter error by overriding `logger.exception` in `recruiters.py`
- A `DevRecruiter` class for easy distinguishing from `MockRecruiter` or a regular `Recruiter`
Sometimes it is good to be notified when gunicorn workers are killed or when they restart or if the whole process is killed.
While you can catch graceful terminations like `SIGINT` (`Ctrl+C`) or `SIGTERM` (`kill`) with `atexit`, you cannot catch forced termination (`SIGKILL`, `Ctrl+K` or `kill -9 <pid>`). Forced termination are especially important, because they can originate from memory leaks. However, `gunicorn` also provides hooks for forceful termination
- Locally (`psynet debug local --verbose`)
- Local …

Three additions: gunicorn experiment hooks, customisable recruiter error handling, `DevRecruiter` class

---

dallinger/command_line/ec2.py

- Update AMI image for EC2 provisioning to use Ubuntu 24.04

Update AMI image for EC2 provisioning to Ubuntu 24.04

---

LICENSE
dallinger/config.py
tests/test_utils.py

This PR removes the dependency on `setuptools.dist.strtobool`, which was causing a deprecation warning.

Remove dependency on setuptools.dist.strtobool

---

dallinger/utils.py
tests/test_utils.py

This PR gives a more informative error message when `FileSource` tries to copy a broken symlink.

Better error message on broken symlink

---

.bumpversion.cfg
CHANGELOG.md
dallinger/version.py
demos/dlgr/demos/bartlett1932/constraints.txt
demos/dlgr/demos/chatroom/constraints.txt
demos/dlgr/demos/chatroom_ws/constraints.txt
demos/dlgr/demos/concentration/constraints.txt
demos/dlgr/demos/function_learning/constraints.txt
demos/dlgr/demos/iterated_drawing/constraints.txt
demos/dlgr/demos/mcmcp/constraints.txt
demos/dlgr/demos/rogers/constraints.txt
demos/dlgr/demos/sheep_market/constraints.txt
demos/dlgr/demos/snake/constraints.txt
demos/dlgr/demos/twentyfortyeight/constraints.txt
demos/dlgr/demos/vox_populi/constraints.txt
demos/requirements.txt
demos/setup.py
pyproject.toml

- Added support for screen-out-submissions in ProlificRecruiter
- Added experiment hooks for server setup and termination, as well as worker termination and startup
- Added experiment hook for recruiter error by overriding `logger.exception` in `recruiters.py`
- Added `DevRecruiter` class for easily distinguishing between `MockRecruiter` or a regular `Recruiter`
- Prolific command line improvements:
- Added `dallinger prolific list studies ` to list all studies associated with an account (across workspaces and projects)
- Added `dallinger prolific delete-drafts` delete all unpublished draft surveys in the account
- Only show deprecation warnings once
- When loading the defaults, load `.dallingerconfig` last
- Give a more informative error message when `FileSource` tries to copy a broken …

Release 11.3.0

---

dallinger/experiment_server/experiment_server.py

- Disabled browser check that returned an error response when a duplicate participant was detected in live mode

Disable browser check for duplicate participants

---

dallinger/heroku/tools.py
dallinger/utils.py
tests/test_heroku.py
tests/test_utils.py

`dallinger debug` previously waited for a particular log line to be printed to know that the server had started successfully. This log line is not printed when `loglevel` > 1, however. I have therefore changed this logic to instead check whether the server is available by listening to the appropriate port.

Fix `dallinger debug` to work when `loglevel` > 0

---

dallinger/heroku/clock.py

Now that `scoped_session_decorator` has been applied to `run_status_check`, we think it should be safe to reinstate `async_recruiter_status_check`, which previously was causing some kind of deadlock on long-running experiments.

Reinstate async_recruiter_status_check

---

tests/test_deployment.py

httpbin is flakey and causes tests to fail. httpbingo seems to be a more recent, more reliable alternative.

Switch from httpbin to httpbingo

---

docs/source/developing_dallinger_setup_guide.rst
docs/source/installing_dallinger_for_users.rst

This PR updates documentation for the Dallinger setup.
See #7788. This PR will:
* Remove references to specific Ubuntu versions
* Remove references to specific Python versions, recommending to check the project `pyproject.toml` instead
* Rework the "Install Python" sections for both MacOS and Ubuntu to discourage Homebrew/system Python and recommend the official installer first. or pyenv
* Recommend using Python built-in venv module to setup the Python virtuelenv, and suggest virtualenvwrapper as a nice to have
* Fix typos
* Better grouping for related sections

Update installation docs

---

docs/source/docker_support.rst
docs/source/ec2_deployment.rst

This PR update the EC2 provisioning and deployment docs with suggested changes to address issues found in testing related to issue #7789  .
For a description of issues encountered while testing EC2 deployments, see related issue #7789 .
Docs can be generated by installing the `requirements-readthedocs.txt` dependencies and running `make html` from the `docs` folder. The generated docs can be browsed from the `docs/build/html` folder.

Update docs related to EC2 deployments

---

.readthedocs.yaml
constraints.txt
dallinger/experiment.py
dallinger/experiment_server/worker_events.py
dev-requirements.txt
docs/source/conf.py
docs/source/the_experiment_class.rst
docs/source/using_websockets.rst
pyproject.toml
requirements-readthedocs.txt
requirements.txt
scripts/update_dependencies.sh
tests/test_command_line.py
tests/test_experiment.py

This PR implements more complete documentation for the Dallinger WebSocket implementation.
See #5388. This documentation provides additional information about what WebSocket features Dallinger provides and how to use them. This PR also relates to #7788 and may be influenced by the eventual implementation of that ticket. Specifically, the updated documentation provides some suggestions for how chat functionality might be implemented by an experiment.

More extensive WebSocket documentation

---

dallinger/config.py

We don't support python2, so we shouldn't be adding `__init__.py` files to working directories when registering experiment package.
Potentially causes problems, and has no benefit.

Get rid of python2 __init__.py creation

---

dallinger/experiment.py
dallinger/experiment_server/experiment_server.py

It is now possible to display custom HTML content on the deployed experiment's index page by customising the `Experiment.index_html` property.
The PR is covered by existing tests.

Add support for customizing the index page via the Experiment class

---

dallinger/experiment.py
dallinger/experiment_server/dashboard.py
tests/test_dashboard.py

Related to issue #7969 
This PR refactors the database dashboard to use **server-side pagination** with DataTables. This implied also implementing **server-side SearchPanes support** to not break existing functionality.  
- Switched from client-side pagination and filtering to fully server-side processing
- Updated `table_data()` to handle paging, searching, ordering, and JSON serialization of rows
- Added `table_search_panes()` to compute SearchPanes options server-side with configurable thresholds and max distinct value limits
- Implements `table_columns()` to include only columns with actual data (checked via fast SQL `EXISTS` queries)
- Updated tests to test for server side options, data, search and filtering
Client-side pagination and filtering caused **performance issues** with …

Server-side pagination in dashboard database tab

---

dallinger/experiment_server/dashboard.py
dallinger/experiment_server/utils.py
tests/test_dashboard.py

The new DataTables database view was failing in certain situations with a 'URL too long error'. I've fixed this problem by using POST instead and passing the filter specification in the request body rather than in the URL.
Tested manually.

Switch DataTables to POST to avoid long URL problem

---

dallinger/command_line/utils.py
tests/test_command_line.py

- Allow customization of  maximum experiment size in MB via `EXP_MAX_SIZE_MB` environment variable

Allow customization of maximum experiment size in MB via EXP_MAX_SIZE_MB environment variable

---

dallinger/command_line/utils.py
tests/test_command_line.py

Increase the default maximum experiment size from 50 to 256MB

Change default max experiment size to 256 MB

---

dallinger/mturk.py
dallinger/recruiters.py
tests/test_mturk.py

- Fixed bug in MTurk `create_qualification_type` which was causing false-positive error logging.

Fix handling of MTurk DuplicateQualificationNameError
