.codecov.yml
Turn off the code status based on patch coverage.
=> Add Codecov settings file

.travis.yml, Dangerfile, Gemfile
[Danger](http://danger.systems) runs as a bot (@DallingerBot) in our CI process. It codifies pull-request etiquette.
=> Check PRs with Danger

README.md
=> Fix README license badge

dallinger/heroku/requirements.txt, requirements.txt
Adds pypandoc 1.2.0 to the requirements.
Pypandoc is a requirement, but it was not in the requirements file.
=> Add pypandoc 1.2.0 to reqs

setup.py
Setup.py does not play friendly with imports inside of it.
=> Fix issue with installation on PyPi

README.md
=> README badge for demos

docs/source/index.rst
Automatically add all the demos to the table of contents of the documentation.
=> Compute demo TOC automatically

.travis.yml
=> Convert Markdown README to rst

.travis.yml
This PR tries to fix some issues with Travis deploys.
=> Move skip_cleanup to ind. deploys

examples/iterated-drawing/requirements.txt, examples/sheep-market/requirements.txt, setup.cfg
It was missing a few demos and automatically added tags & commits,
which doesn’t jibe with the current workflow.
=> Fix issue with bumpversion

docs/source/spelling_wordlist.txt, examples/bartlett1932/README.md, examples/chatroom/README.md, examples/function-learning/README.md, examples/iterated-drawing/README.md, examples/mcmcp/README.md, examples/rogers/README.md
This improves the demo titles so that they look better in the docs.
=> Improve demo titles

README.md, docs/source/_static/style.css, docs/source/conf.py
Improves the style of the documentation, a little.
=> Style docs

MANIFEST.in
This distributes the image when the package is released.
=> Include portrait in manifest

Dangerfile
=> Improve Dangerfile

.github_changelog_generator, setup.cfg
This PR improves `bumpversion` configuration and settings for the changelog.
=> Improve release process

dallinger/command_line.py
=> Use proper RFC 4122 UUIDs

.hound.yml
Adds Python checking to Hound CI.
=> Add Python to Hound CI

requirements.txt
Updates psiTurk-dallinger to the latest version.
=> Update psiTurk to 3.0.1

.pyup.yml, Dangerfile
Assing @pyup-bot PRs the label "enhancement".
=> Assign Pyup PRs a label

docs/source/command_line_utility.rst, docs/source/demoing_dallinger.rst, docs/source/index.rst, docs/source/spelling_wordlist.txt
Monica pointed out that the demos directory is not accessible to someone who installed Dallinger using pip.
=> Fix inconsistency in docs

Dangerfile, dallinger/experiments.py, docs/source/command_line_utility.rst
Thanks to @mongates for the catches.
Fixes #211.
=> Fix typos in documentation

setup.cfg
=> Add 2048 to bumpversion config

dallinger/heroku/clock.py
=> Add missing import statement

Dangerfile, README.md, demos/snake/requirements.txt
- README badge count
- Snake demo requirements
=> Improve Dangerfile and fix missed issues

docs/source/_templates/layout.html
GetSiteControl (getsitecontrol.com) provides widgets for social sharing
and collecting email addresses.
=> Use GetSiteControl on documentation site

docs/source/_templates/layout.html
Fix an issue with the GetSiteControl JavaScript being in a double script tag.
=> Fix double script tags

dev-requirements.txt, docs/source/acknowledgments.rst, docs/source/build_demo_docs.py, docs/source/conf.py, docs/source/dallinger_the_scientist.rst, docs/source/index.rst
1. Reorganize documentation TOC
2. Add acknowledgments page
3. Allow Markdown source files
4. Fix missing images
=> Improve documentation

dallinger/networks.py
=> DiscreteGenerational: change Node to type(node)

setup.py
=> Add PyPi classifiers

demos/concentration/README.md
=> Fix screenshot of Concentration game

dallinger/__init__.py, dallinger/command_line.py, dallinger/heroku/__init__.py, dallinger/heroku/tools.py, tests/test_heroku.py
Start to refactor the CLI, removing reusable functions into the core modules.
=> Refactor CLI

dallinger/frontend/static/scripts/dallinger.js
There was an infinite recursion that was spewing hundreds of requests
to create new blank questions. Oops.
=> Fix bug in question submission

.travis.yml, Dangerfile, Gemfile
[Danger](http://danger.systems) (@DallingerBot) now warns if any of these style guidelines are violated:
- Commit subject begins with a capital letter (subject_cap)
- Commit subject is no longer than 50 characters (subject_length)
- Commit subject does not end in a period (subject_period)
- Commit subject and body are separated by an empty line (empty_line)
Consistency in style.
I tested the new code on this PR. The original PR had a title that was too long and which began with a lowercase letter. Danger gave 2 warnings. Now it should strike them out.
=> Lint commit messages

dallinger/command_line.py, dallinger/heroku/tools.py
=> Use check_call rather than call in order to reveal errors

dallinger/command_line.py
=> Improve verify command

dallinger/command_line.py
@alecpm - I made a handful of small changes (mostly var names) while making sure I understood your updates to setup_experiment() for stories 153/154. Merge if you like.
=> Stories/153 154 bartlett sandbox run (small revisions from Jesse)

docs/source/developing_dallinger_setup_guide.rst
Add command for starting Postgres for users who use a virtual environment in Anaconda to run Python 2.7
=> Add alternative Postgres starting command

dallinger/command_line.py, dallinger/experiment.py
The export data functionality from the command line module was refactored a bit to allow using it from the experiment module.
Implements story 155.
Not finished with testing yet.
=> Export data using the experiment module

docs/source/gsoc.rst, docs/source/spelling_wordlist.txt
[For GSoC application, already seen by @thomasmorgan.]
=> Add draft of GSoC instructions

dallinger/command_line.py, dallinger/config.py, dallinger/config/.dallingerconfig, dallinger/default_configs/local_config_defaults.txt, dallinger/experiment.py, dallinger/heroku/clock.py, dallinger/recruiters.py, demos/2048/config.txt, demos/2048/experiment.py, demos/bartlett1932/config.txt, demos/chatroom/config.txt, demos/chatroom/experiment.py, demos/concentration/config.txt, demos/concentration/experiment.py, demos/function-learning/config.txt, demos/iterated-drawing/config.txt, demos/mcmcp/config.txt, demos/rogers/config.txt, demos/sheep-market/config.txt, demos/snake/config.txt, demos/snake/experiment.py, demos/vox-populi/config.txt, docs/source/aws_etc_keys.rst, docs/source/configuration.rst, docs/source/index.rst, tests/conftest.py, tests/experiment/dallinger_experiment.py, tests/test_config.py, tests/test_recruiters.py
This is a work-in-progress branch for cleaning up remnants of the old configuration and improving consistency & documentation regarding configuration throughout the codebase.
=> Clean config [WIP]

dallinger/command_line.py, dallinger/config.py, dallinger/config/.dallingerconfig, dallinger/default_configs/local_config_defaults.txt, dallinger/experiment.py, dallinger/heroku/clock.py, dallinger/recruiters.py, demos/2048/config.txt, demos/2048/experiment.py, demos/bartlett1932/config.txt, demos/chatroom/config.txt, demos/chatroom/experiment.py, demos/concentration/config.txt, demos/concentration/experiment.py, demos/function-learning/config.txt, demos/iterated-drawing/config.txt, demos/mcmcp/config.txt, demos/rogers/config.txt, demos/sheep-market/config.txt, demos/snake/config.txt, demos/snake/experiment.py, demos/vox-populi/config.txt, docs/source/aws_etc_keys.rst, docs/source/configuration.rst, docs/source/index.rst, tests/conftest.py, tests/experiment/dallinger_experiment.py, tests/test_config.py, tests/test_recruiters.py
(Botched PR #447 so am merging this one instead.)
=> Cleanup configuration

CHANGELOG.md
Adds release nots for version 2.7.1.
=> Write release notes for version 2.7.1

.github_changelog_generator, setup.cfg
This deletes a configuration file for an unused changelog generator.
=> Delete unused changelog generator cofiguration

docs/source/_static/style.css
Adjusts padding for headings and code blocks.
=> Tweak documentation styling

tests/conftest.py, tests/test_bots.py
Extends PR #536 by adding Chrome to the bot tests.
=> Add tests for Chrome webdriver

demos/chatroom/experiment.py, demos/chatroom/requirements.txt, requirements.txt
This is a light edit of the `chatbot` branch by @cguardia, ScrumDo story #175.
=> Chatbots in chatroom demo

dallinger/command_line.py, tests/test_command_line.py
Add a verify_id() function to check if the experiment ID is provided by the user and check if the first few characters of the string contain "dlgr-".
Issue #406 asks for an enhancement to notify users when they enter ```dlgr-``` via the command line as an experiment ID.
This code has been tested using the following dallinger commands: logs, hibernate, summary, export, deploy, awaken.
Example:
```
dallinger logs --app dlgr-XXXX
```
=> Add branch to fix UUID issue

demos/mcmcp/experiment.py
=> (In-repo #580.)

dallinger/command_line.py, dallinger/config.py, dallinger/experiment_server/experiment_server.py, demos/2048/templates/ad.html, demos/bartlett1932/templates/ad.html, demos/chatroom/templates/ad.html, demos/concentration/templates/ad.html, demos/function-learning/templates/ad.html, demos/iterated-drawing/templates/ad.html, demos/mcmcp/templates/ad.html, demos/rogers/templates/ad.html, demos/sheep-market/templates/ad.html, demos/snake/templates/ad.html, demos/vox-populi/templates/ad.html, tests/experiment/templates/ad.html
1. Add UUID to ads in sandbox and debug mode for all demos, add 'id' key to the config
2. Fix whitespace in ad.html's
Issue #393 describes confusion when creating multiple ads in the sandbox
- Testing on the sandbox fails because it pulls a different version of Dallinger that does not contain changes made here.
- Testing in debug mode works.
=> Adding application id to sandbox/debug mode

dallinger/config.py
See https://github.com/Dallinger/Dallinger/issues/602
No new automated tests. Tested manually.
=> Swallow IOError, but not ImportError

dallinger/experiment_server/experiment_server.py, dallinger/experiment_server/worker_events.py, tests/test_experiment_server.py
Improve the testability (and hopefully overall design) of the `experiment_server.worker_function` function
`worker_function` is difficult to test because it has many branches and complex integration with the DB transactional support. This PR is an effort to stop the bleeding and start the testing.
Code from the original function has been copied into a new set of small classes with a dispatcher based on event_type name. Since this change alone was significant, no additional refactoring was done on the individual bits, beyond some required mechanical name changes. There are tests for the class dispatcher, and several "real" tests for the AssignmentSubmitted class.
Once the extracted code was fully under test, it was safe to do additional refactoring for clarity.
=> Worker function testability

.travis.yml, docs/source/spelling_wordlist.txt
Update to Trusty Ubuntu distribution on Travis
=> 217 fix travis

dallinger/frontend/templates/complete.html, demos/2048/templates/ad.html, demos/bartlett1932/templates/ad.html, demos/chatroom/templates/ad.html, demos/concentration/templates/ad.html, demos/function-learning/templates/ad.html, demos/function-learning/templates/default.html, demos/iterated-drawing/templates/ad.html, demos/mcmcp/templates/ad.html, demos/rogers/templates/ad.html, demos/sheep-market/templates/ad.html, demos/snake/templates/ad.html, demos/vox-populi/templates/ad.html, tests/experiment/templates/ad.html, tests/experiment/templates/default.html
=> Circumvent ad blocker

dallinger/frontend/static/scripts/dallinger.js
Part of a continuing effort to provide better feedback to users when something goes wrong during Griduniverse play or post-play actions.
An error response was temporarily set up in the `/question` route to trigger an error.
=> Return a deferred from submitQuestionnaire, and show error page on failure

dallinger/models.py, tests/test_models.py
When failing a participant, go through all questions from a participant and fail them.
Issue 136
=> fail questions when failing a participant

dallinger/command_line.py, tests/test_command_line.py
Small bump in test coverage and refactored code
=> Better coverage for sandbox and deploy commands

dallinger/command_line.py, dallinger/data.py, dallinger/experiment.py, dallinger/heroku/__init__.py, dallinger/heroku/tools.py, dallinger/utils.py, tests/conftest.py, tests/test_command_line.py, tests/test_heroku.py
Test coverage and refactoring of this complex CLI helper function and its service code
* improve coverage
* Improve code quality safely
=> Tests for deploy_sandbox_shared_setup

.travis.yml, dallinger/db.py, docs/source/developing_dallinger_setup_guide.rst
=> show a warning when db user does not exist; update db user permissions

docs/source/developing_dallinger_setup_guide.rst, docs/source/docker_setup.rst, docs/source/index.rst, docs/source/installing_dallinger_for_users.rst, docs/source/troubleshooting.rst
#759 Add documentation for installation, troubleshooting, and Docker support info.
This addresses some complications in installation identified at ASU
=> Improving documentation

tests/test_mturk.py
=> Bump extendhit() timeout to 30 secs

dallinger/frontend/static/scripts/dallinger.js
I made a new PR because the tests were failing due to permission errors on @pkrafft's forked PR #798
=> Fix bug in submitResponses (2)

dallinger/utils.py
Revised implementation of PR #810 
This version uses redirection of stderr to a temporary file as a safer alternative to rerunning a failed git command to collect error output.
* Same manual tests as #810
=> Better git output 2

dallinger/frontend/static/scripts/dallinger2.js
Fixes a bug where participants 1...(n-1) are stuck in the waiting room.
=> Fix bug in waitForQuorum

dallinger/networks.py, tests/conftest.py, tests/test_networks.py
Implementation of split-sample experimental design in a new Network subclass.
Split-sample experimental design involves randomly splitting collecting data into exploratory and confirmatory data subsets.  Split-sample experimental design allows for flexible non-preregistered but statistically valid exploratory data analysis.
The committed changes include tests in the test_networks class, and the added code should not have spillover effects to other code.
=> Implemented split sample network

.travis.yml
Another attempt to fix the new changes to uploading with PyPi. I set `all_branches: true` in order to test PYPI deployment on the current branch.
=> Add pypi server link to travis

docs/source/contributing_to_dallinger.rst, docs/source/index.rst, docs/source/running_bots.rst, docs/source/setting_up_notifications.rst, docs/source/troubleshooting.rst
Improve documentation.
New features have been added that require documentation.
Tested using the Dallinger using the "read the docs" URL locally
=> Add Documentation

tests/test_command_line.py
=> Fix test_xxx_isolation tests so they can run independent of tempdir location

dallinger/experiment_server/experiment_server.py, tests/test_experiment_server.py
Add an index page with config information.
Story 310 required adding a more useful index page.
=> Add index view with config info

dallinger/experiment_server/experiment_server.py
Adjusts the waiting-room overrecruitment logic to include further-along-than-working statuses.
=> Adjust overrecruitment logic

dallinger/command_line.py
Fix for simple coding goof found during review.
=> Use the default parameter we define

.codecov.yml
Seems to fix #1024, though I don't know why it worked previously.
=> Enable patch status

dallinger/mturk.py, tests/test_mturk.py
Fixes #1052 
Don't put burden of rounding bonus amounts on custom experiments, since it's an implementation detail of the recruitment system.
=> Round bonus amounts to currency format for MTurk

dallinger/experiment.py
This adds a button to the `jupyter_replay` widget that attempts to replay
the experiment in real-time. It advances the current state in a loop
controlled by a thread. At the end of each iteration the amount of wall
time that has passed is used to determine the next state to restore up to.
A thread is used to ensure the kernel remains responsive, allowing the user
to pause the replay, which causs the thread to error out.
Easier viewing of experiment data
Cursory manual testing only. I'd really appreciate some other eyes on this
=> Add realtime playback functionality

dallinger/config.py, tests/test_config.py
=> Fix for issue 1079: write all keys if filter_senstive=False

dallinger/bots.py
Bots using BotBase (such as the bartlett1932 bots) were not successfully completing the questionnaire. Added code for filling it up before submitting.
=> make sure robots fill up questionnaire before submitting.

docs/source/index.rst, docs/source/rewarding_participants.rst
This adds documentation on types of bonus calculations, when they're appropriate, and best practices to avoid overpaying.
Some experimenters were unsure about the best way of approaching this.
This was reviewed by @mongates for clarity, and re-read by myself multiple times for correctness.
=> Document calculating bonuses

dallinger/experiment.py
This allows widgets to determine a range of times the user
would be interested in, for example by snipping the waiting room and
survey parts of the dataset.
This makes juypter replays more user friendly by allowing an experiment to exclude its waiting room and surveying from replay times.
=> Support having a user-visible time range for jupyter replays

docs/source/aws_etc_keys.rst, docs/source/troubleshooting.rst
Suggestions taken from the issue.
=> document improvements from ticket #1135

.pyup.yml, dev-requirements.txt
=> Tell pyupbot to ignore pycodestyle version 2.4.0

docs/source/developing_dallinger_setup_guide.rst, docs/source/installing_dallinger_for_users.rst
Small one line update to the docs
=> docs - updated how to install pip on osx

dallinger/deployment.py, tests/test_deployment.py
Fixes a python2 bug, and another bug with `_handle_launch_data()`
=> Fix py27 and launch bugs

.pyup.yml, .travis.yml, MANIFEST.in, constraints-deps.txt, constraints.txt, requirements.txt, tox.ini
Remove all non-default packages from PyUp config.
Too many PRs
PyUp configuration appears to be impossible to test, so it hasn't been.
=> PyUp fixes

.pyup.yml
Don't let PyUp search the repo for random requirements files
=> One last PyUp fix

docs/source/configuration.rst
This documents the difference between the web and worker dynos, as
well as providing guidance on picking their values, and the values
of a few other parameters that affect experiment success liklihood
=> Add documentation on choosing config values

docs/source/configuration.rst
Configuration keys used together to prevent repeat participants warrant specific explanation in addition to the individual definition of each config key.
This is an FAQ in Slack #help.
=> Address FAQ in configuration docs

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, setup.cfg, setup.py
Documentation improvements and additions:
+ New theme that supports searching of the documentation
+ Styling improvements to some documents for increased readability
+ Updated description of what Dallinger is
+ Add Preventing Repeat Participants section to Configuration documentation
- Miscellaneous bug fixes
=> Release version 5.0.1

dallinger/experiment_server/experiment_server.py, tests/test_experiment_server.py
Addresses #1550 
* manual testing with sheep_market demo, where the problem was uncovered (this testing requires fixes included in stories/434-working-demos)
=> Issue 1550: fail early on undefined participant values

demos/dlgr/demos/chatroom/static/scripts/experiment.js, docs/source/creating_an_experiment.rst
Fixes the last remnants of https://github.com/Dallinger/Dallinger/issues/741
=> Standardize on dallinger.goToPage()

docs/source/experiment_data.rst
=> Correct dallinger export syntax in doc

demos/dlgr/demos/rogers/README.md, demos/dlgr/demos/rogers/experiment.py, demos/dlgr/demos/rogers/templates/instructions/instruct-ready.html, demos/pytest.ini, demos/tests/test_rogers.py
This PR makes some updates to the Rogers' demo. Specifically it uses dallinger configuration for the experiment configuration and updates the experiment instructions to reflect the experiment as configured. Additionally, the tests now run to completion and reflect recent logic changes. The documentation has been updated to reflect the new configuration parameters.
See [ScrumDo Story 455](https://app.scrumdo.com/projects/story_permalink/1777501) which describes the desired refactoring. Most essential refactoring appears to have been mostly completed during prior demo updates. What remains is primarily modernizing the configuration of the experiment. Ideally, the tests would also have been refactored to be less monolithic, but I feel that may have been out of scope for this story. It also …
=> Minor Refactoring of Rogers Demo

CHANGELOG.md, THANKS.md, setup.py
=> Release 5.0.3 take 2

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, setup.cfg, setup.py, yarn.lock
Documentation improvements and additions:
+ New documentation section on Networks added
+ Reintroduce working Chatroom demo
--------------------------------------------------------------------------------------------------------
- Start monitoring Javascript code coverage
- Change configuration of certain demos to work in free heroku tier (hobby)
--------------------------------------------------------------------------------------------------------
- Fixed: Prevent Google Chrome from showing default browser popup when running Dallinger in debug mode
- Fixed: Fixed profiles issues with Google Chrome on OSX
=> Release 5.0.4

.codeclimate.yml
It's hard to see the effect of configuration changes on branches, so we may just need to merge it.
Evaluate if CodeClimate can be configured to provide more valuable feedback.
=> Update CodeClimate configuration

.codeclimate.yml
Everything must go through review for merge, unfortunately.
=> More codeclimate tweaks

demos/dlgr/demos/iterated_drawing/models.py, demos/dlgr/demos/iterated_drawing/templates/layout.html
The demo had two problems. It used string handling that was not compatible with Python 3, and the javascript import ordering was wrong in the layout template.
It works now both locally and in Heroku.
=> Fix iterated drawing demo.

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, docs/source/demo_index.rst, setup.cfg, setup.py
=> Release version 5.0.5

CHANGELOG.md, dallinger/deployment.py, tests/test_deployment.py
Addresses #1651 
(See issue)
- Manual testing w/ Bartlett1932
=> Log current attempt count when calling launch route

docs/source/developing_dallinger_setup_guide.rst, docs/source/installing_dallinger_for_users.rst, docs/source/python_module.rst
Several fixes to documentation were added in this PR.
Expanded git installation instructions have also been included.
=> Various documentation fixes

docs/source/index.rst
Add a paragraph about beginner documentation and a link to it.
Integrate other documentation work with the main documentation.
=> Add link to beginner's guide

tests/test_data.py
Many of the tests for `dallinger.data` work only with local files and are relatively fast. This PR splits those out from the ones that interact with Amazon S3, so they can be included in the tests run without the `--runslow` option.
=> Separate slow S3 data tests for faster local ones

docs/source/index.rst, docs/source/recruitment.rst
Add some docs for over-recruitment handling.
=> Recruitment docs

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Prep 5.0.7 release

CHANGELOG.md
Set up changelog for future additions.
=> Prep changelog for next round of development

dallinger/heroku/clock.py, dallinger/recruiters.py, tests/test_heroku.py, tests/test_recruiters.py
Small changes to increase consistency with my general recruiter API recommendations:
https://github.com/Dallinger/Dallinger/issues/1718
=> Simplify recruiter ping

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/config.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, docs/source/configuration.rst, docs/source/creating_an_experiment.rst, setup.cfg, setup.py
=> Prep release 5.1.0

constraints-deps.txt
=> Upgrade MarkupSafe

dallinger/utils.py, tests/test_utils.py
@jessesnyder Good news, I finally found the problem in the ignore file work that I was looking for.
=> Fix bug where committed files were excluded in git client

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release6.0.0

tests/conftest.py
Improvements to existing test infrastructure
=> Test fixups

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py, tests/test_api.py
=> Release6.2.0

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release6.2.1

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release version 6.2.2.

dallinger/deployment.py, dallinger/experiment.py, dallinger/experiment_server/dashboard.py, dallinger/frontend/static/css/dashboard.css, dallinger/frontend/templates/base/dashboard.html, dallinger/frontend/templates/dashboard_home.html, dallinger/frontend/templates/dashboard_monitor.html, dallinger/utils.py, docs/source/monitoring_a_live_experiment.rst, tests/experiment/templates/dashboard_home.html, tests/test_dashboard.py
The PR implements a basic framework for the monitoring dashboard tab. See #2219 for details.
Automated tests for the dashboard have been added. It has been tested manually with different demo experiments in debug mode.
=> Initial implementation of monitoring Dashboard (issue #2219)

dallinger/deployment.py, dallinger/experiment_server/dashboard.py, dallinger/frontend/templates/dashboard_cli.html, tests/test_dashboard.py
This adds a simple new dashboard panel with some documentation on experiment lifecycle commands.
See #2189
=> Add a dashboard panel with some helper documentation for experiment lifecycle

dallinger/config.py, dallinger/deployment.py, dallinger/experiment.py, dallinger/heroku/clock.py, docs/source/creating_an_experiment.rst, docs/source/required_experiment_files.rst, pytest.ini, tests/experiment/dallinger_experiment.py, tests/test_deployment.py
This adds a new callable on the module scope to provide additional static resources, as well as a classmethod to do the same. It also improves the experiment class detection code to better handle multiple subclass chains.
See #2115 - this will allow for better support of statics common to multiple experiments
Unit tests only. This needs some real-world testing before merging, but I'd appreciate some review too.
=> Allow user-defined statics

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release version 6.3.0

dallinger/bots.py
Fixes #2247 
Tested with Chromedriver
=> Update to avoid deprecation warning

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release6.3.1

dallinger/frontend/static/css/dashboard.css, dallinger/frontend/templates/base/dashboard.html
Moved logout button to top of page. Fixed issue with Monitoring details pane layout that @jessesnyder noticed when testing using Bartlett1932.
See #2275 and https://www.screencast.com/t/q1zLJExiJ
Manual testing only
=> Move login button and fix details pane layout

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release 6.4.0

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release6.5.0

docs/source/command_line_utility.rst
=> Fix docs for dallinger compensate command

dallinger/heroku/tools.py, dallinger/recruiters.py, tests/test_recruiters.py
Addresses #2310 
- Sandbox deployment of Bartlett 1932
----
=> Add short version of app Heroku ID to HIT title, so title is unique

dallinger/experiment.py, dallinger/experiment_server/dashboard.py, dallinger/frontend/static/css/dashboard.css, dallinger/frontend/static/scripts/network-monitor.js, dallinger/frontend/templates/dashboard_monitor.html, docs/source/monitoring_a_live_experiment.rst, tests/test_dashboard.py
Fixes a few issues with the Network Monitoring Dashboard.
* Font Awesome icons are displayed properly on load
* Column layout is displayed correctly
* A new top level `Experiment` node is added to the visualization to aid in grouping. All network roles (under which Networks are grouped) are connected to the Experiment node.
* A new experiment method `node_visualization_options` is available returning a dictionary of values that will be injected into the vis.js options configuration for experiment specific layout/visualization tweaks.
* The default node spacing has been increased.
* Documentation updates
See issue #2419
Through the web testing in debug mode and additional automated tests.
=> Fix visualization issues in network monitor dashboard

CHANGELOG.md, dallinger/deployment.py, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, docs/source/contributing_to_dallinger.rst, setup.cfg, setup.py
=> Release6.6.0

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/requirements.txt, demos/dlgr/demos/chatroom/requirements.txt, demos/dlgr/demos/concentration/requirements.txt, demos/dlgr/demos/function_learning/requirements.txt, demos/dlgr/demos/iterated_drawing/requirements.txt, demos/dlgr/demos/mcmcp/requirements.txt, demos/dlgr/demos/rogers/requirements.txt, demos/dlgr/demos/sheep_market/requirements.txt, demos/dlgr/demos/snake/requirements.txt, demos/dlgr/demos/twentyfortyeight/requirements.txt, demos/dlgr/demos/vox_populi/requirements.txt, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release7.0.0

.github/workflows/ci.yml, dallinger/bots.py, dallinger/default_configs/global_config_defaults.txt, dallinger/pytest_dallinger.py, dallinger/recruiters.py, demos/dlgr/demos/bartlett1932/config.txt, demos/tests/conftest.py, tests/conftest.py, tests/test_bots.py, tox.ini
Bot runs of Bartlett1932 were failing both in tests and when run from the command line. It looks like an API change in `rq` was party responsible, as well as a change in the button class used in the Bartlett instructions.
To get tests working. I don't quite understand why we weren't seeing this test failure on all branches though.
Tested Bartlett1932 bot runs manually and in tests.
=> Fix selenium bot test issues

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release version 7.1.0.

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release7.2.0

.github/workflows/ci.yml
The github action code that takes care of differentiating between runs that should include mturk tests and runs that should not had an issue fixed in this PR.
=> Fix mturk condition in github actions

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release7.2.1

.github/workflows/ci.yml
There's been a long gap in codecov checking. Adding it back here.
=> Enable codecov on a separate branch from other changes to deal with unmerged changes.

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release v7.3.0

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.cfg, setup.py
=> Release7.4.0

dallinger/config.py, dallinger/default_configs/global_config_defaults.txt, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, docs/source/configuration.rst, scripts/update_experiments_constraints.sh
Adds a new `language` configuration parameter for setting a gettext language. Default value is `en`.
See #2963
=> Add language configuration parameter

CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, docs/source/contributing_to_dallinger.rst, scripts/update_experiments_constraints.sh, setup.cfg, setup.py, tests/conftest.py
=> Release7.5.0

dallinger/utils.py, tests/test_utils.py
Fix for #3119 
`dallinger debug` on Bartlett demo.
=> Fix quoting of chrome profile directory

.readthedocs.yml
I'm hoping this very simple change fixes the RtD compile. Let's see
See issue #2957 
It has not been tested, but should be safe since it only impacts the currently broken RtD config.
=> Try the most naive way to fix Read The Docs.

CHANGELOG.md, dallinger/version.py, demos/requirements.txt, demos/setup.py, scripts/update_experiments_constraints.sh, setup.cfg, setup.py
=> Release7.6.0

demos/dlgr/demos/bartlett1932/constraints.txt
Fixes the currently failing docker test.
=> Unpin dallinger in bartlett1932

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, docs/source/contributing_to_dallinger.rst, setup.py
=> Release7.8.0

.bumpversion.cfg, dallinger/version.py, demos/requirements.txt, demos/setup.py, setup.py
=> Bump version on master branch post-release

dallinger/prolific.py, docs/source/configuration.rst, docs/source/recruitment.rst
Documentation improvements emerging from Prolific recruiter beta testing.
=> Prolific Recruiter fixes and improvements

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release8.1.0

.bumpversion.cfg, CHANGELOG.md, constraints.txt, dallinger/version.py, demos/requirements.txt, demos/setup.py, dev-requirements.txt, requirements.txt, setup.py
=> Prerelease9.0.0

.bumpversion.cfg, CHANGELOG.md, constraints.txt, dallinger/version.py, demos/requirements.txt, demos/setup.py, dev-requirements.txt, requirements.txt, setup.py
=> Release9.0.0

constraints.txt, dev-requirements.txt, requirements.txt, setup.py, tox.ini
=> Release9.0.0pre

dallinger/db.py
By default sqlalchemy does not issue a CASCADE to PostgreSQL when dropping tables. This made `init_db` fail when tables depend on one another. The following MR fixes this by instructing the compiler to always issue CASCADE when dropping tables. I have tested this manually on my machine.
=> Issue CASCADE when dropping tables

dallinger/command_line/docker.py
The code that determined what version of `script` to use was causing issues with the terminal.
Invoking subcommands through the `script` utility makes sure they still output colors even if they're not directly connected to a terminal. Mac and Linux require different invocation syntaxes, and the code was probing to choose the right one to use.
During these probes it could potentially garble the terminal output.
Manually tested
=> Fix issue with script invocation making the terminal unusable

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release9.1.0

.github/workflows/ci.yml, .github/workflows/deploy.yml, scripts/github_releases.sh
Release PR, which chandler package as an attempt to fix #4468
=> Remove chandler ruby gem due to release errors

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release9.2.0

.pre-commit-config.yaml
Fix flake8 url to make the pre-commit test pass again
=> Fix flake8 url

dallinger/experiment_server/experiment_server.py
=> Prevent accessing database tables when checking for protected routes

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release9.2.1

.bumpversion.cfg, .pre-commit-config.yaml, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release 9.3.0

dallinger/config.py, dallinger/experiment.py, dallinger/experiment_server/experiment_server.py, tests/experiment/dallinger_experiment.py, tests/test_config.py
Implements a new customizable `config_defaults` method on the Experiment class that allows the user to specify custom default values for config variables. A test is included for this functionality.
=> Implement customizable config_defaults in experiment class

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.4.2

dallinger/utils.py, dev-requirements.txt, requirements.txt, scripts/update_dependencies.sh, scripts/update_experiments_constraints.sh, tests/test_deployment.py
**CHANGELOG**
* Infrastructure: Use new 'backtracking' resolver with pip-compile commands; remove extras from requirements files
=> Add '--resolver=backtracking' to pip-compile commands

.bumpversion.cfg, CHANGELOG.md, constraints.txt, dallinger/heroku/rq_gevent_worker.py, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, dev-requirements.txt, requirements.txt, setup.py
=> Release v9.4.3

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.5.0

dallinger/bots.py
The original Bot constructor assumed that the participant recruitment URL was specified in snake case. However the Docker CI tests use participant recruit URLs with camel case. This was causing Bot parameters (assignment ID, worker ID, participant ID) to be left unset, and this seemed to cause occasional CI errors in the Docker tests (search `worker_failed` in CI logs). This PR fixes this issue.
=> Make Bot constructor work with camelCase as well as snake_case

dallinger/command_line/docker_ssh.py, dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2, tests/test_docker.py
Fixed a bug where dollar signs weren't being escaped in docker-compose.yml.
Added a unit test to catch this issue.
=> Escape dollar signs in docker-compose.yml

dallinger/command_line/docker.py, demos/dlgr/demos/bartlett1932/config.txt, demos/dlgr/demos/chatroom/config.txt, demos/dlgr/demos/concentration/config.txt, demos/dlgr/demos/function_learning/config.txt, demos/dlgr/demos/iterated_drawing/config.txt, demos/dlgr/demos/mcmcp/config.txt, demos/dlgr/demos/rogers/config.txt, demos/dlgr/demos/sheep_market/config.txt, demos/dlgr/demos/snake/config.txt, demos/dlgr/demos/twentyfortyeight/config.txt, demos/dlgr/demos/vox_populi/config.txt, docs/source/demos_on_heroku.rst
* Replace Heroku obsolete dyno type 'hobby' with 'basic'
=> Replace Heroku obsolete dyno type 'hobby' with 'basic'

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.7.0

dallinger/command_line/docker_ssh.py, dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2
* Verify `docker_volumes` is not empty when adding additional volumes to `docker-compose.yml`.
See #5214
=> Fix bug adding volumes to docker-compose.yml

dallinger/utils.py, tests/test_utils.py
This PR aims at resolving the issue reported in #5232
=> Fix bug verifying installation of required packages

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.8.0

dallinger/docker/docker-compose.yml.j2, dallinger/docker/ssh_templates/docker-compose-experiment.yml.j2
Bug in the indentation in the yml file
=> Volume indentation

tests/test_db.py
* Fixed skipped Redis message queue test
See https://github.com/Dallinger/Dallinger/issues/5210
=> Fix skipped Redis message queue test

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.8.1

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.8.2

dallinger/command_line/docker_ssh.py
=> Add --update option to dallinger docker-ssh deploy

.github/workflows/ci.yml
=> Update setup-chromedriver to v2.1.0

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.9.0

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, setup.py
=> Release v9.10.0

Dockerfile
=> Fix and refactor Chrome/ChromeDriver download and installation

dallinger/config.py, dallinger/default_configs/global_config_defaults.txt, dallinger/recruiters.py, docs/source/configuration.rst, tests/test_recruiters.py
* Remove `prolific_reward_cents` and use `base_payment` for Prolific reward by multiplying `base_payment` with 100
* Deprecate `prolific_maximum_allowed_minutes`
=> Remove 'prolific_reward_cents' and deprecate 'prolific_maximum_allowed_minutes'

README.md
- Add support channel info to README
=> Add support channel info to README

.bumpversion.cfg, .pre-commit-config.yaml, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
=> Release v9.12.0

dallinger/command_line/docker_ssh.py
Related to #5181 .
This is a rebased version of branch `issue/5181-check-existing-app` and supersedes PR #5342 .
=> Better checks in dallinger docker-ssh for pre-existing apps with the same name

Dockerfile
**Changelog**
* Fix Chrome and ChromeDriver download link in Dockerfile
=> Fix Chrome and ChromeDriver download link in Dockerfile

dallinger/recruiters.py, tests/test_recruiters.py
- Added logic for customising recruiter classes
=> Add logic for customising recruiter classes; add tests

.bumpversion.cfg, CHANGELOG.md, Dockerfile, dallinger/version.py, demos/requirements.txt, demos/setup.py, pyproject.toml
=> Release v10.1.1

dallinger/experiment_server/experiment_server.py
Fixed a new bug whereby participants could not begin the experiment in Prolific.
=> Fix Prolific entry process

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
- Fixed a new bug whereby participants could not begin the experiment in Prolific.
=> Release v10.1.3

constraints.txt, dev-requirements.txt, docs/source/conf.py, pyproject.toml
=> Add sphinx-js back and point the repo to a tag of our fork with fixed pins

dallinger/config.py, dallinger/default_configs/local_config_defaults.txt, dallinger/heroku/rq_gevent_worker.py, dallinger/pytest_dallinger.py, dallinger_scripts/worker.py, docs/source/configuration.rst
- Added new config variable `loglevel_worker` for worker processes
=> Add customizable worker loglevel

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
=> Release v10.2.0

.readthedocs.yaml, docs/Makefile, requirements-readthedocs.txt, tox.ini
- Fixed building Sphinx documentation
See https://github.com/Dallinger/Dallinger/issues/6756
=> Fix building Sphinx documentation

dallinger_scripts/worker.py
See https://github.com/Dallinger/Dallinger/issues/6934
=> Fix bug in loading loglevel_worker

dallinger/config.py, dallinger/default_configs/global_config_defaults.txt, dallinger/prolific.py, dallinger/recruiters.py, docs/source/configuration.rst, tests/conftest.py, tests/test_prolific.py, tests/test_recruiters.py
CHANGELOG:
* Added new boolean config variable `prolific_is_custom_screening` which defaults to `False`.
=> Add new config variable 'prolific_is_custom_screening'

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
=> Release v10.2.3

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
=> Release v10.3.0

dallinger/data.py
- Scrub `client_ip_address` data from participant anonymous data export
=> Scrub 'client_ip_address' from participant anonymous data export

dallinger/data.py
- Improve handling of export when no AWS credentials are registered
=> Do not raise S3BucketUnavailable when exporting and AWS credentials are missing

.bumpversion.cfg, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
- Fixed bug in `get_assignments_for_study` that prevented a participant's status from being updated in Prolific studies via the `async_recruiter_status_check` scheduled job
=> Release  11.0.1

dallinger/command_line/lib/ec2.py
Use tenacity for better logging in `wait_for_instance`
=> Use tenacity for better logging in `wait_for_instance`

.bumpversion.cfg, .pre-commit-config.yaml, CHANGELOG.md, dallinger/version.py, demos/dlgr/demos/bartlett1932/constraints.txt, demos/dlgr/demos/chatroom/constraints.txt, demos/dlgr/demos/chatroom_ws/constraints.txt, demos/dlgr/demos/concentration/constraints.txt, demos/dlgr/demos/function_learning/constraints.txt, demos/dlgr/demos/iterated_drawing/constraints.txt, demos/dlgr/demos/mcmcp/constraints.txt, demos/dlgr/demos/rogers/constraints.txt, demos/dlgr/demos/sheep_market/constraints.txt, demos/dlgr/demos/snake/constraints.txt, demos/dlgr/demos/twentyfortyeight/constraints.txt, demos/dlgr/demos/vox_populi/constraints.txt, demos/requirements.txt, demos/setup.py, pyproject.toml
- Config variable `publish_experiment` now defaults to `False` for Prolific recruitment
- Updated dependencies
=> Release 11.1.1

dallinger/experiment.py, dallinger/experiment_server/experiment_server.py, dallinger/utils.py
Ported `classproperty` decorator from PsyNet to Dallinger in order to specify hidden dashboards in PsyNet too.
- Local experiments
=> Add `classproperty`

dallinger/command_line/docker_ssh.py
**Fixed**:
- The logger file was touched, but was not in the right folder
=> touch the logger file so that it exists when the container starts

dallinger/command_line/docker_ssh.py, dallinger/experiment_server/dashboard.py, dallinger_scripts/worker.py
- Only show the tail of the logger
- Move the `attach_json_logger` down to avoid breaking `gevent.monkey.patch_all()`
=> Fixes to the logger

dallinger/deployment.py, dallinger/recruiters.py
Removed unnecessary 'Initializing recruiter' messages
=> Remove unnecessary 'Initializing recruiter' messages

dallinger/command_line/docker_ssh.py, dallinger/config.py, docs/source/docker_support.rst
- Added new configuration variable `server_pem` for authenticating SSH connections to remote servers, e.g. when doing Docker SSH deployments
=> Added new configuration variable 'server_pem'

dallinger/command_line/docker_ssh.py
Related to issue #7968 
This PR introduces two new flags to the dallinger docker-ssh deploy command: `--remote-build` and `--push-remote-build`.
• The `--remote-build` flag allows users to build the experiment's Docker image directly on the remote server specified by docker-ssh, rather than building it locally and then transferring it.
• The `--push-remote-build` flag, when used in conjunction with `--remote-build`, instructs the remote server to push the newly built Docker image to a configured remote registry.
Previously, building Docker images for deployment always occurred locally. For users with limited local resources (e.g., CPU, memory, disk space) or slow internet connections, this process could be time-consuming and resource-intensive. Building the image directly on the remote …
=> Allow building and selectively pushing docker images remotely

dallinger/command_line/docker_ssh.py
see https://gitlab.com/PsyNetDev/PsyNet/-/issues/973
=> Fix a couple of bugs in new remote build code
